@props(['shipment','gaps'=>[]])
@php($totals=\App\Support\Shipment::totals($shipment))
@php($warnings=\App\Support\Shipment::warnings($shipment))
<div class="space-y-6">@foreach($warnings as $warning)<div class="alert alert-warning">{{ $warning }}</div>@endforeach<div><p class="eyebrow">Cargo</p><p class="mt-2 whitespace-pre-line text-sm leading-6">{{ $shipment['cargo_description']??'Not described yet' }}</p></div>
<div class="grid gap-6 sm:grid-cols-2">@foreach(['origin_country'=>'Origin country','origin_location'=>'Origin port / location','destination_country'=>'Destination country','destination_location'=>'Destination port / location','cargo_ready_date'=>'Cargo-ready date','arrival_date'=>'Requested arrival date','timing_flexibility'=>'Timing flexibility','pickup_address'=>'Pickup address','delivery_address'=>'Delivery address','incoterm'=>'Client-stated Incoterm','named_place'=>'Client-stated named place'] as $key=>$label)<div><p class="eyebrow">{{ $label }}</p><p class="mt-2 whitespace-pre-line text-sm leading-6">{{ $shipment[$key]??'Unknown / not provided' }}</p>@if($gaps['shipment.'.$key]??null)<p class="mt-2 text-xs leading-5 text-[#855600]">{{ $gaps['shipment.'.$key] }}</p>@endif</div>@endforeach</div>
<div class="flex flex-wrap gap-2"><span class="service-tag">{{ ($shipment['mode']??'unknown')==='unknown'?'Mode unknown':$shipment['mode'] }}</span><span class="service-tag">{{ \App\Support\Shipment::SCOPES[$shipment['scope']??'unknown'] }}</span>@foreach($shipment['services']??[] as $service)<span class="service-tag">{{ \App\Support\Shipment::SERVICES[$service] }}</span>@endforeach</div>
@if(($shipment['mode']??'unknown')==='LCL')<section><h3 class="mb-3 text-base">Package groups</h3>@forelse($shipment['packages']??[] as $index=>$row)<div class="mb-3 rounded-xl bg-slate-50 p-4"><p class="text-sm font-medium">Group {{ $index+1 }} · {{ $row['quantity']??'Unknown quantity' }} {{ $row['packaging_type']??'packaging unknown' }}</p><p class="mt-2 text-xs leading-6 text-slate-600">Group gross weight: {{ $row['gross_weight']??'Unknown' }} {{ $row['weight_unit']??'' }}<br>Dimensions per package: {{ $row['length']??'?' }} × {{ $row['width']??'?' }} × {{ $row['height']??'?' }} {{ $row['dimension_unit']??'(unit unknown)' }}</p></div>@empty<p class="text-sm text-slate-500">No package groups recorded.</p>@endforelse</section>@elseif(($shipment['mode']??'unknown')==='FCL')<section><h3 class="mb-3 text-base">Container rows</h3>@forelse($shipment['containers']??[] as $index=>$row)<div class="mb-3 rounded-xl bg-slate-50 p-4"><p class="text-sm font-medium">Row {{ $index+1 }} · {{ $row['quantity']??'Unknown quantity' }} × {{ $row['type']??'type unknown' }}</p><p class="mt-2 text-xs text-slate-600">Total row cargo gross weight: {{ $row['gross_weight']??'Unknown' }} {{ $row['weight_unit']??'(unit unknown)' }}</p></div>@empty<p class="text-sm text-slate-500">No container rows recorded.</p>@endforelse</section>@endif
<div class="grid gap-4 rounded-2xl bg-slate-50 p-5 sm:grid-cols-2"><div><p class="eyebrow">Calculated total gross weight</p><p class="mt-2 text-lg font-semibold">{{ $totals['weight']===null?'Unknown':$totals['weight'].' kg' }}</p><p class="mt-2 text-xs leading-5 text-slate-500">Sum of group / row totals; tonnes × 1,000, lb × 0.45359237.</p></div>@if(($shipment['mode']??'')==='LCL')<div><p class="eyebrow">Calculated package volume</p><p class="mt-2 text-lg font-semibold">{{ $totals['volume']===null?'Unknown':$totals['volume'].' m³' }}</p><p class="mt-2 text-xs leading-5 text-slate-500">Available only when every group has quantity and dimensions.</p></div><div class="sm:col-span-2"><p class="eyebrow">Client-declared total volume</p><p class="mt-2 text-sm">{{ isset($shipment['declared_volume'])?$shipment['declared_volume'].' m³':'Unknown' }}</p><p class="mt-1 text-xs text-slate-500">Source: {{ $shipment['declared_volume_source']??'Not recorded' }}</p></div>@if($totals['basis'])<details class="sm:col-span-2"><summary class="cursor-pointer text-xs text-accent">View calculation basis</summary><ul class="mt-3 space-y-2">@foreach($totals['basis'] as $basis)<li class="text-xs leading-6 text-slate-600">{{ $basis }}</li>@endforeach</ul></details>@endif @endif</div>
@if(!empty($shipment['special_flags']) || !empty($shipment['special_notes']))<div class="alert alert-warning"><x-icon name="warning-circle" /><div><p class="font-medium">Manual specialist review required</p><p class="mt-2 text-xs">@foreach($shipment['special_flags']??[] as $flag){{ \App\Support\Shipment::SPECIAL[$flag] }}{{ $loop->last?'':' · ' }}@endforeach</p><p class="mt-2 whitespace-pre-line text-xs">{{ $shipment['special_notes']??'' }}</p></div></div>@endif
<details><summary class="cursor-pointer text-sm font-medium">Optional commercial context</summary><dl class="mt-4 space-y-3">@foreach(['goods_value'=>['Declared goods value','goods_currency'],'budget'=>['Customer budget','budget_currency'],'reference_quote'=>['Existing freight reference quotation','reference_currency']] as $key=>[$label,$currency])<div><dt class="text-xs text-slate-500">{{ $label }}</dt><dd class="mt-1 text-sm">{{ $shipment[$key]??'Not provided' }} {{ $shipment[$currency]??'' }}</dd></div>@endforeach</dl><p class="mt-4 text-xs leading-6 text-slate-500">These values are separate from authoritative vendor cost and company selling price.</p></details></div>
