<x-layout title="Review AI request">
<a class="text-link mb-6 inline-flex items-center gap-2 text-xs" href="{{ route('inquiries.extraction',['inquiry'=>$inquiry,'view'=>'sources']) }}"><x-icon name="arrow-left" />Back to source selection</a>
<x-page-header title="Review the request scope" :eyebrow="$inquiry->reference" description="One request returns field proposals, evidence, conflicts and an unreviewed summary. Your shipment stays unchanged until staff review." />
<div class="grid items-start gap-6 xl:grid-cols-[1fr_360px]"><section class="panel panel-pad min-w-0"><h2 class="section-title">Selected evidence</h2><p class="mt-2 text-xs leading-6 text-slate-500">Only the text below, its source IDs/classifications/warnings and the extraction instructions are included. Files, images, internal notes and unrelated cases are excluded.</p>
<div class="mt-6 space-y-4">@foreach($sources as $source)<details class="rounded-2xl border border-slate-200 p-4"><summary class="cursor-pointer text-sm font-medium break-words">{{ $source['label'] }}</summary><p class="mt-3 text-xs text-slate-500">{{ $source['id'] }} · {{ $source['method'] }}</p><pre class="source-text mt-4">{{ $source['text'] }}</pre>@foreach($source['warnings'] as $warning)<p class="mt-3 text-xs leading-5 text-[#855600]">{{ $warning }}</p>@endforeach</details>@endforeach</div></section>
<aside class="space-y-6"><section class="panel panel-pad"><h2 class="section-title">Usage & limits</h2><dl class="mt-5 space-y-4 text-sm"><div><dt class="eyebrow">Runtime model</dt><dd class="mt-1 break-all">{{ $settings->model??'Not configured' }}</dd></div><div><dt class="eyebrow">Selected passages</dt><dd class="mt-1">{{ count($sources) }} · {{ collect($sources)->pluck('lineage.document_id')->filter()->unique()->count() }} documents</dd></div><div><dt class="eyebrow">Input size</dt><dd class="mt-1">{{ number_format(mb_strlen($input)) }} characters</dd><dd class="mt-1 text-xs leading-5 text-slate-500">{{ number_format($bound) }} conservative token bound including instructions/schema. Character counts are not exact tokens.</dd></div><div><dt class="eyebrow">Output limit</dt><dd class="mt-1">{{ number_format(config('ai.output_tokens')) }} tokens including reported reasoning</dd></div><div><dt class="eyebrow">Conservative cost reservation · USD</dt><dd class="mt-1 text-xl font-semibold">{{ $estimate===null?'Unknown':'$'.$estimate }}</dd><dd class="mt-1 text-xs text-slate-500">Configured rates: {{ $settings->configuration['rate_version']??'Unknown' }} · {{ $settings->configuration['rate_date']??'Unknown date' }}. An estimate, not a provider invoice.</dd></div></dl></section>
@if($reasons || $estimate===null || $bound>config('ai.input_tokens'))<section class="panel panel-pad"><h2 class="text-sm">Live request unavailable</h2><ul class="mt-3 list-disc space-y-2 pl-4 text-xs leading-6 text-[#855600]">@foreach($reasons as $reason)<li>{{ $reason }}</li>@endforeach @if($estimate===null)<li>A hard monetary reservation cannot yet be made.</li>@endif @if($bound>config('ai.input_tokens'))<li>Select fewer passages to meet the input bound.</li>@endif</ul><p class="mt-4 text-xs leading-6">Local extraction and manual shipment editing remain available.</p></section>
@else<form method="POST" action="{{ route('inquiries.ai.store',$inquiry) }}" class="panel panel-pad space-y-5">@csrf @foreach($sources as $source)<input type="hidden" name="sources[]" value="{{ $source['id'] }}">@endforeach<input type="hidden" name="shipment_hash" value="{{ $inquiry->snapshotHash() }}"><input type="hidden" name="scope_hash" value="{{ $scopeHash }}"><label class="flex items-start gap-3 text-xs leading-6"><input class="mt-1 h-4 w-4 accent-accent" type="checkbox" name="authorize_paid" value="1" required>I authorize this selected text and the displayed reservation for one paid provider request. Identical successful results are reused.</label><details><summary class="cursor-pointer text-xs text-accent">Explicitly retry a prior failed run</summary><label class="mt-4 flex gap-3 text-xs"><input type="checkbox" name="retry" value="1">Make another paid request after reconciliation</label><x-field name="reason" label="Retry reason" maxlength="1000" hint="A retry preserves prior runs and can incur another provider charge." /></details><x-button class="w-full">Request proposals</x-button><p class="text-xs leading-6 text-slate-500">Responses storage is disabled. Provider handling may still include retention; this is not a zero-retention guarantee.</p></form>@endif
</aside></div></x-layout>
