<x-layout title="Client clarification">
<x-page-header :title="'Clarification · '.$inquiry->reference" eyebrow="Approved client communication" description="Review and approve the exact message and recipient before manual communication or explicitly approved email release."><x-button variant="secondary" :href="route('inquiries.show',$inquiry)">Back to inquiry</x-button></x-page-header>
@php($current=$clarification->currentFor($inquiry))
@php($mailDispatch=$clarification->outlookDispatch())
@include('mail.release-status',['dispatch'=>$mailDispatch])
@if($clarification->approved_at)<a class="btn btn-secondary mb-6" href="{{ route('mail.preview',['clarification',$clarification->id]) }}">Email preview & dispatch history</a>@endif
<div class="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_320px]"><section class="panel panel-pad min-w-0"><div class="mb-6 flex flex-wrap items-center gap-3"><span class="badge {{ $clarification->status==='approved'?'badge-active':'badge-inactive' }}">{{ ucfirst($clarification->status) }}</span><span class="text-xs text-slate-500">Shipment revision {{ $clarification->shipment_revision }} · {{ $clarification->recipient_email }}</span></div>
@if(!$current)<div class="alert alert-warning mb-6">Shipment or recipient details have changed. This message is retained as evidence; prepare a fresh clarification for the working revision.</div>@endif
@if($clarification->status==='draft'&&$current&&$inquiry->status!=='closed')
<form method="post" action="{{ route('inquiries.clarifications.update',[$inquiry,$clarification]) }}" data-unsaved>@csrf @method('PATCH')<input type="hidden" name="lock_version" value="{{ old('lock_version',$clarification->lock_version) }}"><div class="space-y-6"><x-field name="client_contact_id" label="Exact recipient" type="select" required>@foreach($contacts as $contact)<option value="{{ $contact->id }}" @selected((string)old('client_contact_id',$clarification->client_contact_id)===(string)$contact->id)>{{ $contact->name }} · {{ $contact->email }}</option>@endforeach</x-field><x-field name="body" label="Exact message" type="textarea" rows="16" :value="$clarification->body" maxlength="12000" required hint="Deterministic template based on current gaps. Edit and save before approving." /><x-button>Save message draft</x-button></div></form>
@else
<label for="clarification-message" class="label">Exact {{ $clarification->status==='approved'||$clarification->status==='communicated'?'approved':'saved' }} message</label><textarea id="clarification-message" class="input leading-7" rows="16" readonly>{{ $clarification->body }}</textarea><p class="hint">To copy manually, focus this message and select its text. The original wording remains preserved.</p><button hidden type="button" data-copy-message="clarification-message" class="btn btn-secondary mt-4">Copy message</button><p data-copy-status class="hint" role="status" aria-live="polite"></p>
@endif</section><aside class="space-y-6"><section class="panel panel-pad"><h2 class="section-title">Review & approval</h2><p class="mt-3 text-xs leading-6 text-slate-500">Approval captures this exact message, recipient and shipment revision. It does not record communication.</p>
@if($clarification->approved_at)<p class="mt-4 text-sm">Approved {{ $clarification->approved_at->setTimezone($company->timezone)->format('d M Y, H:i') }}</p>@endif
@if($clarification->status==='draft'&&$current&&$inquiry->status!=='closed')<form class="mt-5" method="post" action="{{ route('inquiries.clarifications.approve',[$inquiry,$clarification]) }}" data-confirm-form="Approve the saved message and exact recipient for this shipment revision?">@csrf<input type="hidden" name="lock_version" value="{{ old('lock_version',$clarification->lock_version) }}"><x-button>Approve saved message</x-button></form>@endif
@if(!$current&& !in_array($inquiry->status,['closed','ready_for_sourcing'],true))<form class="mt-5" method="post" action="{{ route('inquiries.clarifications.store',$inquiry) }}">@csrf<input type="hidden" name="lock_version" value="{{ $inquiry->lock_version }}"><x-button>Prepare fresh clarification</x-button></form>@endif</section>
@if($clarification->status==='approved'&&$current&&$inquiry->status!=='closed'&&!$mailDispatch)
<section class="panel panel-pad"><h2 class="section-title">Record manual communication</h2><p class="mt-3 mb-5 text-xs leading-6 text-slate-500">Only complete this after staff communicated the approved message outside LRS. Copying or approval alone does not count.</p><form method="post" action="{{ route('inquiries.clarifications.communicated',[$inquiry,$clarification]) }}" class="space-y-5">@csrf<input type="hidden" name="lock_version" value="{{ old('lock_version',$clarification->lock_version) }}"><x-field name="recipient" label="Recipient communicated to" :value="$clarification->recipient_email" readonly required /><x-field name="channel" label="Actual channel" type="select">@foreach(array_diff_key(\App\Models\Inquiry::CHANNELS, ['website'=>true]) as $key=>$label)<option value="{{ $key }}" @selected(old('channel','email')===$key)>{{ $label }}</option>@endforeach</x-field><x-field name="occurred_at" label="Communication time" type="datetime-local" :value="\App\Support\InquiryWorkflow::local(now())" required /><label class="flex gap-3 text-xs leading-6"><input type="checkbox" name="confirmed_manual" value="1" required class="mt-1 h-4 w-4 shrink-0 accent-accent">I confirm staff manually communicated this exact message to this recipient outside LRS.</label>@error('confirmed_manual')<p class="field-error">{{ $message }}</p>@enderror<x-button>Record as manually communicated</x-button></form></section>
@elseif($clarification->status==='communicated')<section class="panel panel-pad"><h2 class="section-title">Communication recorded</h2><p class="mt-3 text-xs leading-6 text-slate-500">Recorded as performed outside LRS at {{ $clarification->communicated_at->setTimezone($company->timezone)->format('d M Y, H:i') }}. See the inquiry activity for staff, channel and exact wording.</p></section>@endif</aside></div></x-layout>