<x-layout title="Extraction & review">
<a class="text-link mb-6 inline-flex items-center gap-2 text-xs" href="{{ route('inquiries.show',$inquiry) }}"><x-icon name="arrow-left" />Inquiry workspace</a>
<x-page-header title="Evidence into clear decisions." :eyebrow="$inquiry->reference.' · Extraction & review'" description="Extract locally, compare source evidence and review proposed changes. You stay in control of the working shipment."><x-button variant="secondary" :href="route('inquiries.edit',$inquiry)"><x-icon name="pencil-simple" />Edit manually</x-button></x-page-header>
<nav class="mb-6 flex flex-wrap gap-2" aria-label="Inquiry sections">@foreach(['overview'=>'Overview','shipment'=>'Shipment','documents'=>'Documents','activity'=>'Activity'] as $section=>$label)<a class="workspace-tab" href="{{ route('inquiries.show',['inquiry'=>$inquiry,'section'=>$section]) }}">{{ $label }}</a>@endforeach<a class="workspace-tab active" aria-current="page" href="{{ route('inquiries.extraction',$inquiry) }}">Extraction & review</a></nav>
<ol class="review-steps mb-6" aria-label="Review sequence"><li><span>1</span>Extract sources</li><li><span>2</span>Request proposals</li><li><span>3</span>Review & apply</li><li><span>4</span>Confirm shipment</li></ol>
@if($liveReasons)<div class="alert alert-warning mb-6"><x-icon name="warning-circle" /><div><p class="font-medium">Live AI is unavailable</p><p class="mt-1 text-xs leading-6">Local extraction and manual entry are available. {{ implode(' ', $liveReasons) }}</p>@can('manage-company')<a class="text-link mt-2 inline-block text-xs" href="{{ route('settings.ai') }}">Open runtime & usage settings</a>@endcan</div></div>@endif
<details class="panel mb-6" @if(!$documentRuns->count() && !$run) open @endif><summary class="cursor-pointer p-6 text-sm font-semibold">Local document extraction <span class="ml-2 font-normal text-slate-500">{{ $documents->where('is_archived',false)->count() }} available originals</span></summary><div class="border-t border-slate-100 p-6">
@if($documents->where('is_archived',false)->isEmpty())<p class="text-sm leading-7">No supporting documents yet. You can use original inquiry text below or <a class="text-link" href="{{ route('inquiries.show',['inquiry'=>$inquiry,'section'=>'documents']) }}">upload private evidence</a>. Attachments are optional.</p>
@else<form method="POST" action="{{ route('inquiries.extraction.store',$inquiry) }}" class="space-y-5">@csrf<div class="grid gap-3 lg:grid-cols-2">@foreach($documents->where('is_archived',false) as $document)<label class="flex min-w-0 items-start gap-3 rounded-xl border border-slate-200 p-4"><input class="mt-1 h-4 w-4 shrink-0 accent-accent" type="checkbox" name="document_ids[]" value="{{ $document->id }}" @checked(in_array($document->id,old('document_ids',[])))><span class="min-w-0"><span class="block break-all text-sm font-medium">{{ $document->original_name }}</span><span class="mt-1 block text-xs text-slate-500">{{ \App\Models\InquiryDocument::CLASSES[$document->classification] }} · Private original · Unscanned</span></span></label>@endforeach</div><div class="grid gap-5 md:grid-cols-3"><x-field name="pages" label="PDF pages to process" placeholder="e.g. 1-3, 5" hint="Empty selects up to the first configured page limit; omitted pages are reported. Applies to each selected PDF." /><x-field name="ocr_pages" label="Force OCR on selected PDF pages" placeholder="e.g. 2" hint="Normally only pages without usable digital text use OCR. Empty uses automatic fallback." /><div class="rounded-xl bg-slate-50 p-4 text-xs leading-6">Local limits: {{ config('extraction.pages') }} pages, {{ number_format(config('extraction.pixels')) }} pixels, {{ number_format(config('extraction.text_chars')) }} text characters, {{ config('extraction.rows') }} rows and {{ config('extraction.cells') }} cells. Processing cannot change shipment fields.</div></div><details><summary class="cursor-pointer text-xs text-accent">Retry or reprocess an earlier local run</summary><label class="mt-4 flex gap-3 text-xs"><input type="checkbox" name="reprocess" value="1" @checked(old('reprocess'))>Create a new local attempt and preserve previous evidence</label><div class="mt-4"><x-field name="reason" label="Reprocess reason" maxlength="1000" hint="Local extraction has no provider/API charge. Unchanged successful runs are reused by default." /></div></details><x-button>Extract selected sources</x-button></form>@endif</div></details>
@if($documentRuns->count())<details class="panel mb-6"><summary class="cursor-pointer p-6 text-sm font-semibold">Extraction history <span class="ml-2 font-normal text-slate-500">{{ $documentRuns->count() }} runs</span></summary><div class="space-y-4 border-t border-slate-100 p-6">@foreach($documentRuns as $documentRun)<article class="rounded-xl border border-slate-200 p-4"><div class="flex flex-wrap items-start justify-between gap-3"><div class="min-w-0"><h3 class="break-all text-sm">{{ $documentRun->document->original_name }}</h3><p class="mt-1 text-xs text-slate-500">Local run {{ $documentRun->id }} · Attempt {{ $documentRun->generation }} · {{ \App\Support\Processing::time($documentRun->created_at) }}</p></div><span class="badge {{ in_array($documentRun->state,['failed','unavailable','partial','manual_review'])?'badge-warning':'tint-blue' }}">{{ $documentRun->label() }}</span></div><p class="mt-3 text-xs text-slate-500">{{ count($documentRun->blocks) }} readable passages · {{ $documentRun->total_pages??'Unknown' }} total pages · {{ $documentRun->attempts }} worker attempts</p>@if($documentRun->error_message)<p class="mt-3 text-xs leading-6 text-red-700">{{ $documentRun->error_message }}</p>@endif @if($documentRun->warnings)<details class="mt-3"><summary class="cursor-pointer text-xs text-[#855600]">Quality and processing warnings ({{ count($documentRun->warnings) }})</summary><ul class="mt-2 list-disc space-y-1 pl-4 text-xs leading-6">@foreach($documentRun->warnings as $warning)<li>{{ $warning }}</li>@endforeach</ul></details>@endif @if(in_array($documentRun->state,['queued','processing']))<p class="mt-3 text-xs leading-6">Waiting for the extraction queue worker. Refresh this page for progress; completed passages are retained.</p>@endif</article>@endforeach</div></details>@endif
<div class="mb-6 flex flex-wrap items-center justify-between gap-3"><div class="flex flex-wrap gap-2"><a class="workspace-tab {{ !$run?'active':'' }}" href="{{ route('inquiries.extraction',['inquiry'=>$inquiry,'view'=>'sources']) }}">Choose sources</a>@foreach($runs->take(6) as $history)<a class="workspace-tab {{ $run?->id===$history->id?'active':'' }}" href="{{ route('inquiries.extraction',['inquiry'=>$inquiry,'run'=>$history->id]) }}">Run {{ $history->id }}{{ $history->is_demo?' · Demo':'' }}</a>@endforeach</div><a class="text-link text-xs" href="{{ request()->fullUrl() }}">Refresh progress</a></div>
@if($run)
<section class="panel panel-pad mb-6"><div class="flex flex-wrap items-start justify-between gap-4"><div><h2 class="section-title">Proposal run {{ $run->id }}</h2><p class="mt-2 text-xs text-slate-500">{{ $run->is_demo?'Synthetic fixture · no provider request':'OpenAI Responses request' }} · {{ $run->model }} · {{ \App\Support\Processing::time($run->created_at) }}</p></div><div class="flex flex-wrap gap-2"><span class="badge tint-blue">{{ $run->label() }}</span><span class="badge badge-inactive">{{ ucfirst(str_replace('_',' ',$run->review_outcome)) }}</span>@if($run->stale())<span class="badge badge-warning">Stale · compare with current shipment</span>@endif</div></div>
@if($run->is_demo)<p class="mt-4 rounded-xl bg-[#EDF4FF] p-4 text-xs leading-6">These proposals are deterministic synthetic test data. Local extraction is real; no live AI accuracy or provider usage is claimed.</p>@endif
@if($run->error_message)<p class="mt-4 rounded-xl bg-red-50 p-4 text-xs leading-6 text-red-700">{{ $run->error_message }}</p>@endif
<dl class="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4 text-xs"><div><dt class="eyebrow">Selected input</dt><dd class="mt-2">{{ count($run->sources) }} passages · {{ number_format($run->input_characters) }} characters</dd></div><div><dt class="eyebrow">Reported usage</dt><dd class="mt-2">{{ $run->usage===null?'Unknown':(isset($run->usage['input_tokens'])?number_format($run->usage['input_tokens']):'Unknown').' input / '.(isset($run->usage['output_tokens'])?number_format($run->usage['output_tokens']):'Unknown').' output tokens' }}</dd>@if($run->usage)<dd class="mt-1 text-slate-500">Cached: {{ $run->usage['input_tokens_details']['cached_tokens']??'Unknown' }} · Reasoning: {{ $run->usage['output_tokens_details']['reasoning_tokens']??'Unknown' }}</dd>@endif</div><div><dt class="eyebrow">Calculated cost · USD</dt><dd class="mt-2">{{ $run->estimated_cost===null?'Unknown':'$'.$run->estimated_cost }}{{ $run->cost_uncertain?' · Uncertain':'' }}</dd><dd class="mt-1 text-slate-500">Estimate from captured dated rates, not an invoice.</dd></div><div><dt class="eyebrow">Provider attempt / reservation</dt><dd class="mt-2">{{ $run->attempts }} attempts · {{ $run->reservation>0?'$'.$run->reservation.' held':'No reservation held' }}</dd><dd class="mt-1 break-all text-slate-500">{{ $run->provider_request_id??'No reported provider request ID' }}</dd></div></dl>
@if($run->stale())<p class="mt-4 text-xs leading-6 text-[#855600]">The source or working shipment differs from this run. Its draft summary is stale. Applying these proposals is blocked; compare evidence with the current shipment and select a fresh snapshot.</p>@endif
@if($run->reviews->count())<details class="mt-5"><summary class="cursor-pointer text-xs text-accent">Recorded staff reviews</summary>@foreach($run->reviews as $record)<div class="mt-3 rounded-xl bg-slate-50 p-4 text-xs"><p>Review {{ $record->id }} · Staff {{ $record->reviewer_id }} · Revision {{ $record->resulting_revision }} · {{ \App\Support\Processing::time($record->reviewed_at) }}</p>@foreach($record->decisions as $decision)<p class="mt-2">{{ ucfirst(str_replace('_',' ',$decision['field'])) }}: {{ $decision['action'] }}{{ $decision['reason']?' — '.$decision['reason']:'' }}</p>@endforeach</div>@endforeach</details>@endif
</section>@endif
<div class="review-switch mb-4 flex gap-2" aria-label="Review panels"><a class="workspace-tab" href="#source-panel" data-review-switch="source">Source evidence</a><a class="workspace-tab" href="#proposal-panel" data-review-switch="proposals">{{ $run?'Proposals':'Source selection' }}</a></div>
<div class="review-workspace grid items-start gap-6 xl:grid-cols-[minmax(0,0.9fr)_minmax(0,1.1fr)]" data-review-workspace>
<section class="panel min-w-0 xl:sticky xl:top-6" id="source-panel" data-review-pane="source"><div class="border-b border-slate-100 p-6"><h2 class="section-title">Source evidence</h2>@if($catalogue)<form method="GET" action="{{ route('inquiries.extraction',$inquiry) }}#source-panel" class="mt-4 space-y-3">@if($run)<input type="hidden" name="run" value="{{ $run->id }}">@else<input type="hidden" name="view" value="sources">@endif<x-field name="source" label="Page, sheet or passage" type="select">@foreach($catalogue as $block)<option value="{{ $block['id'] }}" @selected($source && $source['id']===$block['id'])>{{ $block['label'] }}</option>@endforeach</x-field><x-button variant="secondary">Open passage</x-button></form>@endif</div>
@if($source)<div class="p-6"><p class="break-words text-sm font-medium">{{ $source['label'] }}</p><p class="mt-2 break-all text-xs text-slate-500">{{ $source['id'] }} · {{ $source['method'] }}</p>@if(($source['lineage']['kind']??null)==='document')<a class="text-link mt-3 inline-block text-xs" href="{{ route('inquiries.documents.show',[$inquiry,$source['lineage']['document_id']]) }}">Open private original</a>@if($pageAvailable)<details class="mt-4"><summary class="cursor-pointer text-xs text-accent">Rendered page {{ $source['metadata']['page'] }}</summary><img class="mt-3 w-full rounded-xl border border-slate-200" loading="lazy" src="{{ route('inquiries.extraction.page',[$inquiry,$source['lineage']['run_id'],$source['metadata']['page']]) }}" alt="Private rendered source page {{ $source['metadata']['page'] }}; read extracted text below for accessible content."></details>@endif @endif
@if($quote??null)<div class="mt-4 rounded-xl bg-[#FFF4DF] p-4"><p class="eyebrow">Supporting quotation</p><p class="mt-2 whitespace-pre-line break-words text-xs leading-6">{{ $quote }}</p><p class="mt-2 text-xs text-slate-500">Exact passage text; no precise image bounding-box claim.</p></div>@endif
<div class="source-text mt-5" tabindex="0" role="region" aria-label="Extracted passage text">@if(($quote??null) && str_contains($source['text'],$quote))
@php
$parts=explode($quote,$source['text'],2);
@endphp
{{ $parts[0] }}<mark>{{ $quote }}</mark>{{ $parts[1] }}@else{{ $source['text'] }}@endif</div>
@if(isset($source['metadata']['cells']) && !is_array($source['metadata']['cells'][0]??null))<details class="mt-4"><summary class="cursor-pointer text-xs text-accent">Word table cells</summary><dl class="mt-3 space-y-3 text-xs">@foreach($source['metadata']['cells'] as $cell)<div class="rounded-xl bg-slate-50 p-3"><dt class="font-medium">Column {{ $loop->iteration }}</dt><dd class="mt-2 break-words">{{ $cell }}</dd></div>@endforeach</dl><p class="hint">Column order is preserved; inspect headings and merged cells in the original.</p></details>@endif
@if(isset($source['metadata']['cells']) && is_array($source['metadata']['cells'][0]??null))<details class="mt-4"><summary class="cursor-pointer text-xs text-accent">Cell metadata and raw values</summary><div class="table-scroll mt-3" tabindex="0"><table><caption class="sr-only">Extracted cell provenance</caption><thead><tr><th>Cell</th><th>Raw text</th><th>Formula/cache/format</th></tr></thead><tbody>@foreach($source['metadata']['cells'] as $cell)@if(is_array($cell))<tr><td>{{ $cell['cell']??'Unknown' }}</td><td>{{ $cell['raw']??'' }}</td><td>{{ !empty($cell['formula'])?'Formula · cached '.($cell['cached']??'absent'):(!empty($cell['formula_like'])?'Formula-like text':'Literal') }} · {{ $cell['number_format']??'No format metadata' }}</td></tr>@else<tr><td>Column {{ $loop->iteration }}</td><td>{{ $cell }}</td><td>Word table text · check headings in original</td></tr>@endif @endforeach</tbody></table></div></details>@endif
@if($source['warnings'])<ul class="mt-4 list-disc space-y-2 pl-4 text-xs leading-6 text-[#855600]">@foreach($source['warnings'] as $warning)<li>{{ $warning }}</li>@endforeach</ul>@endif</div>@else<x-empty title="No extracted passages yet" description="Queue a local document run or capture original inquiry text. Manual shipment entry stays available." icon="file-text" />@endif</section>
<section class="min-w-0 space-y-6" id="proposal-panel" data-review-pane="proposals">
@if(!$run)
<form method="POST" action="{{ route('inquiries.ai.scope',$inquiry) }}" class="panel panel-pad space-y-5">@csrf<h2 class="section-title">Choose text for proposals</h2><p class="text-xs leading-6 text-slate-500">Select deliberate passages/pages. The next screen previews the exact text, model and cost before any paid request. Nothing is sent from this screen.</p>@forelse($catalogue as $block)<label class="flex min-w-0 items-start gap-3 rounded-xl border border-slate-200 p-4"><input class="mt-1 h-4 w-4 shrink-0 accent-accent" type="checkbox" name="sources[]" value="{{ $block['id'] }}" @checked(in_array($block['id'],old('sources',[])))><span class="min-w-0"><span class="block break-words text-sm font-medium">{{ $block['label'] }}</span><span class="mt-2 block text-xs leading-6 text-slate-500">{{ \Illuminate\Support\Str::limit($block['text'],180) }}</span></span></label>@empty<p class="text-sm leading-6">Extract a source or enter the preserved original request first.</p>@endforelse @if($catalogue)<x-button class="w-full">Preview request scope</x-button>@endif</form>
@elseif($run->state==='needs_review')
<section class="panel panel-pad"><h2 class="section-title">Unreviewed draft summary{{ $run->stale()?' · Stale':'' }}</h2><p class="mt-4 whitespace-pre-line break-words text-sm leading-7">{{ $run->result['summary'] }}</p>@foreach(['conflicts'=>'Conflicts to compare','missing'=>'Missing or uncertain','identity_flags'=>'Identity review flags'] as $key=>$label)@if($run->result[$key])<h3 class="mt-5 text-sm">{{ $label }}</h3><ul class="mt-2 list-disc space-y-2 pl-4 text-xs leading-6 text-[#855600]">@foreach($run->result[$key] as $item)<li>{{ $item }}</li>@endforeach</ul>@endif @endforeach</section>
<form method="POST" action="{{ route('inquiries.ai.preview',[$inquiry,$run]) }}" data-proposal-review class="space-y-5">@csrf<input type="hidden" name="lock_version" value="{{ old('lock_version',$inquiry->lock_version) }}"><div class="flex flex-wrap items-center justify-between gap-3"><h2 class="section-title">Review field proposals</h2><button type="button" data-select-supported class="text-link text-xs" @disabled($run->stale())>Select supported empty fields</button></div>
@forelse($run->proposals as $candidate)
@php
$id=$candidate['id']; $current=$inquiry->shipment[$candidate['field']]??null; $populated=$current!==null && $current!=='' && $current!==[] && $current!=='unknown';
@endphp

<article class="panel panel-pad" data-candidate data-supported="{{ $candidate['supported'] && !$candidate['ambiguous'] && !$candidate['conflict'] && !$populated?'1':'0' }}"><div class="flex flex-wrap items-start justify-between gap-3"><h3 class="text-base">{{ ucfirst(str_replace('_',' ',$candidate['field'])) }}</h3><span class="badge {{ $candidate['label']==='Supported by source'?'tint-green':'badge-warning' }}">{{ $candidate['label'] }}</span></div><div class="mt-4 grid gap-3 sm:grid-cols-2"><div class="rounded-xl bg-slate-50 p-4"><p class="eyebrow">Current working value</p><p class="mt-2 whitespace-pre-line break-words text-sm leading-6">{{ \App\Support\ProposalEvidence::display($current) }}</p></div><div class="rounded-xl bg-[#EDF4FF] p-4"><p class="eyebrow">Proposed</p><p class="mt-2 whitespace-pre-line break-words text-sm leading-6">{{ \App\Support\ProposalEvidence::display($candidate['value']) }}</p></div></div><p class="mt-3 whitespace-pre-line break-words text-xs leading-6 text-slate-500">Raw source value: {{ $candidate['raw_value']?:'Unknown' }}</p>
@foreach($candidate['evidence'] as $evidence)
@php
$selectedSource=collect($catalogue)->firstWhere('id',$evidence['source_id']); $verifiedLink=$selectedSource && $selectedSource['locator']===$evidence['locator'] && str_contains(\App\Support\ProposalEvidence::text($selectedSource['text']),\App\Support\ProposalEvidence::text($evidence['quote']));
@endphp
 @if($verifiedLink)<a class="mt-3 block rounded-xl border border-slate-200 p-4 hover:bg-slate-50" href="{{ route('inquiries.extraction',['inquiry'=>$inquiry,'run'=>$run->id,'source'=>$evidence['source_id'],'evidence'=>$candidate['id'].':'.$loop->index]) }}#source-panel"><p class="text-link text-xs">{{ $evidence['locator'] }} · Open evidence</p><p class="mt-2 whitespace-pre-line break-words text-xs leading-6">{{ $evidence['quote'] }}</p></a>@else<div class="mt-3 rounded-xl bg-slate-50 p-4"><p class="text-xs font-medium text-[#855600]">Unverifiable evidence · {{ $evidence['locator'] }}</p><p class="mt-2 break-words text-xs leading-6">{{ $evidence['quote'] }}</p></div>@endif @endforeach
@if($candidate['warnings'])<details class="mt-4"><summary class="cursor-pointer text-xs text-[#855600]">Warnings & conflicts ({{ count($candidate['warnings']) }})</summary><ul class="mt-2 list-disc space-y-1 pl-4 text-xs leading-6">@foreach($candidate['warnings'] as $warning)<li>{{ $warning }}</li>@endforeach</ul></details>@endif
<div class="mt-5 border-t border-slate-100 pt-5 space-y-4"><x-field :name="'decisions['.$id.'][action]'" label="Your decision" type="select" data-proposal-action><option value="unresolved" @selected(old('decisions.'.$id.'.action','unresolved')==='unresolved')>Leave unresolved</option><option value="accept" @selected(old('decisions.'.$id.'.action')==='accept') @disabled(!$candidate['supported'] || $candidate['ambiguous'])>Accept supported value</option><option value="correct" @selected(old('decisions.'.$id.'.action')==='correct')>Correct and accept manually</option><option value="reject" @selected(old('decisions.'.$id.'.action')==='reject')>Reject this proposal</option></x-field>
<details data-correction @if(old('decisions.'.$id.'.action')==='correct') open @endif><summary class="cursor-pointer text-xs text-accent">Manual correction inputs</summary><div class="mt-4"><x-proposal-editor :candidate="$candidate" /></div></details>
<x-field :name="'decisions['.$id.'][reason]'" label="Review explanation" type="textarea" maxlength="2000" hint="Required for corrections or conflicting critical values. A manual correction never becomes source-verified AI evidence." />
@if($populated || $candidate['conflict'])<label class="flex items-start gap-3 text-xs leading-6"><input class="mt-1 h-4 w-4 accent-accent" type="checkbox" name="decisions[{{ $id }}][acknowledge]" value="1" @checked(old('decisions.'.$id.'.acknowledge'))>I compared the current value and evidence and explicitly authorize this replacement/conflict decision.</label>@error('decisions.'.$id.'.acknowledge')<p class="field-error">{{ $message }}</p>@enderror @endif</div></article>
@empty<section class="panel panel-pad"><p class="text-sm">No field proposals were returned. Use the missing-information notes and manual editor.</p></section>@endforelse
<div class="panel panel-pad"><x-button class="w-full" :disabled="$run->stale()">Preview selected changes</x-button><p class="mt-3 text-xs leading-6 text-slate-500">Nothing is accepted by default. The next screen shows all changes before applying them. Readiness, identity and outgoing actions remain human-controlled.</p></div></form>
@else<section class="panel panel-pad"><h2 class="section-title">{{ $run->label() }}</h2><p class="mt-4 text-sm leading-7">{{ in_array($run->state,['queued','processing'])?'The database worker is preparing this request. Refresh for progress.':'No applicable proposals are available from this run. Local evidence and manual entry remain available.' }}</p><a class="text-link mt-4 inline-block text-xs" href="{{ route('inquiries.extraction',['inquiry'=>$inquiry,'view'=>'sources']) }}">Review a fresh source selection</a></section>@endif
</section></div></x-layout>
