<x-layout title="Inquiries"><x-page-header title="Your inquiry workspace" eyebrow="From request to review" description="Capture the customer’s requirements, resolve the gaps, and confirm a shipment your team can source."><x-button :href="route('inquiries.create')"><x-icon name="plus" />New inquiry</x-button></x-page-header>
<details class="mb-5"><summary class="text-xs font-medium">Customer request form & sharing link</summary><div class="mt-4">@include('inquiries.public-link')</div></details>
<div class="mb-6 flex flex-wrap gap-2"><a class="workspace-tab {{ ($filters['data']??'real')==='samples'?'active':'' }}" href="{{ route('inquiries.index',['data'=>'samples']) }}">Fictional examples</a><a class="workspace-tab {{ ($filters['data']??'real')==='real'?'active':'' }}" href="{{ route('inquiries.index',['data'=>'real']) }}">Real requests</a></div>
<div class="mb-7 grid gap-4 sm:grid-cols-3">@foreach([[$review,'Need review','Review the current shipment','needs_review','tint-blue'],[$waiting,'Waiting for client information','Follow approved clarification and customer replies','needs_client_information','tint-amber'],[$overdue,'Overdue responses','Open inquiries past their response deadline',null,'tint-amber']] as [$count,$label,$hint,$status,$tint])<a href="{{ route('inquiries.index',array_merge(['data'=>$filters['data']],$status?['status'=>$status]:['overdue'=>1])) }}" class="panel metric-card"><div><p class="text-xs text-slate-500">{{ $label }}</p><p class="mt-2 text-[36px] font-semibold leading-none tabular-nums">{{ $count }}</p><p class="mt-3 max-w-xs text-xs text-slate-500">{{ $hint }}</p></div><span class="metric-icon {{ $tint }}"><x-icon name="clock" /></span></a>@endforeach</div>
<form method="GET" class="panel mb-6 p-5">
<div class="flex flex-wrap items-end gap-3"><div class="min-w-0 flex-1"><x-field name="q" label="Find an inquiry" :value="$filters['q']??''" placeholder="Shipment reference, customer or title" /></div><x-button variant="secondary">Search</x-button></div>
<details class="mt-4" @if(collect($filters)->except(['q','data'])->filter()->isNotEmpty()) open @endif><summary class="text-xs font-medium">More filters & data options</summary><div class="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
<x-field name="status" type="select" label="Shipment review status"><option value="">All statuses</option>@foreach(\App\Models\Inquiry::STATUSES as $key=>$label)<option value="{{ $key }}" @selected(($filters['status']??'')===$key)>{{ $label }}</option>@endforeach</x-field>
<x-field name="owner" type="select" label="Staff handling the request"><option value="">All staff</option>@foreach($owners as $owner)<option value="{{ $owner->id }}" @selected(($filters['owner']??'')==$owner->id)>{{ $owner->name }}{{ $owner->is_active?'':' (inactive)' }}</option>@endforeach</x-field>
<x-field name="priority" type="select" label="Priority"><option value="">All priorities</option>@foreach(['normal','urgent'] as $priority)<option @selected(($filters['priority']??'')===$priority)>{{ $priority }}</option>@endforeach</x-field>
<x-field name="client" type="select" label="Customer"><option value="">All customers</option>@foreach($clients as $client)<option value="{{ $client->id }}" @selected(($filters['client']??'')==$client->id)>{{ $client->company_name }}</option>@endforeach</x-field>
<x-field name="data" label="Records to show" type="select"><option value="real" @selected(($filters['data']??'real')==='real')>Real requests</option><option value="samples" @selected(($filters['data']??'real')==='samples')>Fictional examples</option><option value="fixtures" @selected(($filters['data']??'real')==='fixtures')>Labelled test fixtures</option><option value="all" @selected(($filters['data']??'real')==='all')>All labelled records</option></x-field>
<x-field name="source" type="select" label="Request source"><option value="">All sources</option>@foreach(\App\Models\Inquiry::CHANNELS as $key=>$label)<option value="{{ $key }}" @selected(($filters['source']??'')===$key)>{{ $label }}</option>@endforeach</x-field>
</div><div class="mt-5 flex flex-wrap items-center gap-4"><label class="flex items-center gap-2 text-xs"><input type="checkbox" name="overdue" value="1" @checked($filters['overdue']??false) class="h-4 w-4 accent-accent">Overdue only</label><label class="flex items-center gap-2 text-xs"><input type="checkbox" name="unassigned" value="1" @checked($filters['unassigned']??false) class="h-4 w-4 accent-accent">Unassigned only</label><x-button variant="secondary" class="btn-small">Apply filters</x-button><a class="text-link text-xs" href="{{ route('inquiries.index') }}">Clear filters</a></div></details></form>

<p class="mb-4 text-xs text-slate-500">Showing {{ ($filters['data']??'real')==='samples'?'fictional business-preview':(($filters['data']??'real')==='fixtures'?'synthetic fixture':(($filters['data']??'real')==='all'?'all labelled':'real')) }} inquiry records. The counts above use this data selection.</p>
@if($inquiries->isEmpty())<div class="panel"><x-empty :title="$total?'No inquiries match':'Start with a customer request'" :description="$total?'Try another reference or clear your filters.':'Add a customer, then record the shipment details you know.'"><x-button :href="route($total?'inquiries.index':'inquiries.create')">{{ $total?'Clear filters':'Create your first inquiry' }}</x-button></x-empty></div>
@else<p class="mb-4 text-xs text-slate-500">{{ $inquiries->total() }} inquiries · open one to see its next step</p>
<div class="grid gap-4 lg:grid-cols-2">@foreach($inquiries as $inquiry)<article class="panel panel-pad">
<div class="flex flex-wrap items-center justify-between gap-2"><p class="eyebrow">{{ $inquiry->reference }}</p>@if($inquiry->is_demo)<span class="badge tint-blue">Fictional example</span>@endif</div>
<h2 class="mt-3 text-lg"><a class="hover:text-accent" href="{{ route('inquiries.show',$inquiry) }}">{{ $inquiry->title }}</a></h2>
<p class="mt-2 text-sm text-slate-500">{{ $inquiry->client?->company_name ?? ($inquiry->public_contact['company'] ?? 'Customer needs review') }}</p>
<p class="mt-5 text-sm leading-6">{{ $inquiry->shipment['origin_location']??'Origin unknown' }} → {{ $inquiry->shipment['destination_location']??'Destination unknown' }}</p>
<div class="mt-3 flex flex-wrap items-center gap-2"><x-inquiry-status :status="$inquiry->status" /><span class="text-xs text-slate-500">Shipment review</span>@if($inquiry->priority==='urgent')<span class="badge badge-warning">Urgent</span>@endif</div>
<dl class="mt-5 grid grid-cols-2 gap-3 border-t border-slate-100 pt-4 text-xs"><div><dt class="text-slate-500">Handled by</dt><dd class="mt-1">{{ $inquiry->owner?->name??'Unassigned' }}{{ $inquiry->owner && !$inquiry->owner->is_active?' · inactive':'' }}</dd></div><div><dt class="text-slate-500">Reply due</dt><dd class="mt-1 {{ $inquiry->status!=='closed' && $inquiry->response_due_at?->isPast()?'text-red-700':'' }}">{{ $inquiry->response_due_at?->setTimezone($company->timezone)->format('d M, H:i')??'Not set' }}</dd></div></dl>
<div class="mt-5 flex flex-wrap items-center justify-between gap-3"><a class="text-link text-xs" href="{{ route('inquiries.show',['inquiry'=>$inquiry,'section'=>'documents']) }}">{{ $inquiry->documents_count }} files</a><a class="btn btn-secondary btn-small" href="{{ route('inquiries.show',$inquiry) }}">Open inquiry<x-icon name="arrow-right" /></a></div>
</article>@endforeach</div><x-pagination :records="$inquiries" />@endif</x-layout>
