<x-layout :title="$vendor->exists ? 'Edit vendor' : 'Add vendor'">
<a href="{{ $vendor->exists ? route('vendors.show',$vendor) : route('vendors.index') }}" class="text-link mb-6 inline-flex items-center gap-2 text-xs"><x-icon name="arrow-left" class="!h-4 !w-4" />{{ $vendor->exists ? 'Back to vendor' : 'Back to directory' }}</a>
<x-page-header :title="$vendor->exists ? 'Edit vendor' : 'Add a vendor'" eyebrow="Company directory" description="Capture the essentials. Keep capabilities and quotation contacts clear for your team." />
<form method="POST" action="{{ $vendor->exists ? route('vendors.update',$vendor) : route('vendors.store') }}" class="grid items-start gap-6 xl:grid-cols-[1fr_280px]">@csrf @if($vendor->exists) @method('PATCH') @endif
<div class="space-y-6">
<section class="panel panel-pad"><h2 class="section-title">01 · Company details</h2><p class="mb-6 text-xs text-slate-500">Required fields are marked with an asterisk.</p><div class="grid gap-5 sm:grid-cols-2">
<x-field name="company_name" label="Company name" :value="$vendor->company_name" required maxlength="255" autocomplete="organization" placeholder="e.g. Straits Forwarding Sdn. Bhd." />
<x-field name="display_name" label="Short / display name" :value="$vendor->display_name" maxlength="255" hint="Optional name your team commonly uses." />
<x-field name="type" label="Vendor type" type="select" required><option value="">Select a vendor type</option>@foreach(\App\Models\Vendor::TYPES as $value => $label)<option value="{{ $value }}" @selected(old('type',$vendor->type) === $value)>{{ $label }}</option>@endforeach</x-field>
<x-field name="communication_channel" label="Preferred communication" type="select" required>@foreach(\App\Models\Vendor::CHANNELS as $value => $label)<option value="{{ $value }}" @selected(old('communication_channel',$vendor->communication_channel) === $value)>{{ $label }}</option>@endforeach</x-field>
</div></section>
<section class="panel panel-pad"><h2 class="section-title">02 · Services & coverage</h2><p class="mb-6 text-xs text-slate-500">Record what this vendor can support. Services are never assumed.</p>
<fieldset><legend class="label">Services offered</legend><div class="mb-5 flex flex-wrap gap-3">@foreach(\App\Models\Vendor::SERVICES as $service)<label class="flex cursor-pointer items-center gap-2 rounded-lg border border-slate-200 px-4 py-3 text-xs"><input type="checkbox" name="services[]" value="{{ $service }}" @checked(in_array($service,old('services',$vendor->services ?? []))) class="h-4 w-4 accent-accent">{{ $service }}</label>@endforeach</div>@error('services')<p class="field-error">{{ $message }}</p>@enderror @error('services.*')<p class="field-error">{{ $message }}</p>@enderror</fieldset>
<div class="space-y-5"><x-field name="coverage" type="textarea" label="Coverage & routes" :value="$vendor->coverage" maxlength="4000" placeholder="Port Klang → Singapore; Malaysia pickup & delivery" hint="Use one route or coverage area per line. Keep direction and service scope explicit." /><x-field name="minimum_notes" type="textarea" label="Minimum shipment / charge notes" :value="$vendor->minimum_notes" maxlength="4000" placeholder="e.g. LCL minimum volume, charge minimums or restrictions" hint="Reference notes only. A blank field means unknown." /></div>
</section>
@if(! $vendor->exists)<section class="panel panel-pad"><div class="flex items-start justify-between gap-3"><h2 class="section-title">03 · First quotation contact</h2><span class="service-tag">Optional</span></div><p class="mt-2 mb-6 text-xs leading-6 text-slate-500">If provided, this person becomes the primary quotation contact. You can add more contacts after saving.</p><div class="grid gap-5 sm:grid-cols-2"><x-field name="contact_name" label="Contact name" maxlength="255" autocomplete="name" /><x-field name="contact_email" label="Contact email" type="email" maxlength="255" autocomplete="email" /><x-field name="contact_role" label="Role / job title" maxlength="255" /><x-field name="contact_phone" label="Phone" type="tel" maxlength="64" autocomplete="tel" /></div></section>@endif
<section class="panel panel-pad"><h2 class="section-title">{{ $vendor->exists ? '03' : '04' }} · Internal context</h2><p class="mt-2 mb-5 text-xs text-slate-500">For your staff only. Keep operational context useful and factual.</p><x-field name="internal_notes" type="textarea" label="Internal notes" :value="$vendor->internal_notes" maxlength="8000" rows="4" /></section>
<div class="flex flex-wrap justify-end gap-3"><x-button :href="$vendor->exists ? route('vendors.show',$vendor) : route('vendors.index')" variant="secondary">Cancel</x-button><x-button>{{ $vendor->exists ? 'Save changes' : 'Create vendor' }}<x-icon name="check" class="!h-4 !w-4" /></x-button></div>
</div>
<aside class="panel panel-pad"><span class="mb-4 inline-flex rounded-lg bg-[#edf4ff] p-3 text-accent"><x-icon name="buildings" /></span><h2 class="text-sm">Build a useful record</h2><ul class="mt-4 space-y-4 text-xs leading-6 text-slate-500"><li>Use the company’s full name. A matching name may be a legitimate branch.</li><li>A vendor can be saved before its contact details are complete.</li><li>Assign a primary quotation contact to prepare for future outreach.</li><li>Email validation checks syntax, not ownership or deliverability.</li></ul></aside>
</form></x-layout>
