<x-layout title="Vendor directory">
<x-page-header title="Vendor directory" eyebrow="Your partner network" description="A shared source of truth for the people who move your cargo."><x-button :href="route('vendors.create')"><x-icon name="plus" />Add vendor</x-button></x-page-header>
<div class="mb-7 grid gap-4 sm:grid-cols-3">
@foreach([[$total,'Total vendors','In your company directory',route('vendors.index'),'buildings'],[$active,'Active vendors','Available to your team',route('vendors.index',['status' => 'active']),'check-circle'],[$missing,'Need a quotation contact','Complete these vendor records',route('vendors.index',['contact' => 'missing']),'warning-circle']] as [$count,$label,$hint,$url,$icon])
<a class="panel metric-card" href="{{ $url }}"><div><p class="text-xs text-slate-500">{{ $label }}</p><p class="mt-2 text-[36px] font-semibold leading-none tracking-tight tabular-nums">{{ $count }}</p><p class="mt-3 text-xs text-slate-500">{{ $hint }}</p></div><span class="metric-icon {{ $icon === 'warning-circle' ? 'tint-amber' : ($icon === 'check-circle' ? 'tint-green' : 'tint-blue') }}"><x-icon :name="$icon" /></span></a>
@endforeach</div>
<form method="GET" action="{{ route('vendors.index') }}" class="panel mb-5 p-5">
<div class="grid items-end gap-4 sm:grid-cols-2 xl:grid-cols-6">
<div class="xl:col-span-2"><x-field name="q" label="Search directory" :value="$filters['q'] ?? ''" placeholder="Company, contact, email or route" /></div>
<x-field name="type" type="select" label="Vendor type"><option value="">All types</option>@foreach(\App\Models\Vendor::TYPES as $value => $label)<option value="{{ $value }}" @selected(($filters['type'] ?? '') === $value)>{{ $label }}</option>@endforeach</x-field>
<x-field name="service" type="select" label="Service"><option value="">All services</option>@foreach(\App\Models\Vendor::SERVICES as $service)<option @selected(($filters['service'] ?? '') === $service)>{{ $service }}</option>@endforeach</x-field>
<x-field name="status" type="select" label="Status"><option value="">All statuses</option><option value="active" @selected(($filters['status'] ?? '') === 'active')>Active</option><option value="inactive" @selected(($filters['status'] ?? '') === 'inactive')>Inactive</option></x-field>
<x-field name="contact" type="select" label="Quotation contact"><option value="">All records</option><option value="ready" @selected(($filters['contact'] ?? '') === 'ready')>Contact assigned</option><option value="missing" @selected(($filters['contact'] ?? '') === 'missing')>Missing contact</option></x-field>
</div><div class="mt-4 flex items-center gap-4"><x-button variant="secondary" class="btn-small"><x-icon name="magnifying-glass" class="!h-4 !w-4" />Search & filter</x-button>@if(collect($filters)->filter()->isNotEmpty())<a class="text-link text-xs" href="{{ route('vendors.index') }}">Clear filters</a>@endif</div>
</form>
<div class="mb-3 flex flex-wrap items-center justify-between gap-2"><p class="text-xs font-semibold">{{ $vendors->total() }} {{ $vendors->total() === 1 ? 'vendor' : 'vendors' }}{{ collect($filters)->filter()->isNotEmpty() ? ' matching your filters' : ' in your directory' }}</p><p class="text-[11px] text-slate-500">Sorted by company name</p></div>
@if($vendors->isEmpty())
<div class="panel"><x-empty :title="$total ? 'No vendors match this search' : 'Your network starts here'" :description="$total ? 'Try a different company name or broaden your filters to find the right record.' : 'Add your first vendor, capture their capabilities, and give your team a reliable place to find quotation contacts.'">@if($total)<x-button :href="route('vendors.index')" variant="secondary">Clear filters</x-button>@else<x-button :href="route('vendors.create')"><x-icon name="plus" />Add your first vendor</x-button>@endif</x-empty></div>
@else
<div class="table-wrap" role="region" aria-label="Vendor directory table; scroll horizontally for all columns" tabindex="0"><table class="table"><thead><tr><th scope="col">Company</th><th scope="col">Capabilities</th><th scope="col">Quotation contact</th><th scope="col">Status</th><th scope="col"><span class="sr-only">View vendor</span></th></tr></thead><tbody>
@foreach($vendors as $vendor)<tr><td><div class="flex items-center gap-3"><span class="avatar">{{ mb_strtoupper(mb_substr($vendor->display_name ?: $vendor->company_name,0,2)) }}</span><div><a class="font-semibold hover:text-accent" href="{{ route('vendors.show',$vendor) }}">{{ $vendor->company_name }}</a><p class="mt-1 text-xs text-slate-500">{{ \App\Models\Vendor::TYPES[$vendor->type] }}</p></div></div></td><td><div class="flex flex-wrap gap-1.5">@forelse($vendor->services as $service)<span class="service-tag">{{ $service }}</span>@empty<span class="text-xs text-slate-400">Not specified</span>@endforelse</div><p class="mt-2 max-w-[210px] truncate text-[11px] text-slate-500">{{ $vendor->coverage ?: 'Coverage not specified' }}</p></td><td>@if($vendor->primaryContact)<p class="text-xs font-medium">{{ $vendor->primaryContact->name }}</p><p class="mt-1 text-[11px] text-slate-500">{{ $vendor->primaryContact->email }}</p>@else<span class="badge badge-warning"><x-icon name="warning-circle" class="!h-3.5 !w-3.5" />Contact needed</span>@endif</td><td><x-badge :active="$vendor->is_active" />@if($vendor->is_demo)<span class="badge badge-warning ml-2">Fictional sample</span>@endif</td><td><a href="{{ route('vendors.show',$vendor) }}" class="inline-flex rounded-lg p-2 text-slate-500 hover:bg-slate-100 hover:text-accent" aria-label="View {{ $vendor->company_name }}"><x-icon name="arrow-right" /></a></td></tr>@endforeach
</tbody></table></div><x-pagination :records="$vendors" />
@endif
<p class="mt-5 flex items-center gap-2 text-xs text-slate-500"><x-icon name="lock-key" class="!h-4 !w-4" />Internal directory · Shared by your company’s admins and agents</p>
</x-layout>
