<x-layout :title="$vendor->display_name ?: $vendor->company_name">
<a class="text-link mb-6 inline-flex items-center gap-2 text-xs" href="{{ route('vendors.index') }}"><x-icon name="arrow-left" class="!h-4 !w-4" />Vendor directory</a>
<x-page-header :title="$vendor->company_name" :description="$vendor->display_name ? $vendor->display_name.' · '.\App\Models\Vendor::TYPES[$vendor->type] : \App\Models\Vendor::TYPES[$vendor->type]" eyebrow="Vendor record"><x-button :href="route('vendors.status',$vendor)" variant="secondary">{{ $vendor->is_active ? 'Deactivate' : 'Activate' }}</x-button><x-button :href="route('vendors.edit',$vendor)"><x-icon name="pencil-simple" />Edit vendor</x-button></x-page-header>
<div class="mb-6 flex flex-wrap items-center gap-3"><x-badge :active="$vendor->is_active" /><span class="text-xs text-slate-500">Vendor #{{ str_pad($vendor->id,4,'0',STR_PAD_LEFT) }}</span></div>
@if(! $vendor->is_active)<div class="alert alert-warning mb-6"><x-icon name="warning-circle" /><p>This vendor is inactive. Its details and history are preserved, and it will be excluded from future outreach selection.</p></div>@endif
@if(! $vendor->primaryContact)<div class="alert alert-warning mb-6"><x-icon name="warning-circle" /><div><p class="font-semibold">A primary quotation contact is needed.</p><p class="mt-1">This record can be maintained, but it will not be eligible for future outreach until a contact is assigned.</p><a href="{{ route('vendors.contacts.create',$vendor) }}" class="mt-2 inline-block font-semibold underline underline-offset-4">Add a quotation contact</a></div></div>@endif
@if($duplicates->isNotEmpty())<div class="alert alert-warning mb-6"><x-icon name="warning-circle" /><div><p class="font-semibold">Possible duplicate company</p><p class="mt-1">Another record uses this company name. Branches may be legitimate; review before outreach.</p>@foreach($duplicates as $duplicate)<a class="mt-2 mr-4 inline-block underline" href="{{ route('vendors.show',$duplicate) }}">{{ $duplicate->display_name ?: $duplicate->company_name }} · #{{ $duplicate->id }}</a>@endforeach</div></div>@endif
<div class="grid items-start gap-6 xl:grid-cols-[1fr_320px]"><div class="space-y-6">
<section class="panel panel-pad"><h2 class="section-title">Capabilities & coverage</h2><div class="mt-5 flex flex-wrap gap-2">@forelse($vendor->services as $service)<span class="service-tag">{{ $service }}</span>@empty<p class="text-xs text-slate-500">Services have not been specified.</p>@endforelse</div><dl class="mt-6 grid gap-6 sm:grid-cols-2"><div><dt class="eyebrow">Coverage & routes</dt><dd class="mt-2 whitespace-pre-line break-words text-sm leading-6">{{ $vendor->coverage ?: 'Not specified' }}</dd></div><div><dt class="eyebrow">Preferred communication</dt><dd class="mt-2 text-sm">{{ \App\Models\Vendor::CHANNELS[$vendor->communication_channel] }}</dd></div><div class="sm:col-span-2"><dt class="eyebrow">Minimum shipment / charge notes</dt><dd class="mt-2 whitespace-pre-line break-words text-sm leading-6">{{ $vendor->minimum_notes ?: 'Unknown · No minimum notes recorded' }}</dd></div></dl></section>
<section class="panel"><div class="flex flex-wrap items-center justify-between gap-4 border-b border-slate-100 p-5 sm:px-7"><div><h2 class="section-title">Contacts</h2><p class="text-xs text-slate-500">{{ $vendor->contacts->count() }} {{ $vendor->contacts->count() === 1 ? 'person' : 'people' }} in this vendor record</p></div><x-button :href="route('vendors.contacts.create',$vendor)" variant="secondary" class="btn-small"><x-icon name="plus" class="!h-4 !w-4" />Add contact</x-button></div>
@forelse($vendor->contacts as $contact)<div class="flex flex-wrap items-start justify-between gap-4 border-b border-slate-100 p-5 last:border-0 sm:p-7"><div class="flex min-w-0 gap-3"><span class="avatar !rounded-full">{{ mb_strtoupper(mb_substr($contact->name,0,2)) }}</span><div class="min-w-0"><div class="flex flex-wrap items-center gap-2"><h3 class="text-sm">{{ $contact->name }}</h3>@if($contact->is_primary)<span class="badge badge-active">Primary quotation contact</span>@endif</div><p class="mt-1 text-xs text-slate-500">{{ $contact->role ?: 'Role not specified' }}</p><p class="mt-3 break-all text-xs">{{ $contact->email }}</p><p class="mt-1 text-xs text-slate-500">{{ $contact->phone ?: 'No phone recorded' }}</p></div></div><a href="{{ route('vendors.contacts.edit',[$vendor,$contact]) }}" class="text-link inline-flex items-center gap-1 text-xs"><x-icon name="pencil-simple" class="!h-4 !w-4" />Edit<span class="sr-only"> {{ $contact->name }}</span></a></div>@empty<x-empty title="No contacts yet" description="Add someone your team can reach for quotation requests." icon="users-three" />@endforelse
<div class="rounded-b-[20px] bg-slate-50 px-7 py-3 text-[11px] text-slate-500">Email syntax is validated. Ownership and deliverability still need confirmation.</div></section>
<section class="panel panel-pad"><h2 class="section-title">Internal notes</h2><p class="mb-4 text-[11px] text-slate-500">Visible to your staff only</p><p class="whitespace-pre-line break-words text-sm leading-7">{{ $vendor->internal_notes ?: 'No internal notes recorded.' }}</p></section>
</div><aside class="panel panel-pad"><div class="mb-6 flex items-center gap-2"><x-icon name="clock" class="text-accent" /><h2 class="text-sm">Record activity</h2></div><x-activity :entries="$activity" /><x-pagination :records="$activity" /></aside></div>
</x-layout>
