<x-layout title="Follow-up policies">
<x-page-header title="A considered follow-up." eyebrow="Company policy" description="Approve predictable wording and a bounded business-day schedule. Each request still needs an exact staff activation."><x-button variant="secondary" :href="route('followups.index')">Attention queue</x-button></x-page-header>
<div class="mb-6 flex flex-wrap gap-2">@foreach(['rfq'=>'Vendor requests','client_quote'=>'Client quotations'] as $key=>$label)<a href="{{ route('settings.followups',['kind'=>$key]) }}" class="badge {{ $kind===$key?'tint-blue':'badge-inactive' }}">{{ $label }}</a>@endforeach<span class="badge {{ $policy?->enabled?'badge-active':'badge-inactive' }}">{{ $policy?->enabled?'Company policy enabled':'Automatic follow-ups disabled' }}</span></div>
<div class="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_330px]"><form method="POST" action="{{ route('settings.followups.save') }}" class="panel panel-pad space-y-6" data-unsaved>@csrf<input type="hidden" name="kind" value="{{ $kind }}"><input type="hidden" name="expected_number" value="{{ $policy?->number??0 }}">
<div><h2 class="section-title">Schedule & boundaries</h2><p class="hint">Version {{ $policy?->number??0 }} · {{ $defaults['timezone'] }}. Two and three business days are editable starter examples.</p></div>
<div class="grid gap-5 sm:grid-cols-2"><x-field name="interval_days" label="Business-day intervals" :value="old('interval_days',implode(',',$defaults['intervals']))" required hint="One interval per send, for example 2,3. Maximum five stages." /><x-field name="max_sends" label="Maximum cumulative sends" type="number" min="1" max="5" :value="old('max_sends',$defaults['max_sends'])" required /></div>
<fieldset><legend class="field-label">Working weekdays</legend><div class="mt-3 flex flex-wrap gap-3">@foreach([1=>'Mon',2=>'Tue',3=>'Wed',4=>'Thu',5=>'Fri',6=>'Sat',7=>'Sun'] as $day=>$label)<label class="flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-xs"><input name="weekdays[]" type="checkbox" value="{{ $day }}" @checked(in_array($day,old('weekdays',$defaults['weekdays']))) class="accent-accent">{{ $label }}</label>@endforeach</div></fieldset>
<div class="grid gap-5 sm:grid-cols-2"><x-field name="opens" label="Sending window opens" type="time" :value="old('opens',$defaults['opens'])" required /><x-field name="closes" label="Sending window closes" type="time" :value="old('closes',$defaults['closes'])" required /></div>
<x-field name="holiday_dates" label="Company holidays" type="textarea" :value="old('holiday_dates',implode(PHP_EOL,$defaults['holidays']))" hint="One YYYY-MM-DD date per line. Local company dates; the closing boundary is exclusive." />
<x-field name="freshness_minutes" label="Maximum incoming sync age · minutes" type="number" min="5" max="120" :value="old('freshness_minutes',$defaults['freshness_minutes'])" required hint="Every selected incoming folder must have completed a healthy sync within this interval." />
<div class="border-t border-slate-100 pt-6"><h2 class="section-title">Approved wording</h2><p class="hint">Allowed placeholders: [original_subject], [reference], [revision], [recipient_name], [company_name], [deadline], [stage_number]. Values come from frozen approved records.</p></div>
<x-field name="subject" label="Subject template" :value="old('subject',$defaults['subject'])" maxlength="250" required />
<x-field name="body" label="Message template" type="textarea" :value="old('body',$defaults['body'])" maxlength="5000" rows="10" required />
<x-field name="attachment_mode" label="Attachment permission" type="select"><option value="none" @selected(old('attachment_mode',$defaults['attachment_mode'])==='none')>No attachments</option><option value="approved" @selected(old('attachment_mode',$defaults['attachment_mode'])==='approved')>{{ $kind==='client_quote'?'Allow exact approved customer PDF':'Allow original approved request files' }}</option></x-field>
<label class="flex gap-3 rounded-xl bg-slate-50 p-4 text-xs leading-6"><input name="enabled" type="checkbox" value="1" @checked(old('enabled',$policy?->enabled??false)) class="mt-1 h-4 w-4 accent-accent">Enable this company policy. Each exact parent revision still needs an Agent activation. Disabling pauses current plans.</label>
<x-field name="reason" label="Policy approval reason" type="textarea" maxlength="2000" required /><x-button>Approve new policy version</x-button>
</form><aside class="space-y-6"><section class="panel panel-pad"><p class="eyebrow">Human control</p><h2 class="mt-3 text-xl font-medium tracking-tight">Bounded by design.</h2><p class="mt-4 text-xs leading-7 text-slate-500">Staff approve the exact recipient, sender, wording, files and stop conditions before activation. A policy edit preserves every prior approval and cumulative send count.</p><p class="mt-4 text-xs leading-7 text-slate-500">Questions, reviewed commercial responses, bounces, stale revisions and expiry stop or hold the plan. Out-of-office replies pause for staff review.</p></section><section class="panel panel-pad"><h2 class="section-title">Policy history</h2>@forelse($history as $item)<div class="mt-5 border-t border-slate-100 pt-4 text-xs leading-6"><strong>Version {{ $item->number }}</strong> · {{ $item->enabled?'Enabled':'Disabled' }}<br>{{ \App\Support\Processing::time($item->created_at) }}<br>{{ $item->reason }}</div>@empty<p class="hint">No approved version yet. Starter settings are disabled.</p>@endforelse</section></aside></div>
</x-layout>