<x-layout title="Follow-up plan">
<x-page-header title="Stay in touch, intentionally." eyebrow="Exact revision follow-ups" :description="$inquiry->reference.' · '.($kind==='rfq'?$source->revision->rfq->reference:$source->revision->quotation->reference).' · revision '.$source->revision->number"><x-button variant="secondary" :href="route('followups.index')">Attention queue</x-button><x-button variant="secondary" :href="route('inquiries.show',$inquiry)">Open inquiry</x-button></x-page-header>
<div class="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_350px]"><div class="min-w-0 space-y-6">
<section class="panel panel-pad"><div class="flex flex-wrap justify-between gap-3"><h2 class="section-title">Current follow-up plan</h2><span class="badge {{ $plan?->state==='active'?'tint-blue':'badge-inactive' }}">{{ ucfirst($plan?->state??'Not activated') }}</span></div>
<dl class="mt-6 grid gap-6 sm:grid-cols-3"><div><dt class="eyebrow">Mode</dt><dd class="mt-2 text-sm">{{ $plan?->authorization?->mode==='automatic'?'Approved automatic':($plan?->authorization?'Review each message':'No activation') }}</dd></div><div><dt class="eyebrow">Cumulative sends</dt><dd class="mt-2 text-sm">{{ $plan?->send_count??0 }} / {{ $plan?->authorization?->snapshot['policy']['max_sends']??'—' }}</dd></div><div><dt class="eyebrow">Next approved date</dt><dd class="mt-2 text-sm">{{ $plan?->next_due_at?\App\Support\Processing::time($plan->next_due_at):'No pending date' }}</dd></div></dl>
@if($plan?->authorization)<p class="hint">Policy version {{ $plan->authorization->snapshot['policy_number'] }} · Approved {{ \App\Support\Processing::time($plan->authorization->created_at) }} · Exact parent revision {{ $plan->authorization->snapshot['content']['revision'] }}</p>@endif
@if($plan?->reason)<p class="mt-5 rounded-xl bg-slate-50 p-4 text-xs leading-6">{{ $plan->reason }}</p>@endif
@if($plan?->fixture_at)<p class="hint">Synthetic business clock: {{ \App\Support\Processing::time($plan->fixture_at) }}. No real mail.</p>@endif
@php($responseTask=$plan?->tasks?->whereNotNull('mail_message_id')->sortByDesc('id')->first()) @if($responseTask)<a class="text-link mt-4 block text-xs" href="{{ route('mail.message',$responseTask->mail_message_id) }}">Latest response evidence: {{ $responseTask->title }} →</a>@endif
</section>
<section class="panel panel-pad"><h2 class="section-title">Review activation options</h2><p class="hint">Changing these options refreshes the exact message and schedule preview. Nothing is sent by a preview.</p>
<form method="GET" action="{{ route('followups.show',[$kind,$approval]) }}" class="mt-5 space-y-5"><x-field name="mode" label="Approval mode" type="select"><option value="manual_review" @selected($mode==='manual_review')>Review each follow-up before sending</option><option value="automatic" @selected($mode==='automatic')>Approved automatic · within frozen boundaries</option></x-field>
<label class="flex gap-3 text-xs leading-6"><input type="checkbox" name="attach" value="1" @checked(request()->boolean('attach')) class="mt-1 h-4 w-4 accent-accent">Include original approved files if the company policy permits them. Customer reminders use only the exact approved customer PDF.</label>
<label class="flex gap-3 text-xs leading-6"><input type="checkbox" name="acknowledge_response" value="1" @checked(request()->boolean('acknowledge_response')) class="mt-1 h-4 w-4 accent-accent">Intentionally start after previously reviewed responses. Explain why a new plan is appropriate below. Unreviewed replies and bounces remain blocking.</label>
@if($snapshot && !$snapshot['baseline']['dispatch_id'])<x-field name="manual_sent_at" label="Declared actual manual send time" type="datetime-local" step="1" :value="request('manual_sent_at',\Carbon\CarbonImmutable::parse($snapshot['baseline']['sent_at'])->setTimezone($snapshot['policy']['timezone'])->format('Y-m-d\\TH:i:s'))" hint="Prefilled from the existing manual declaration. Confirm or correct the actual past sending time; this exact date is part of activation approval." required />@endif<x-button variant="secondary">Refresh exact preview</x-button></form></section>
@if($blockers)<section class="panel panel-pad"><h2 class="section-title">Before activation</h2>@foreach($blockers as $error)<p class="mt-4 text-sm leading-7 text-[#855600]">{{ $error }}</p>@endforeach @can('manage-company')<a class="text-link mt-5 inline-block text-xs" href="{{ route('settings.followups',['kind'=>$kind]) }}">Review company policy →</a>@endcan</section>@endif
@if($snapshot)<section class="panel panel-pad"><p class="eyebrow">Exact replacement activation preview</p><h2 class="mt-3 section-title">Recipients & sending identity</h2><dl class="mt-5 grid gap-5 sm:grid-cols-2">@foreach(['to'=>'To'] as $key=>$label)<div><dt class="eyebrow">{{ $label }}</dt><dd class="mt-2 break-all text-xs leading-6">{{ $snapshot['content'][$key]['name'] }}<br>{{ $snapshot['content'][$key]['email'] }}</dd></div>@endforeach<div><dt class="eyebrow">CC</dt><dd class="mt-2 break-all text-xs leading-6">@forelse($snapshot['content']['cc'] as $cc){{ $cc['name'] }} &lt;{{ $cc['email'] }}&gt;<br>@empty None @endforelse</dd></div>@foreach(['from'=>'From','sender'=>'Actual sender','reply_to'=>'Reply-To'] as $key=>$label)<div><dt class="eyebrow">{{ $label }}</dt><dd class="mt-2 break-all text-xs leading-6">{{ $snapshot['envelope'][$key]['name']??'' }}<br>{{ $snapshot['envelope'][$key]['email'] }}</dd></div>@endforeach</dl>
<p class="mt-5 text-xs leading-7">Baseline: {{ $snapshot['baseline']['kind'] }} · {{ \App\Support\Processing::time(\Carbon\CarbonImmutable::parse($snapshot['baseline']['sent_at'])) }}.</p>@if(isset($snapshot['baseline']['evidence']))<p class="hint">{{ $snapshot['baseline']['evidence'] }}</p>@endif
<p class="hint">{{ $snapshot['content']['thread_provider_id']?'Uses the authorized provider thread with the frozen subject and RFC reply evidence.':'No provider thread is available for this manually recorded send; the reminder retains the exact reference.' }} {{ $snapshot['envelope']['is_demo']?'Synthetic transport · no real mail.':'' }}</p>
<h3 class="mt-6 text-sm font-medium">Approved attachments</h3>@forelse($snapshot['content']['manifest'] as $file)<p class="mt-3 break-all text-xs leading-6">{{ $file['name'] }} · {{ number_format($file['size']/1024,1) }} KB<br>SHA-256 {{ $file['checksum'] }}</p>@empty<p class="hint">No attachments.</p>@endforelse</section>
<section class="panel panel-pad"><h2 class="section-title">Exact messages & projected schedule</h2><p class="hint">{{ $snapshot['policy']['timezone'] }} · {{ $snapshot['policy']['opens'] }}–{{ $snapshot['policy']['closes'] }} · Maximum {{ $snapshot['policy']['max_sends'] }} cumulative sends. Later dates recalculate from actual preceding acceptance; one overdue stage at a time.</p><p class="hint">Working weekdays: {{ implode(', ',array_map(fn($day)=>[1=>'Mon',2=>'Tue',3=>'Wed',4=>'Thu',5=>'Fri',6=>'Sat',7=>'Sun'][$day],$snapshot['policy']['weekdays'])) }}. Holidays: {{ implode(', ',$snapshot['policy']['holidays'])?:'None approved' }}. Incoming sync maximum age: {{ $snapshot['policy']['freshness_minutes'] }} minutes.</p><p class="hint">Permitted placeholders: [original_subject], [reference], [revision], [recipient_name], [company_name], [deadline], [stage_number]. Frozen reviewed values are shown below.</p>
@foreach($snapshot['messages'] as $ordinal=>$message)<article class="mt-6 rounded-2xl border border-slate-200 p-5"><div class="flex flex-wrap justify-between gap-3"><h3 class="text-sm font-medium">Follow-up {{ $ordinal }}</h3><span class="badge badge-inactive">{{ \App\Support\Processing::time(\Carbon\CarbonImmutable::parse($snapshot['dates'][$loop->index])) }}</span></div>@if(\Carbon\CarbonImmutable::parse($snapshot['dates'][$loop->index])->gte(\Carbon\CarbonImmutable::parse($snapshot['expires_at'])))<p class="hint">Falls outside validity; this stage cannot send.</p>@endif<p class="mt-5 text-sm font-medium">{{ $message['subject'] }}</p><pre class="mt-4 whitespace-pre-wrap break-words font-sans text-sm leading-7 text-slate-600">{{ $message['body'] }}</pre></article>@endforeach
<p class="mt-6 text-xs leading-7">Expiry: {{ \App\Support\Processing::time(\Carbon\CarbonImmutable::parse($snapshot['expires_at'])) }}. Reminders never extend validity, change prices or alter shipment terms.</p></section>
@endif
@if($plan)<section class="panel panel-pad"><h2 class="section-title">Reminder history</h2>@forelse($plan->stages as $stage)<a href="{{ route('followups.stage',$stage) }}" class="mt-4 block rounded-xl border border-slate-200 p-4 text-xs leading-6"><strong>Follow-up {{ $stage->ordinal }}</strong> · {{ ucfirst(str_replace('_',' ',$stage->state)) }}<br>Due {{ \App\Support\Processing::time($stage->due_at) }}@if($stage->sent_at)<br>Accepted {{ \App\Support\Processing::time($stage->sent_at) }} · Delivery unconfirmed @endif</a>@empty<p class="hint">No reminder stage has been created yet.</p>@endforelse</section>@endif
</div><aside class="space-y-6"><section class="panel panel-pad"><h2 class="section-title">Stop & review conditions</h2><ul class="mt-4 space-y-3 text-xs leading-6 text-slate-500"><li>Meaningful response for the exact revision; client outcomes require staff review.</li><li>Questions go to staff. Out-of-office replies pause. Bounces stop the approved address.</li><li>Stale parent or selection, expiry, held/closed inquiry, inactive contacts or revoked approval.</li><li>Disconnected or changed sender, incomplete replies, unresolved matching, unhealthy incoming sync.</li><li>Uncertain submission blocks the next stage. A submitted message cannot be unsent.</li><li>At the cap: “No response after approved follow-ups” creates staff attention.</li></ul></section>
@if($snapshot)<section class="panel panel-pad"><h2 class="section-title">Approve exact activation</h2><p class="hint">Policy {{ $snapshot['policy_number'] }} · {{ $mode==='automatic'?'Approved automatic sending':'Explicit review for each due message' }} · Already counted {{ $snapshot['send_count'] }}.</p><form method="POST" action="{{ route('followups.activate',[$kind,$approval]) }}" class="mt-5 space-y-5">@csrf<input type="hidden" name="mode" value="{{ $mode }}">@if(!$snapshot['baseline']['dispatch_id'])<input type="hidden" name="manual_sent_at" value="{{ \Carbon\CarbonImmutable::parse($snapshot['baseline']['sent_at'])->setTimezone($snapshot['policy']['timezone'])->format('Y-m-d\\TH:i:s') }}">@endif<input type="hidden" name="digest" value="{{ \App\Support\Processing::hash($snapshot) }}"><input type="hidden" name="attach" value="{{ request()->boolean('attach')?1:0 }}"><input type="hidden" name="acknowledge_response" value="{{ request()->boolean('acknowledge_response')?1:0 }}"><x-field name="reason" id="activation-reason" label="Activation / replacement reason" type="textarea" maxlength="2000" required /><label class="flex gap-3 text-xs leading-6"><input type="checkbox" name="confirm" value="1" required class="mt-1 h-4 w-4 shrink-0 accent-accent">I approve these exact recipients, sender, wording, placeholders, files, schedule, cumulative cap, expiry and stop conditions for this revision.</label><x-button class="w-full">Activate approved plan</x-button></form></section>@endif
@if($plan && in_array($plan->state,['active','held']))<section class="panel panel-pad"><h2 class="section-title">Take control</h2><form method="POST" action="{{ route('followups.control',$plan) }}" class="mt-5 space-y-5">@csrf<x-field name="reason" id="control-reason" label="Pause / cancellation reason" type="textarea" maxlength="2000" required /><div class="flex flex-wrap gap-3"><x-button variant="secondary" name="action" value="pause">Pause</x-button><x-button variant="danger" name="action" value="cancel">Cancel</x-button></div></form></section>@endif
</aside></div></x-layout>