<x-layout :title="$staff->exists ? 'Manage staff' : 'Add staff'"><a class="text-link mb-6 inline-flex items-center gap-2 text-xs" href="{{ route('staff.index') }}"><x-icon name="arrow-left" />Staff & access</a><x-page-header :title="$staff->exists ? 'Manage staff account' : 'Add a staff member'" eyebrow="Administration" description="Assign a role and send a password setup link. Public registration is disabled." />
<div class="grid items-start gap-6 xl:grid-cols-[1fr_300px]"><div class="space-y-6">
<form class="panel panel-pad" method="POST" action="{{ $staff->exists ? route('staff.update',$staff) : route('staff.store') }}" @if($staff->exists) data-confirm-form="Role and status changes take effect immediately. Inactive accounts lose access. Keep at least one active admin." @endif>@csrf @if($staff->exists) @method('PATCH') @endif
<div class="grid gap-5 sm:grid-cols-2"><x-field name="name" label="Full name" :value="$staff->name" required maxlength="255" autocomplete="name" /><x-field name="email" label="Staff email" type="email" :value="$staff->email" required maxlength="255" autocomplete="email" :readonly="$staff->exists" :hint="$staff->exists ? 'Email is the account identity and is fixed in Phase 1.' : 'A password setup link is sent for active accounts.'" /><x-field name="role" label="Access role" type="select" required><option value="agent" @selected(old('role',$staff->role) === 'agent')>Agent</option><option value="admin" @selected(old('role',$staff->role) === 'admin')>Admin</option></x-field></div>
<label class="mt-6 flex items-start gap-3 rounded-lg border border-slate-200 p-4"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked(old('is_active',$staff->is_active)) class="mt-0.5 h-4 w-4 accent-accent"><span><span class="block text-sm font-medium">Active account</span><span class="mt-1 block text-xs leading-6 text-slate-500">Inactive staff cannot sign in or continue working through an existing session.</span></span></label>
<div class="mt-7 flex justify-end gap-3"><x-button :href="route('staff.index')" variant="secondary">Cancel</x-button><x-button>{{ $staff->exists ? 'Save access changes' : 'Create staff account' }}</x-button></div></form>
@if($staff->exists)<section class="panel panel-pad"><h2 class="section-title">Password setup & recovery</h2><p class="mt-3 text-xs leading-6 text-slate-500">Send a time-limited link to {{ $staff->email }}. Passwords and reset tokens are never shown in the workspace. Activate the account first if it is inactive.</p><form method="POST" action="{{ route('staff.reset',$staff) }}" class="mt-5">@csrf<x-button variant="secondary"><x-icon name="envelope-simple" />Send password setup link</x-button></form></section>@endif
</div><aside class="panel panel-pad"><h2 class="text-sm">Choose access deliberately</h2><div class="mt-5 space-y-5 text-xs leading-6 text-slate-500"><p><strong class="block text-ink">Agent</strong>View, create and edit vendors and contacts. Activate or deactivate vendors. Manage their own profile.</p><p><strong class="block text-ink">Admin</strong>All agent capabilities, plus staff administration and company settings.</p><p>Last active admin protection is enforced for every update.</p></div></aside></div>
</x-layout>
