<x-layout title="Approved RFQ outputs">
@php($mailDispatch=$revision->approval->outlookDispatch())
@include('mail.release-status',['dispatch'=>$mailDispatch])
@include('sourcing.header',['heading'=>$revision->approval->dispatchLabel(),'description'=>$snapshot['vendor_name'].' · exact revision '.$revision->number])
<div class="alert alert-success mb-6"><x-icon name="check-circle" /><div><p class="font-semibold">{{ $revision->approval->dispatchLabel() }}</p><p class="mt-2 text-xs leading-6">Copying or downloading never records a send. Outlook release requires a separately authorized sending envelope and an explicit enqueue action. Provider delivery or reading is not confirmed. {{ $revision->approval->dispatch?'This version is excluded from future automatic dispatch; approve a new revision for a deliberate resend.':'If you send this exact version outside LRS, record that separately below.' }}</p></div></div>
<div class="mb-6 flex flex-wrap gap-3"><a class="btn btn-secondary" href="{{ route('rfqs.review',[$inquiry,$rfq]) }}">Approval evidence & history</a><a class="btn btn-secondary" href="{{ route('rfqs.edit',[$inquiry,$rfq]) }}">Prepare a revised request</a></div>
<div class="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_340px]"><section class="panel panel-pad min-w-0"><h2 class="section-title">Exact approved email</h2>@foreach(['recipient'=>'Approved recipients','subject'=>'Subject','body'=>'Plain-text body'] as $key=>$label)@php($value=$key==='recipient'?'To: '.$snapshot['to']['email'].($snapshot['cc']?"\nCC: ".implode(', ',array_column($snapshot['cc'],'email')):''):$snapshot[$key])<div class="mt-6"><label class="label" for="copy-{{ $key }}">{{ $label }}</label><textarea id="copy-{{ $key }}" readonly class="input text-xs leading-7" rows="{{ $key==='body'?24:3 }}">{{ $value }}</textarea><div class="mt-3"><button type="button" hidden class="btn btn-secondary" data-copy-message="copy-{{ $key }}">Copy {{ $key==='recipient'?'recipients':$key }}</button><p data-copy-status role="status" class="mt-2 text-xs leading-6 text-slate-500">Select the text and use Ctrl+C or Command+C. No communication is recorded.</p></div></div>@endforeach</section>
<aside class="min-w-0 space-y-6"><section class="panel panel-pad"><h2 class="section-title">Approved attachments</h2><p class="mt-2 text-xs leading-6 text-slate-500">Only files in this approval’s immutable manifest. Each download rechecks current eligibility and checksum.</p>@forelse($snapshot['manifest'] as $file)<a class="text-link mt-4 block break-all text-xs leading-6" href="{{ route('rfqs.attachment',[$inquiry,$rfq,$file['document_id']]) }}">{{ $file['name'] }} · version {{ $file['version'] }} ↓</a>@empty<p class="mt-4 text-xs text-slate-500">No attachments approved.</p>@endforelse</section>
@if(!$revision->approval->dispatch && !$mailDispatch)<section class="panel panel-pad"><h2 class="section-title">Record an outside-LRS send</h2><p class="mt-2 mb-5 text-xs leading-6 text-slate-500">Use this only after actually sending the exact approved revision and all its To/CC recipients. It records your declaration, not delivery or reading.</p><form method="POST" data-unsaved action="{{ route('rfqs.manual',[$inquiry,$rfq]) }}" class="space-y-5">@csrf<input type="hidden" name="expected_revision" value="{{ $revision->number }}"><input type="hidden" name="digest" value="{{ $revision->approval->digest }}"><input type="hidden" name="action_key" value="{{ old('action_key',(string)\Illuminate\Support\Str::uuid()) }}"><x-field name="sent_at" label="Actual sending time" type="datetime-local" :value="\App\Support\InquiryWorkflow::local(now())" required :hint="'Local time · '.$company->timezone" /><x-field name="channel" label="External channel" type="select"><option value="email">Email · recorded manually</option><option value="other">Other · describe evidence</option></x-field><x-field name="recipient" label="Actual primary recipient" type="email" :value="$snapshot['to']['email']" required /><x-field name="evidence" label="Optional evidence / reference" type="textarea" maxlength="4000" hint="Describe your external message reference; do not enter credentials. Clearly label synthetic acceptance examples." /><label class="flex items-start gap-3 text-xs leading-6"><input type="checkbox" name="confirm_exact" value="1" required class="mt-1 h-4 w-4 shrink-0 accent-accent">I sent this exact approved revision, with its approved attachments and all To/CC recipients, at the declared time.</label><x-button>Record manual send</x-button></form></section>@elseif($revision->approval->dispatch)<section class="panel panel-pad"><h2 class="section-title">Manual dispatch evidence</h2><p class="mt-3 text-xs leading-6">{{ $revision->approval->dispatch->actor_name }} · {{ \App\Support\Processing::time($revision->approval->dispatch->sent_at) }} · {{ $revision->approval->dispatch->channel }}</p><p class="mt-4 whitespace-pre-line text-xs leading-6">{{ $revision->approval->dispatch->evidence?:'No additional evidence was declared.' }}</p><p class="mt-4 text-xs leading-6 text-slate-500">Another dispatch requires a deliberately revised and approved request. Cancelling cannot undo this historical external message.</p></section>@endif</aside></div>
</x-layout>
