<x-layout title="Review RFQ">
<div class="rfq-no-print">@include('sourcing.header',['heading'=>'Review the exact request.','description'=>$snapshot['vendor_name'].' · revision '.$revision->number])
@include('sourcing.gaps')
@if($revision->approval)@include('mail.release-status',['dispatch'=>$revision->approval->outlookDispatch()])@endif
@if($revision->approval)<a class="btn btn-secondary mb-5" href="{{ route('mail.preview',['rfq',$revision->approval->id]) }}">Outlook preview & dispatch history</a>@endif
<div class="mb-6 flex flex-wrap gap-3"><a class="btn btn-secondary" href="{{ route('rfqs.edit',[$inquiry,$rfq]) }}">Edit current draft</a><a class="btn btn-secondary" href="{{ route('inquiries.sourcing',$inquiry) }}">All vendors</a><button type="button" class="btn btn-secondary" data-print-rfq hidden>Print this preview</button>@if($revision->approval && !$releaseReasons)<a class="btn btn-primary" href="{{ route('rfqs.output',[$inquiry,$rfq]) }}">Approved copy & manual record</a>@endif</div>
@if($revision->approval)<section class="panel panel-pad mb-6"><span class="badge tint-green">{{ $revision->approval->dispatchLabel() }}</span><p class="mt-4 text-xs leading-6">Approved by {{ $revision->approval->approver_name }} · {{ \App\Support\Processing::time($revision->approval->approved_at) }}. Historical content remains frozen even when current release eligibility is blocked.</p><p class="mt-3 break-all text-[10px] text-slate-500">Content/manifest SHA-256 {{ $revision->approval->digest }}</p>@if($revision->approval->dispatch)<p class="mt-3 text-xs leading-6">Declared send: {{ \App\Support\Processing::time($revision->approval->dispatch->sent_at) }} · {{ $revision->approval->dispatch->channel }} · recorded by {{ $revision->approval->dispatch->actor_name }}. Provider delivery/reading is not confirmed.</p><p class="mt-2 whitespace-pre-line text-xs">{{ $revision->approval->dispatch->evidence }}</p>@endif</section>@endif</div>
<div class="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_340px]"><div class="min-w-0 space-y-6">@include('sourcing.preview')
<section class="panel panel-pad"><h2 class="section-title">Selected disclosure · {{ count($snapshot['manifest']) }} {{ count($snapshot['manifest'])===1?'file':'files' }}</h2><p class="mt-3 text-xs leading-6">Client identity {{ $snapshot['disclosure']['identity']?'included':'withheld in message' }} · Logistics addresses {{ $snapshot['disclosure']['addresses']?'explicitly included':'not included' }}<br>{{ $snapshot['disclosure']['notes']?:'No additional disclosure notes.' }}</p><p class="mt-3 text-xs leading-6">{{ number_format(array_sum(array_column($snapshot['manifest'],'size'))/1024/1024,2) }} MiB total. Preparation warning at {{ config('rfq.size_warning_kb')/1024 }} MiB; Outlook preview checks the Admin-configured transport limit and supported mailbox attachment method.</p>@if(array_sum(array_column($snapshot['manifest'],'size'))>config('rfq.size_warning_kb')*1024)<p class="mt-3 text-xs text-[#855600]">This selection may exceed common transport limits. Prepare smaller reviewed files if needed.</p>@endif @forelse($snapshot['manifest'] as $file)<article class="mt-4 rounded-xl border border-slate-200 p-4"><h3 class="break-all text-xs font-medium">{{ $file['name'] }}</h3><p class="mt-2 text-[11px] leading-6 text-slate-500">{{ \App\Models\InquiryDocument::CLASSES[$file['classification']] }} · {{ number_format($file['size']/1024,1) }} KB · {{ $file['mime'] }}<br>Document #{{ $file['document_id'] }} · version {{ $file['version'] }} · {{ $file['scan_status'] }}</p><p class="mt-2 break-all text-[10px] text-slate-500">{{ $file['checksum'] }}</p><a class="text-link mt-3 inline-block text-xs rfq-no-print" href="{{ route('inquiries.documents.show',[$inquiry,$file['document_id']]) }}">Inspect private source</a></article>@empty<p class="mt-4 text-xs text-slate-500">No attachments selected. Approval binds this explicit empty manifest.</p>@endforelse</section>
@if($changes)<section class="panel panel-pad rfq-no-print"><h2 class="section-title">What changed since revision {{ $revision->number-1 }}</h2><p class="mt-2 text-xs leading-6 text-slate-500">Every saved change remains visible. Confirmed shipment facts follow the inquiry revision path.</p>@foreach($changes as $key=>$change)<details class="mt-4 rounded-xl border border-slate-200 p-4"><summary class="cursor-pointer text-xs font-medium">{{ ucwords(str_replace('_',' ',$key)) }}</summary><div class="mt-4 grid gap-4 sm:grid-cols-2"><div><p class="eyebrow">Previous</p><pre class="mt-2 whitespace-pre-wrap break-all text-[11px] leading-6">{{ is_array($change['before'])?json_encode($change['before'],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE):var_export($change['before'],true) }}</pre></div><div><p class="eyebrow">Current</p><pre class="mt-2 whitespace-pre-wrap break-all text-[11px] leading-6">{{ is_array($change['after'])?json_encode($change['after'],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE):var_export($change['after'],true) }}</pre></div></div></details>@endforeach</section>@endif
</div><aside class="min-w-0 space-y-6 rfq-no-print">
@if(!$revision->approval && !$reasons && $rfq->current_number===$revision->number)<section class="panel panel-pad"><h2 class="section-title">Approve revision {{ $revision->number }}</h2><p class="mt-3 text-xs leading-6 text-slate-500">Approve this vendor, exact To/CC, confirmed baseline, deadline, full message, company reply/signature and file versions.</p><form class="mt-5 space-y-5" method="POST" action="{{ route('rfqs.approve',[$inquiry,$rfq]) }}">@csrf<input type="hidden" name="expected_revision" value="{{ $revision->number }}"><input type="hidden" name="digest" value="{{ $digest }}"><label class="flex items-start gap-3 text-xs leading-6"><input type="checkbox" name="approve_exact" value="1" required class="mt-1 h-4 w-4 shrink-0 accent-accent">I reviewed and approve this exact revision for this vendor. Nothing is sent by this approval.</label><x-button class="w-full">Approve revision {{ $revision->number }}</x-button></form></section>@endif
@if($rfq->current_number===$revision->number && !$revision->approval?->dispatch)<section class="panel panel-pad"><h2 class="section-title">Review decision</h2><form class="mt-5 space-y-4" method="POST" action="{{ route('rfqs.state',[$inquiry,$rfq]) }}">@csrf<input type="hidden" name="expected_revision" value="{{ $revision->number }}"><x-field name="target" label="State" type="select">@if(!$revision->approval)<option value="needs_approval">Needs approval</option><option value="changes_requested">Changes requested</option>@endif<option value="cancelled">Cancel future use</option></x-field><x-field name="reason" label="Decision reason" type="textarea" required maxlength="2000" /><x-button variant="secondary" class="w-full">Record review decision</x-button></form></section>@endif
@include('sourcing.history')<section class="panel panel-pad"><h2 class="section-title mb-5">RFQ audit timeline</h2><x-activity :entries="$activity" /></section>
</aside></div></x-layout>
