<x-layout title="Operations health">
<x-page-header title="Operations health" eyebrow="Admin · observed evidence" description="Check what needs attention before releasing work. An observed heartbeat is evidence of a recent invocation, not proof that every integration is healthy."><x-button variant="secondary" :href="route('reports.index')">Operational reports</x-button><x-button variant="secondary" :href="route('settings.mailbox')">Email connections</x-button></x-page-header>
<div class="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
@foreach(['scheduler_seen_at'=>'Scheduler invocation','worker_seen_at'=>'Health queue worker'] as $key=>$label)@php($seen=$settings->$key)@php($fresh=$seen && $seen->gte(now()->subMinutes(config('operations.heartbeat_stale_minutes'))))
<section class="panel panel-pad"><p class="eyebrow">{{ $label }}</p><p class="mt-4 text-xl font-medium {{ $fresh?'text-emerald-700':'text-amber-700' }}">{{ !$seen?'No observation':($fresh?'Recently observed':'Stale observation') }}</p><p class="hint mt-3">{{ $seen?\App\Support\OperationalReports::time($seen,$company->timezone):'Install the scheduler and a worker consuming health.' }}</p><p class="hint mt-2">Attention threshold: {{ config('operations.heartbeat_stale_minutes') }} minutes.</p></section>@endforeach
<section class="panel panel-pad"><p class="eyebrow">Uncertain / submitting mail</p><p class="mt-3 text-3xl tabular-nums">{{ $uncertainCount }}</p><p class="hint mt-3">{{ $exhaustedCount }} exhausted observation attempts. Review provider evidence; never resend an uncertain message.</p></section>
<section class="panel panel-pad"><p class="eyebrow">Failed queue jobs</p><p class="mt-3 text-3xl tabular-nums">{{ $failedCount }}</p><p class="hint mt-3">All provenances. Queue errors need investigation; business mail recovery remains per dispatch.</p></section>
</div>
<div class="mb-6 grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_340px]">
<section class="panel panel-pad"><div class="flex flex-wrap justify-between gap-3"><h2 class="section-title">Emergency outgoing control</h2><span class="badge {{ $settings->outbound_paused?'badge-warning':'badge-inactive' }}">{{ $settings->outbound_paused?'Paused':'Sending permitted subject to approvals' }}</span></div><p class="mt-4 text-sm leading-7 text-slate-500">Pause Outlook, Gmail and reminder release while incoming capture continues. Workers check this control before preparation and again at the frozen submission boundary. A request already in submission cannot be recalled.</p>
<p class="mt-4 text-xs leading-6">{{ $heldCount }} earlier queued/failed requests require individual review. Resume does not reactivate previous reminder plans or release pre-pause messages; each needs current eligibility, exact authority and explicit recovery/activation.</p>
@if($settings->outbound_changed_at)<p class="mt-4 text-xs leading-6 text-slate-500">Last decision {{ \App\Support\OperationalReports::time($settings->outbound_changed_at,$company->timezone) }} · {{ $settings->outbound_reason }}</p>@endif
@if(config('operations.restore_lockdown'))<div class="alert alert-warning mt-5">Restore lockdown is active. External work is disabled and this environment cannot resume sending.</div>@else
<form method="POST" action="{{ route('operations.control') }}" class="mt-6 space-y-5">@csrf<input type="hidden" name="epoch" value="{{ $settings->outbound_epoch }}"><input type="hidden" name="action" value="{{ $settings->outbound_paused?'resume':'pause' }}"><x-field name="reason" label="Reason and evidence for this decision" type="textarea" required minlength="12" maxlength="2000" /><label class="flex items-start gap-3 text-xs leading-6"><input type="checkbox" name="confirm" value="1" required class="mt-1 h-4 w-4 shrink-0 accent-accent">I reviewed the effect. Submitted mail cannot be recalled; resuming requires separate current review of earlier work.</label><x-button variant="{{ $settings->outbound_paused?'primary':'secondary' }}">{{ $settings->outbound_paused?'Explicitly resume outgoing control':'Pause outgoing business mail' }}</x-button></form>@endif
</section>
<section class="panel panel-pad"><h2 class="section-title">Today’s AI ledger · UTC</h2><p class="mt-4 text-xs leading-7">{{ $ai->enabled?'Live AI enabled subject to configuration':'Live AI disabled' }}<br>Recorded USD spent: {{ $budget?->spent??'No ledger row' }}<br>Reserved USD: {{ $budget?->reserved??'No ledger row' }}<br>Configured daily cap: {{ $ai->configuration['daily_cap']??'Unconfigured' }}<br>{{ $uncertainAi }} live runs with uncertain cost.</p><a class="text-link mt-5 block text-xs" href="{{ route('settings.ai') }}">Review AI settings & reconciliation →</a><p class="hint mt-4">Recorded estimates and holds are not a provider invoice. Missing amounts are not zero.</p></section>
</div>
<section class="panel panel-pad mb-6"><h2 class="section-title">Database queue backlog</h2><p class="hint mt-2">Queued and reserved jobs, including delayed work. Empty queues do not prove workers are running. The health queue records a separate actual worker heartbeat.</p>
<div class="table-wrap mt-5" tabindex="0" role="region" aria-label="Queue backlog"><table class="table min-w-[550px]"><thead><tr><th>Queue</th><th>Backlog</th><th>Reserved</th><th>Oldest job created</th></tr></thead><tbody>@forelse($queues as $q)<tr><td>{{ $q->queue }}</td><td>{{ $q->backlog }}</td><td>{{ $q->reserved }}</td><td>{{ \App\Support\OperationalReports::time(\Carbon\CarbonImmutable::createFromTimestampUTC($q->oldest),$company->timezone) }}</td></tr>@empty<tr><td colspan="4">No queued jobs observed.</td></tr>@endforelse</tbody></table></div>
@if($failed->isNotEmpty())<details class="mt-6"><summary class="cursor-pointer text-sm text-accent">Latest {{ $failed->count() }} failed job identities</summary>@foreach($failed as $f)<p class="mt-3 break-all text-xs leading-6">{{ $f->uuid }} · {{ $f->queue }} · {{ \App\Support\OperationalReports::time($f->failed_at,$company->timezone) }}</p>@endforeach<p class="hint mt-4">Investigate privately by this correlation identity. Payloads and exception text are intentionally withheld from this page. Do not use queue:retry all for mail.</p></details>@endif
</section>
<section class="panel panel-pad mb-6"><h2 class="section-title">Mailbox capture & reconnection</h2><div class="mt-5 grid gap-4 sm:grid-cols-2">@forelse($mailboxes as $m)<article class="rounded-2xl border border-slate-200 p-5"><h3 class="text-sm font-medium">{{ ucfirst($m->provider) }} #{{ $m->id }} · {{ $m->is_demo?'Fictional transport':'Company transport' }}</h3><p class="mt-3 text-xs leading-7">{{ ucfirst($m->state) }} · incoming {{ $m->incoming_enabled?'enabled':'paused' }}<br>Last observed sync {{ $m->last_sync_at?\App\Support\OperationalReports::time($m->last_sync_at,$company->timezone):'Unknown / never observed' }}</p>
@foreach($m->folders->where('kind','incoming') as $f)<p class="mt-3 break-words text-xs leading-6">{{ $f->name }} · {{ $f->enabled?'enabled':'paused' }} · {{ $f->failure_count }} failures · {{ $f->cycle_count }} items in current cycle<br>Folder sync {{ $f->last_sync_at?\App\Support\OperationalReports::time($f->last_sync_at,$company->timezone):'Unknown' }}</p>@endforeach
<a class="text-link mt-4 block text-xs" href="{{ route('settings.mailbox') }}">{{ $m->state!=='connected'?'Review configuration / reconnect':'Inspect folders and catch-up' }} →</a></article>@empty<p class="hint">No mailbox connections configured. Manual and website capture remain available.</p>@endforelse</div></section>
<section class="panel panel-pad mb-6"><h2 class="section-title">Mail attention · latest 25</h2><p class="hint mt-2">Includes fictional history, failed preparation and unresolved provider outcomes. Recovery uses the exact dispatch identity and fresh approvals.</p><div class="attention-list mt-5 space-y-4" tabindex="0" role="region" aria-label="Dispatches needing attention">@forelse($dispatches as $d)<article class="rounded-2xl border border-slate-200 p-4"><a class="text-link text-sm" href="{{ route('mail.dispatch',$d) }}">Dispatch #{{ $d->id }} · {{ $d->envelope->inquiry->reference }} →</a><p class="mt-2 text-xs leading-6">{{ $d->is_demo?'Fictional':'Company' }} · {{ ucfirst($d->envelope->mailbox->provider) }} · {{ $d->label() }}</p><p class="mt-2 text-xs leading-6 text-slate-500">Preparation attempts {{ $d->attempts }} / 6 · observations {{ $d->reconcile_attempts }} / 10. {{ $d->reconcile_attempts>=10?'Automatic observation exhausted; staff escalation required.':'' }}</p></article>@empty<p class="hint">No failed or uncertain dispatches observed.</p>@endforelse</div></section>
<div class="grid items-start gap-6 xl:grid-cols-2"><section class="panel panel-pad"><h2 class="section-title">Paused follow-ups · latest 25</h2><div class="attention-list" tabindex="0" role="region" aria-label="Paused follow-up plans">@forelse($plans as $p)<article class="mt-5 border-t border-slate-100 pt-4"><a class="text-link text-sm" href="{{ route('inquiries.show',$p->inquiry_id) }}">{{ $p->inquiry->reference }} →</a><p class="mt-2 text-xs leading-6">{{ ucfirst($p->state) }} · {{ $p->reason }}</p><p class="hint mt-2">Cumulative sends {{ $p->send_count }}. Review evidence before a new exact activation.</p></article>@empty<p class="hint mt-5">No paused, held or exhausted plans observed.</p>@endforelse</div><a class="text-link mt-5 block text-xs" href="{{ route('followups.index') }}">Open attention queue →</a></section>
<section class="panel panel-pad"><h2 class="section-title">Extraction attention · latest 25</h2><div class="attention-list" tabindex="0" role="region" aria-label="Extractions needing attention">@forelse($extractions as $e)<article class="mt-5 border-t border-slate-100 pt-4"><a class="text-link text-sm" href="{{ route('inquiries.extraction',$e->inquiry_id) }}">{{ $e->inquiry->reference }} · run #{{ $e->id }} →</a><p class="mt-2 text-xs leading-6">{{ $e->label() }} · {{ $e->error_code?:'Review recorded omissions / evidence' }}</p></article>@empty<p class="hint mt-5">No extraction failures or manual-review results observed.</p>@endforelse</div></section></div>
<p class="mt-6 text-xs leading-7 text-slate-500">This internal view sends no external alerts. Health evidence includes retained fictional records. Complete production supervision, encrypted backups and controlled live-provider pilot checks before relying on the system operationally. Recovery instructions and staff guidance are in the Phase 11 handoff.</p>
</x-layout>
