<x-layout title="Operational reports">
<x-page-header title="Operational reports" eyebrow="Insight from saved work" description="See where work is waiting, how requests are answered, and the economics of approved quotations. Every figure has a defined basis.">
<x-button variant="secondary" :href="route('reports.export', request()->except('page'))">Export this table · CSV</x-button>
</x-page-header>
@if($filters['data'] !== 'real')<div class="alert alert-warning mb-6"><x-icon name="warning-circle" /><p>{{ $filters['data']==='samples'?'Fictional records only.':'Real and fictional records together, labelled on every row.' }} These figures are saved examples, not real operational performance.</p></div>@endif
<form method="GET" action="{{ route('reports.index') }}" class="panel panel-pad mb-6">
<input type="hidden" name="tab" value="{{ $filters['tab'] }}">
<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
<x-field name="from" label="Inquiry received from" type="date" :value="$filters['from']" required />
<x-field name="to" label="Inquiry received through" type="date" :value="$filters['to']" required />
<x-field name="data" label="Record provenance" type="select">@foreach(['real'=>'Real records','samples'=>'Fictional records','all'=>'All · labelled'] as $v=>$label)<option value="{{ $v }}" @selected($filters['data']===$v)>{{ $label }}</option>@endforeach</x-field>
<x-field name="owner" label="Current owner" type="select"><option value="">All owners</option><option value="0" @selected($filters['owner']===0)>Unassigned</option>@foreach($owners as $owner)<option value="{{ $owner->id }}" @selected($filters['owner']===$owner->id)>{{ $owner->name }}</option>@endforeach</x-field>
<x-field name="status" label="Current inquiry status" type="select"><option value="">All statuses</option>@foreach(\App\Models\Inquiry::STATUSES as $v=>$label)<option value="{{ $v }}" @selected($filters['status']===$v)>{{ $label }}</option>@endforeach</x-field>
<x-field name="source" label="Intake source" type="select"><option value="">All sources</option>@foreach(\App\Models\Inquiry::CHANNELS as $v=>$label)<option value="{{ $v }}" @selected($filters['source']===$v)>{{ $label }}</option>@endforeach</x-field>
<x-field name="vendor" label="Vendor requested" type="select"><option value="">All vendors</option>@foreach($vendors as $vendor)<option value="{{ $vendor->id }}" @selected($filters['vendor']===$vendor->id)>{{ $vendor->display_name ?: $vendor->company_name }}</option>@endforeach</x-field>
<div class="flex items-end gap-3"><x-button>Apply filters</x-button><a class="text-link py-3 text-xs" href="{{ route('reports.index') }}">Reset</a></div>
</div><p class="mt-4 text-xs leading-6 text-slate-500">Received-date cohort in {{ $company->timezone }}, including the last day. Current status/owner and current quotation outcome are shown as of now. Maximum period: 366 days. Vendor filters cases with any RFQ to that vendor; the RFQ table further limits vendor rows.</p>
</form>
@php($t=$summary['totals']) @php($denominator=$t->accepted+$t->declined)
<div class="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
@foreach([['Inquiries',$t->inquiries,'One business case, regardless of revisions or source copies.'],['Waiting past deadline',$t->overdue,'Open inquiries with a recorded deadline before now.'],['Accepted / decided',$t->accepted.' / '.$denominator,$denominator?number_format($t->accepted/$denominator*100,1).'% win rate · Accepted ÷ (Accepted + Declined).':'Win rate unavailable · no accepted or declined outcome.'],['Recorded bookings',$t->booked,'Actual booking evidence tied to the current quotation and handoff.']] as [$label,$value,$note])
<section class="panel panel-pad"><p class="eyebrow">{{ $label }}</p><p class="mt-3 text-[30px] font-semibold tracking-tight tabular-nums">{{ $value }}</p><p class="mt-2 text-xs leading-6 text-slate-500">{{ $note }}</p></section>
@endforeach
</div>
<div class="mb-6 grid items-start gap-6 xl:grid-cols-2">
<section class="panel panel-pad"><h2 class="section-title">Work by current status</h2><p class="hint mt-2">A count of the filtered inquiry cohort. Select a status to inspect its cases.</p><div class="mt-5 space-y-4">
@forelse($summary['breakdowns']['status'] as $bucket)<a class="block rounded-xl p-2 hover:bg-slate-50 focus-visible:ring-2 focus-visible:ring-accent" href="{{ route('reports.index', array_merge(request()->except('page'),['status'=>$bucket->status,'tab'=>'inquiries'])) }}"><div class="flex justify-between gap-4 text-xs"><span>{{ \App\Models\Inquiry::STATUSES[$bucket->status]??$bucket->status }}</span><strong class="tabular-nums">{{ $bucket->count }}</strong></div><div class="mt-2 h-2 rounded-full bg-slate-100" aria-hidden="true"><div class="h-2 rounded-full bg-accent/75" style="width:{{ $t->inquiries?round($bucket->count/$t->inquiries*100,2):0 }}%"></div></div></a>@empty<p class="text-sm text-slate-500">No inquiries in this period. Adjust the dates or provenance.</p>@endforelse
</div><div class="mt-6 grid gap-5 border-t border-slate-100 pt-5 sm:grid-cols-2">@foreach(['source_channel'=>'Intake sources','owner_name'=>'Responsibility'] as $field=>$label)<div><h3 class="eyebrow">{{ $label }}</h3><dl class="mt-3 space-y-2">@foreach($summary['breakdowns'][$field] as $b)@php($v=$b->$field)<div class="flex justify-between gap-3 text-xs"><dt class="break-words">{{ $field==='source_channel'?(\App\Models\Inquiry::CHANNELS[$v]??$v):($v?:'Unassigned') }}</dt><dd class="tabular-nums">{{ $b->count }}</dd></div>@endforeach</dl></div>@endforeach</div></section>
<section class="panel panel-pad"><h2 class="section-title">Current quotation & request activity</h2><dl class="mt-5 grid grid-cols-2 gap-5 text-xs">@foreach(['quotations'=>'Current quotations','pending'=>'Awaiting decision','expired'=>'Expired without a decision','declined'=>'Recorded decline','revised'=>'Revision requested','review'=>'Questions / review required','handed'=>'Actually handed to operations','accepted'=>'Recorded acceptance'] as $key=>$label)<div><dt class="text-slate-500">{{ $label }}</dt><dd class="mt-2 text-lg font-semibold tabular-nums">{{ $t->$key }}</dd></div>@endforeach</dl>
@php($r=$summary['rfqs'])<div class="mt-6 rounded-2xl bg-slate-50 p-5"><h3 class="text-sm font-medium">Vendor RFQs · current shipment round</h3><p class="mt-3 text-xs leading-7">{{ $r->requests }} requests · {{ $r->sent }} with actual send evidence · {{ $r->answered }} meaningfully answered · {{ $r->unanswered }} unanswered.</p><p class="mt-2 text-xs leading-6 text-slate-500">Mean elapsed response: {{ $r->mean_hours===null?'Unknown':number_format($r->mean_hours,2).' hours' }} across answered requests only. Automated messages and replies before sending are excluded.</p></div>
<p class="hint mt-5">Acceptance and historical booking evidence do not prove current release eligibility. Open the lifecycle checklist before any handoff or booking instruction.</p></section>
</div>
<section class="panel panel-pad mb-6"><div class="flex flex-wrap items-start justify-between gap-4"><div><h2 class="section-title">Approved quotation economics</h2><p class="hint mt-2">One complete current approved revision per case, grouped in its frozen quotation currency. Includes pending/expired quotes; no new reporting FX. These are quoted estimates before other company expenses, not realized revenue.</p></div><span class="badge badge-inactive">Staff only</span></div>
<div class="table-wrap mt-5" tabindex="0" role="region" aria-label="Currency totals"><table class="table min-w-[720px]"><thead><tr><th>Currency</th><th>Quoted cost subtotal</th><th>Quoted selling subtotal</th><th>Customer total incl. tax</th><th>Estimated quoted profit</th><th>Unknown totals</th></tr></thead><tbody>@forelse($summary['money'] as $m)<tr><td class="font-medium">{{ $m->currency }} · {{ $m->quotations }} quotes</td><td class="tabular-nums">{{ $m->cost??'Unknown' }}</td><td class="tabular-nums">{{ $m->selling??'Unknown' }}</td><td class="tabular-nums">{{ $m->total??'Unknown' }}</td><td class="tabular-nums">{{ $m->profit??'Unknown' }}</td><td>{{ $m->unknown }}</td></tr>@empty<tr><td colspan="6">No current approved quotation amounts in this cohort.</td></tr>@endforelse</tbody></table></div>
</section>
<section class="panel panel-pad mb-6"><h2 class="section-title">Recorded AI usage</h2><p class="hint mt-2">Runs requested within this period on inquiries in the cohort. USD estimates use each run's captured rates; reservations and uncertain outcomes remain separate. Local extraction has no provider token charge recorded.</p><div class="mt-5 grid gap-4 sm:grid-cols-2">@forelse($summary['ai'] as $a)<div class="rounded-2xl border border-slate-200 p-5"><h3 class="text-sm font-medium">{{ $a->is_demo?'Fictional AI runs':'Live API runs · recorded evidence' }}</h3><p class="mt-3 text-xs leading-7">{{ $a->runs }} runs · {{ $a->input_tokens??'Unknown' }} recorded input tokens · {{ $a->output_tokens??'Unknown' }} recorded output tokens</p><p class="text-xs leading-7">Estimated USD {{ $a->cost??'Unknown' }} · USD {{ $a->held }} held · {{ $a->uncertain }} uncertain</p><p class="hint mt-2">{{ $a->unknown_usage }} runs have no reported usage; {{ $a->unknown_cost }} have unknown cost. Missing values are not zero.</p></div>@empty<p class="text-sm text-slate-500">No AI runs recorded for this period. Manual processing remains available.</p>@endforelse</div></section>
<nav class="mb-5 flex flex-wrap gap-2" aria-label="Report tables">@foreach(['inquiries'=>'Inquiry & outcomes','rfqs'=>'RFQ response evidence','ai'=>'AI run evidence'] as $tab=>$label)<a class="btn {{ $filters['tab']===$tab?'btn-primary':'btn-secondary' }}" href="{{ route('reports.index', array_merge(request()->except('page'),['tab'=>$tab])) }}" @if($filters['tab']===$tab) aria-current="page" @endif>{{ $label }}</a>@endforeach</nav>
<section class="panel overflow-hidden">
@if($rows->isEmpty())<x-empty title="No matching records" description="Try a wider received-date period, clear a filter, or inspect labelled fictional records. No data is created to fill a report." icon="file-text"><x-button variant="secondary" :href="route('reports.index')">Reset report</x-button></x-empty>@else
<div class="table-wrap" tabindex="0" role="region" aria-label="Report detail table"><table class="table min-w-[1080px]"><thead><tr>
@if($filters['tab']==='rfqs')<th>Request / inquiry</th><th>Vendor</th><th>Actual send evidence</th><th>First meaningful response</th><th>Elapsed time</th>
@elseif($filters['tab']==='ai')<th>Run / inquiry</th><th>Requested</th><th>Purpose / state</th><th>Reported tokens</th><th>Cost evidence · USD</th>
@else<th>Inquiry / owner</th><th>Current state / age</th><th>Current quotation outcome</th><th>Private quoted economics</th><th>Next action</th>@endif
</tr></thead><tbody>
@foreach($rows as $row)<tr>
@if($filters['tab']==='rfqs')
<td><a class="text-link" href="{{ route('rfqs.review',[$row->inquiry_id,$row->id]) }}">{{ $row->reference }}</a><p class="mt-2 text-xs text-slate-500">{{ $row->inquiry_reference }} · {{ $row->is_demo?'Fictional':'Real' }}</p></td><td>{{ $row->vendor_name }}</td><td><p>{{ $row->sent_at?\App\Support\OperationalReports::time($row->sent_at,$company->timezone):'Not actually sent / unknown' }}</p><p class="mt-2 text-xs text-slate-500">{{ $row->send_basis??'No send evidence' }}{{ $row->number?' · r'.$row->number:'' }}</p></td><td>{{ $row->responded_at?\App\Support\OperationalReports::time($row->responded_at,$company->timezone):($row->sent_at?'Unanswered':'Not measured') }}</td><td class="tabular-nums">{{ $row->response_hours===null?'Unknown':number_format($row->response_hours,2).' hours' }}</td>
@elseif($filters['tab']==='ai')@php($usage=is_string($row->usage)?json_decode($row->usage,true):$row->usage)
<td><a class="text-link" href="{{ route('inquiries.extraction',$row->inquiry_id) }}">{{ $row->reference }} · run #{{ $row->id }}</a><p class="mt-2 text-xs text-slate-500">{{ $row->is_demo?'Fictional AI':'Live API' }}</p></td><td>{{ \App\Support\OperationalReports::time($row->created_at,$company->timezone) }}</td><td>{{ ucfirst(str_replace('_',' ',$row->purpose)) }}<p class="mt-2 text-xs text-slate-500">{{ $row->state }} · {{ $row->model }}</p></td><td>{{ $usage['input_tokens']??'Unknown' }} input<br>{{ $usage['output_tokens']??'Unknown' }} output</td><td>{{ $row->estimated_cost??'Unknown' }} estimated<p class="mt-2 text-xs text-slate-500">{{ $row->reservation }} held · {{ $row->cost_uncertain?'Outcome uncertain':'Recorded estimate' }}</p></td>
@else
<td><a class="text-link" href="{{ route('inquiries.show',$row->id) }}">{{ $row->reference }}</a><p class="mt-2 text-xs">{{ $row->title }}</p><p class="mt-2 text-xs text-slate-500">{{ $row->owner_name?:'Unassigned' }} · {{ \App\Models\Inquiry::CHANNELS[$row->source_channel]??$row->source_channel }} · {{ $row->is_demo?'Fictional':'Real' }}</p></td>
<td><x-inquiry-status :status="$row->status" /><p class="mt-3 text-xs text-slate-500">Received {{ \App\Support\OperationalReports::time($row->received_at,$company->timezone) }}<br>{{ $row->status==='closed'?'Closed; aging not counted':floor(\Carbon\CarbonImmutable::parse($row->received_at)->diffInHours(now())).' elapsed hours since receipt' }}</p><p class="mt-2 text-xs {{ $row->response_due_at && \Carbon\CarbonImmutable::parse($row->response_due_at)->isPast() && $row->status!=='closed'?'text-amber-700':'text-slate-500' }}">Due {{ $row->response_due_at?\App\Support\OperationalReports::time($row->response_due_at,$company->timezone):'Unknown' }}</p></td>
<td>@if($row->quote_id)<a class="text-link" href="{{ route('quotations.review',[$row->id,$row->quote_id]) }}">{{ $row->quotation_reference }} · r{{ $row->quote_number }}</a>@endif<p class="mt-2">{{ ucfirst(str_replace('_',' ',$row->outcome)) }}</p><p class="mt-2 text-xs text-slate-500">{{ $row->provider_evidence??($row->manual_sent_at?'Manually recorded as sent':'No actual send evidence') }}</p><p class="mt-2 text-xs text-slate-500">{{ $row->approved_at?'Approved revision':'Draft / not approved' }}</p></td>
<td class="tabular-nums"><p>Selected native cost: {{ $row->selected_currency }} {{ $row->selected_cost??'Unknown' }}</p><p class="mt-2">Quoted cost: {{ $row->currency }} {{ $row->quoted_cost??'Unknown' }}</p><p class="mt-2">Selling subtotal: {{ $row->currency }} {{ $row->quoted_selling??'Unknown' }}</p><p class="mt-2 text-xs text-slate-500">Estimated profit {{ $row->currency }} {{ $row->estimated_profit??'Unknown' }}</p></td>
<td><a class="text-link" href="{{ $row->quote_id?route('lifecycle.index',$row->id):route('inquiries.show',$row->id) }}">{{ \App\Support\OperationalReports::nextAction($row) }} →</a>@if($row->attention)<p class="mt-2 text-xs text-slate-500">Open attention: {{ $row->attention }}</p>@endif<p class="mt-3 text-xs text-slate-500">Handoff {{ $row->handed_at?\App\Support\OperationalReports::time($row->handed_at,$company->timezone):'Not recorded for current basis' }}<br>Booking {{ $row->booked_at?\App\Support\OperationalReports::time($row->booked_at,$company->timezone):'Unconfirmed for current basis' }}</p></td>
@endif
</tr>@endforeach
</tbody></table></div><x-pagination :records="$rows" />@endif
</section>
<details class="panel panel-pad mt-6"><summary class="cursor-pointer text-sm font-medium text-accent">Metric definitions & limits</summary><div class="mt-5 space-y-4 text-xs leading-7 text-slate-500">
<p>Inquiry counts use stable inquiry IDs and original receipt time. Import copies, vendor alternatives, quote revisions and decision corrections never add inquiries. Sources and owners describe today's working record. Current quotation means the aggregate's current revision; its latest recorded human decision is counted once. Recorded human decisions remain historical outcomes after the quotation deadline passes. Expired means a current quote with no recorded decision whose deadline has passed; it is not a fresh-release guarantee. Pending, expired and review-required outcomes are excluded from Accepted ÷ (Accepted + Declined).</p>
<p>RFQ rows represent one vendor request in the current shipment round. Select the most recent revision with actual manual sending or provider acceptance/observation; approval and enqueue are not sends. The first exact matched incoming meaningful email received at or after that send determines elapsed hours, including weekends. Out-of-office, bounce, automation, noise, unmatched and duplicate-copy messages are excluded. Staff-only offline offers without a matched incoming email leave response time unknown. Manual send declarations and fictional provider evidence are visibly separate; no delivery or service-quality score is implied.</p>
<p>Selected cost is the native reviewed total of the latest unsuperseded final selection, which can still need fresh eligibility review. Quoted cost/selling/profit use the current saved pricing calculation only when its recorded gaps are empty. Currency totals include approved revisions only, retaining expired/pending quotes. Missing amounts remain unknown; sums exclude unknown amounts and list their count. Optional service prices are excluded from totals. Quote totals include stated tax/pass-through; profit compares selling subtotal with cost subtotal.</p>
<p>Handoff/booking counts use actual event times on the current handoff approval linked to the exact current quote and latest decision. They are historical evidence within that basis, not proof of fresh release eligibility, capacity or earned revenue. Review the lifecycle checklist for current gates. CSV dates are UTC; screens display {{ $company->timezone }}. Exports retain filters, have a 5,000-row limit and neutralize formula-like text. This system has no invoice/payment/revenue ledger.</p>
</div></details>
</x-layout>
