<x-layout title="Review the exact client decision."><x-page-header title="Review the exact client decision." eyebrow="Client response" description="Compare the original evidence with this quotation revision before recording an outcome."><x-button variant="secondary" :href="route('lifecycle.index',$inquiry)">Decision & handoff</x-button><x-button variant="secondary" :href="route('inquiries.show',$inquiry)">Inquiry</x-button></x-page-header>
<x-inquiry-navigation :inquiry="$inquiry" />@if($inquiry->is_demo)<div class="alert alert-warning mb-6">Fictional business preview · retained evidence describes a simulated shipment.</div>@endif
<div class="grid items-start gap-6 xl:grid-cols-2"><div class="min-w-0 space-y-6">
<section class="panel panel-pad"><div class="flex flex-wrap gap-3"><span class="badge tint-blue">Quote r{{ $revision->number }}</span><span class="badge badge-warning">{{ \App\Support\LifecycleEligibility::outcome($revision) }}</span></div><h2 class="section-title mt-5">{{ $revision->quotation->reference }}</h2><p class="mt-5 text-3xl font-semibold tracking-tight">{{ $revision->pricing['currency'] }} {{ $revision->pricing['total'] }}</p><p class="hint">Valid until {{ \App\Support\Processing::time($revision->expires_at) }}</p><x-button class="mt-5" variant="secondary" :href="route('quotations.pdf',[$inquiry,$revision])" target="_blank">Open exact quotation PDF</x-button><iframe title="Exact quotation PDF for decision review" src="{{ route('quotations.pdf',[$inquiry,$revision]) }}" class="mt-5 h-[360px] w-full rounded-xl border border-slate-200 bg-slate-100 sm:h-[520px]"></iframe><p class="hint">This preview and the PDF link use the same saved bytes.</p>
@foreach(['inclusions'=>'Inclusions','exclusions'=>'Exclusions','conditions'=>'Commercial terms'] as $key=>$label)<h3 class="eyebrow mt-6">{{ $label }}</h3><p class="mt-3 whitespace-pre-line break-words text-sm leading-7">{{ $revision->payload[$key]?:'Not stated' }}</p>@endforeach</section>
<section class="panel panel-pad"><h2 class="section-title">Response evidence</h2>@if($message)<a class="text-link mt-4 block text-xs" href="{{ route('mail.message',$message) }}">Original source and match review →</a><p class="hint">{{ $message->sender_email }} · {{ \App\Support\Processing::time($message->received_at) }}</p><pre class="mt-4 whitespace-pre-wrap break-words rounded-xl bg-slate-50 p-4 font-sans text-sm leading-7">{{ $message->text() }}</pre>@if(!$message->response_reviewed_at)<div class="alert alert-warning mt-5">Review the mail association and classification before accepting this email as commercial evidence.</div>@endif @else<p class="mt-4 text-sm leading-7 text-slate-500">Record the actual phone, meeting or offline decision. Include who agreed, the exact scope and where its supporting evidence is retained.</p>@endif</section></div>
<div class="min-w-0 space-y-6"><section class="panel panel-pad"><h2 class="section-title">{{ $latest?'Append a correction / renewed decision':'Record staff decision review' }}</h2>@if($latest)<p class="hint">The latest decision is {{ str_replace('_',' ',$latest->outcome) }} (#{{ $latest->id }}). This action appends evidence and preserves it.</p>@endif
<form data-unsaved class="mt-5 space-y-5" method="POST" action="{{ route('lifecycle.decision.save',[$inquiry,$revision]) }}">@csrf<input type="hidden" name="action_key" value="{{ old('action_key',\Illuminate\Support\Str::uuid()) }}"><input type="hidden" name="expected_decision" value="{{ $latest?->id??0 }}"><input type="hidden" name="corrects_id" value="{{ $latest?->id }}"><input type="hidden" name="mail_message_id" value="{{ $message?->id }}">
<div class="grid gap-5 sm:grid-cols-2"><x-field name="outcome" label="Requested outcome" type="select" required>@foreach(['accepted'=>'Accepted','revision_requested'=>'Revision requested','declined'=>'Declined','question'=>'Question / needs review'] as $key=>$label)<option value="{{ $key }}" @selected(old('outcome')===$key)>{{ $label }}</option>@endforeach</x-field>
<x-field name="channel" label="Evidence channel" type="select" required>@foreach(['email','phone','whatsapp','meeting','other'] as $key)<option @selected(old('channel',$message?'email':'phone')===$key)>{{ $key }}</option>@endforeach</x-field>
<x-field name="decided_at" label="Actual decision time" type="datetime-local" step="1" :value="now($company->timezone)->format('Y-m-d\TH:i:s')" required :hint="$company->timezone" />
<x-field name="contact_id" label="Authorized client contact" type="select"><option value="">Identity requires review</option>@foreach($contacts as $contact)<option value="{{ $contact->id }}" @selected(old('contact_id',$inquiry->client_contact_id)==$contact->id)>{{ $contact->name }} · {{ $contact->email }}</option>@endforeach</x-field></div>
<x-field name="reference" label="Supplied client reference / PO · optional" maxlength="500" />
<x-field name="po_document_id" label="Supplied PO document · optional" type="select"><option value="">No PO supplied</option>@foreach($documents as $doc)<option value="{{ $doc->id }}" @selected(old('po_document_id')==$doc->id)>{{ $doc->original_name }}</option>@endforeach</x-field><div class="grid gap-5 sm:grid-cols-2"><x-field name="decline_reason" label="Decline reason · optional" type="select"><option value="">Not stated</option>@foreach(['price','timing','scope','cancelled','competitor','other'] as $key)<option @selected(old('decline_reason')===$key)>{{ $key }}</option>@endforeach</x-field><x-field name="change_scope" label="Requested change affects" type="select">@foreach(['unknown'=>'Needs assessment','wording'=>'Wording / terms','shipment'=>'Shipment / service','cost'=>'Vendor cost assumptions'] as $key=>$label)<option value="{{ $key }}" @selected(old('change_scope','unknown')===$key)>{{ $label }}</option>@endforeach</x-field></div>
<x-field name="notes" label="Evidence and review / correction reason" type="textarea" rows="5" required maxlength="8000" />
@foreach(['identity_confirmed'=>'I verified the client contact and their authority to make this decision.','scope_confirmed'=>'I verified unconditional agreement to this exact revision, total, service scope and terms.','communicated_confirmed'=>'This exact approved quotation was communicated to the client.','conditional'=>'The response contains conditions or ambiguous acceptance. Keep acceptance under review.'] as $key=>$text)<label class="flex items-start gap-3 text-xs leading-6"><input type="checkbox" name="{{ $key }}" value="1" @checked(old($key)) class="mt-1 h-4 w-4 shrink-0 accent-accent">{{ $text }}</label>@endforeach
@include('lifecycle.documents')
<p class="hint">Old, expired, conditional or uncertain acceptance is retained as Needs review. Decline does not close the inquiry. Any substantive response stops matching reminders.</p><x-button class="w-full">Record exact client decision</x-button></form></section>
<section class="panel panel-pad"><h2 class="section-title">Decision history</h2>@forelse($history as $d)<article class="mt-5 border-t border-slate-100 pt-5"><span class="badge badge-inactive">{{ str_replace('_',' ',$d->outcome) }} · decision {{ $d->number }}</span><p class="hint">{{ $d->reviewer->name }} · {{ \App\Support\Processing::time($d->created_at) }}</p><p class="mt-3 whitespace-pre-line break-words text-sm leading-7">{{ $d->snapshot['notes'] }}</p>@foreach($d->snapshot['blocking_reasons'] as $reason)<p class="hint text-amber-800">{{ $reason }}</p>@endforeach @if($d->message)<a class="text-link mt-3 inline-block text-xs" href="{{ route('mail.message',$d->message) }}">Original email →</a>@endif</article>@empty<p class="hint">No reviewed decision for this exact revision.</p>@endforelse</section></div></div></x-layout>