<x-layout title="Handoff readiness"><x-page-header title="A clear handoff to operations." :eyebrow="$inquiry->reference.' · Readiness'" description="Review prerequisites, approve a frozen internal summary, then record actual operations and booking evidence."><x-button variant="secondary" :href="route('lifecycle.index',$inquiry)">Lifecycle</x-button>@can('manage-company')<x-button variant="secondary" :href="route('settings.handoff')">Company requirements</x-button>@endcan</x-page-header>
<x-inquiry-navigation :inquiry="$inquiry" />
@php($reasons=$current?($current->approval?\App\Support\LifecycleEligibility::approvalReasons($current->approval):\App\Support\LifecycleEligibility::revisionReasons($current)):[])
@if($inquiry->is_demo)<div class="alert alert-warning mb-6">Fictional business preview. This workflow must not create a real booking.</div>@endif
<div class="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_360px]"><div class="min-w-0 space-y-6">
<section class="panel panel-pad"><div class="flex flex-wrap justify-between gap-3"><h2 class="section-title">Current readiness</h2><span class="badge {{ $ready['ready']?'badge-active':'badge-warning' }}">{{ $ready['ready']?'All prerequisites evidenced':'Prerequisites need attention' }}</span></div><p class="hint">Policy {{ $ready['policy']?'v'.$ready['policy']->number:'not yet approved' }} · confirmation freshness {{ $ready['policy']?->snapshot['freshness_hours']?($ready['policy']->snapshot['freshness_hours'].' hours'):'no company age limit configured; supplied expiries still apply' }}</p>
<div class="mt-6 space-y-3">@foreach($ready['items'] as $key=>$item)<article class="flex items-start gap-4 rounded-xl border border-slate-200 p-4"><x-icon :name="$item['state']==='complete'?'check-circle':'clipboard-text'" :class="$item['state']==='complete'?'text-green-700':'text-slate-400'" /><div class="min-w-0 flex-1"><div class="flex flex-wrap justify-between gap-2"><h3 class="text-sm font-medium">{{ $item['label'] }}</h3><span class="badge {{ $item['state']==='complete'?'badge-active':($item['state']==='missing'?'badge-warning':'badge-inactive') }}">{{ ucfirst(str_replace('_',' ',$item['state'])) }}</span></div><p class="hint whitespace-pre-line break-words">{{ $item['reason'] }}</p>@if($item['exception'])<p class="mt-2 text-xs leading-6 text-amber-800">Admin exception: {{ $item['exception'] }}</p>@endif</div></article>@endforeach</div></section>
<section class="panel panel-pad"><h2 class="section-title">Checklist evidence</h2><p class="hint">Saving prepares a new private snapshot. Address or commercial changes go through shipment and quotation review.</p>
<form data-unsaved class="mt-5 space-y-5" method="POST" action="{{ route('lifecycle.handoff.save',$inquiry) }}">@csrf<input type="hidden" name="expected_revision" value="{{ $current?->number??0 }}">
<x-field name="operations_owner_id" label="Responsible operations owner" type="select"><option value="">Choose active staff</option>@foreach($staff as $person)<option value="{{ $person->id }}" @selected(old('operations_owner_id',$evidence['operations_owner_id']??$inquiry->owner_id)==$person->id)>{{ $person->name }}</option>@endforeach</x-field>
@foreach(['pickup','delivery'] as $type)@if($ready['items'][$type.'_contact']['state']!=='not_applicable')<x-field :name="$type.'_contact'" :label="ucfirst($type).' contact · name and usable phone/email'" type="textarea" :value="$evidence[$type.'_contact']??''" maxlength="1000" />@endif @endforeach
<label class="flex items-start gap-3 text-xs leading-6"><input type="checkbox" name="cargo_ready_confirmed" value="1" @checked(old('cargo_ready_confirmed',$evidence['cargo_ready_confirmed']??false)) class="mt-1 h-4 w-4 shrink-0 accent-accent">I verified cargo availability on the agreed ready date.</label>
<x-field name="cargo_evidence" label="Cargo readiness evidence" type="textarea" :value="$evidence['cargo_evidence']??''" maxlength="3000" />
@include('lifecycle.documents',['selectedDocuments'=>$evidence['document_ids']??[]])
@foreach($ready['policy']?->snapshot['required_documents']??[] as $index=>$requirement)<x-field :name="'document_map['.$index.']'" :label="$requirement['label'].' · '.$requirement['service']" type="select"><option value="">Missing / not supplied</option>@foreach($documents as $doc)<option value="{{ $doc->id }}" @selected(old('document_map.'.$index,$evidence['document_map'][$index]??null)==$doc->id)>{{ $doc->original_name }} · v{{ $doc->version }}</option>@endforeach</x-field>@endforeach
@if($ready['policy']?->snapshot['require_deposit'])<div class="rounded-xl bg-slate-50 p-4 space-y-4"><label class="flex gap-3 text-xs leading-6"><input type="checkbox" name="deposit_confirmed" value="1" @checked(old('deposit_confirmed',$evidence['deposit_confirmed']??false)) class="mt-1 h-4 w-4 shrink-0 accent-accent">Actual deposit confirmed through the company's external process.</label><x-field name="deposit_at" label="Actual deposit confirmation time" type="datetime-local" :value="empty($evidence['deposit_at'])?'':\Carbon\CarbonImmutable::parse($evidence['deposit_at'])->setTimezone($company->timezone)->format('Y-m-d\\TH:i')" /><x-field name="deposit_evidence" label="Deposit evidence / reference" type="textarea" :value="$evidence['deposit_evidence']??''" maxlength="3000" /></div>@endif
@can('manage-company')@foreach($ready['policy']?->snapshot['operational_exceptions']??[] as $key)<x-field :name="'exceptions['.$key.']'" :label="'Optional Admin exception · '.str_replace('_',' ',$key)" type="textarea" maxlength="2000" hint="Record explicit authority and operational reason. Commercial acceptance, pricing, scope and capacity cannot be overridden." />@endforeach @endcan
<x-field name="reason" label="Preparation / change reason" type="textarea" required maxlength="2000" /><x-button>Save private handoff revision</x-button></form></section>
@if($message)<section class="panel panel-pad"><h2 class="section-title">Original booking response</h2><a class="text-link mt-4 block text-xs" href="{{ route('mail.message',$message) }}">Review original source and exact association →</a><pre class="mt-4 whitespace-pre-wrap break-words rounded-xl bg-slate-50 p-4 font-sans text-sm leading-7">{{ $message->text() }}</pre>@if(!$message->response_reviewed_at)<p class="hint text-amber-800">Review the original mail association before using it as booking evidence.</p>@endif</section>@endif
@if($current?->approval)<section class="panel panel-pad"><h2 class="section-title">Record actual operations / booking evidence</h2><p class="hint">Approval #{{ $current->approval->id }} · events are append-only. Booking confirmation needs actual vendor evidence.</p>
<form class="mt-5 space-y-5" method="POST" action="{{ route('lifecycle.event',[$inquiry,$current->approval]) }}">@csrf<input type="hidden" name="action_key" value="{{ old('action_key',\Illuminate\Support\Str::uuid()) }}">
<div class="grid gap-5 sm:grid-cols-2"><x-field name="kind" label="Actual event" type="select">@foreach(['handed_to_operations'=>'Handed to operations','booking_requested'=>'External booking requested','booking_confirmed'=>'Vendor booking confirmed'] as $key=>$label)<option value="{{ $key }}" @selected(old('kind')===$key)>{{ $label }}</option>@endforeach</x-field><x-field name="occurred_at" label="Actual event time" type="datetime-local" step="1" :value="now($company->timezone)->format('Y-m-d\TH:i:s')" required :hint="$company->timezone" />
<x-field name="vendor_reference" label="Actual vendor booking reference" maxlength="500" /><x-field name="contact_id" label="Vendor contact · required for confirmed booking" type="select"><option value="">Not yet confirmed</option>@foreach($current->confirmation?->request->selection->revision->offer->vendor->contacts()->where('is_active',true)->get()??[] as $contact)<option value="{{ $contact->id }}" @selected(old('contact_id')==$contact->id)>{{ $contact->name }} · {{ $contact->email }}</option>@endforeach</x-field><x-field name="pickup_date" label="Vendor-confirmed pickup / cargo date" type="date" /><x-field name="arrival_date" label="Confirmed arrival · when agreed" type="date" />
<x-field name="mail_message_id" label="Reviewed vendor booking email · optional" type="select"><option value="">Offline / supplied document evidence</option>@foreach($vendorEmails as $sourceEmail)<option value="{{ $sourceEmail->id }}" @selected(old('mail_message_id',$message?->id)==$sourceEmail->id)>{{ $sourceEmail->subject }} · {{ \App\Support\Processing::time($sourceEmail->received_at) }}</option>@endforeach</x-field><x-field name="corrects_id" label="Latest event ID being corrected · optional" type="number" min="1" /></div>
<label class="flex items-start gap-3 text-xs leading-6"><input type="checkbox" name="scope_confirmed" value="1" @checked(old('scope_confirmed')) class="mt-1 h-4 w-4 shrink-0 accent-accent">Vendor booking evidence agrees with the accepted rate, scope and reconfirmed dates.</label><x-field name="notes" label="Actual evidence / correction reason" type="textarea" required rows="5" maxlength="5000" />@include('lifecycle.documents')
<x-button>Record actual event evidence</x-button></form></section>@endif
<section class="panel panel-pad"><h2 class="section-title">Operations evidence</h2>@forelse($events as $event)<article class="mt-5 border-t border-slate-100 pt-5"><p class="text-sm font-medium">#{{ $event->id }} · {{ ucfirst(str_replace('_',' ',$event->kind)) }}</p><p class="hint">{{ \App\Support\Processing::time($event->occurred_at) }} · {{ $event->recorder?->name }}</p><p class="mt-3 break-words text-sm leading-7">{{ $event->snapshot['data']['vendor_reference']??'' }} · {{ $event->snapshot['data']['notes'] }}</p>@if($event->corrects_id)<p class="hint">Corrects #{{ $event->corrects_id }}; original retained.</p>@endif</article>@empty<p class="hint">No actual handoff or vendor booking evidence recorded for this approval.</p>@endforelse</section>
</div><aside class="min-w-0 space-y-6"><section class="panel panel-pad"><h2 class="section-title">Frozen handoff snapshot</h2>@if($current)<span class="badge tint-blue mt-4">Handoff v{{ $current->number }}</span><p class="hint">{{ $current->snapshot['reason'] }}</p><x-button class="mt-5 w-full" variant="secondary" :href="route('lifecycle.pdf',[$inquiry,$current])" target="_blank">Review private internal PDF</x-button><p class="hint">Includes internal vendor costs and profit. This export is restricted to staff and excluded from vendor-facing mail.</p>
@if($reasons)<div class="mt-5 space-y-3">@foreach($reasons as $reason)<p class="text-xs leading-6 text-amber-800">{{ $reason }}</p>@endforeach</div>
@elseif($current->approval)<div class="mt-5 rounded-xl bg-green-50 p-4"><p class="text-sm font-medium">Handoff approved</p><p class="hint">{{ $current->approval->reviewer->name }} · {{ \App\Support\Processing::time($current->approval->approved_at) }}</p><p class="hint">Approval alone does not confirm booking.</p></div>
@else<form method="POST" class="mt-5 space-y-5" action="{{ route('lifecycle.handoff.approve',[$inquiry,$current]) }}">@csrf<input type="hidden" name="digest" value="{{ $current->digest }}"><label class="flex items-start gap-3 text-xs leading-6"><input type="checkbox" name="confirm" value="1" required class="mt-1 h-4 w-4 shrink-0 accent-accent">I reviewed the exact internal PDF, accepted commercial basis, vendor confirmation, checklist evidence, contacts and operations owner.</label><x-button class="w-full">Approve exact handoff</x-button></form>@endif
@else<p class="hint">Complete the evidence and save a handoff revision. Missing prerequisites block approval.</p>@endif</section>
@if($current?->approval && !$reasons && $events->contains('kind','handed_to_operations') && !$events->contains('kind','booking_confirmed'))<section class="panel panel-pad"><h2 class="section-title">Optional booking instruction</h2><p class="hint">Prepare an explicitly reviewed vendor message. The shared outbox rechecks the handoff before submission.</p><x-button class="mt-5 w-full" variant="secondary" :href="route('lifecycle.booking.compose',$inquiry)">Prepare booking instruction</x-button>@foreach($messages as $op)<a class="text-link mt-4 block text-xs" href="{{ route('lifecycle.message',[$inquiry,$op]) }}">Booking message v{{ $op->number }} →</a>@endforeach</section>@endif
<section class="panel panel-pad"><h2 class="section-title">Preserved exports</h2>@forelse($history as $h)<a class="text-link mt-4 block text-xs" href="{{ route('lifecycle.pdf',[$inquiry,$h]) }}">Private handoff v{{ $h->number }} · {{ $h->approval?'approved':'prepared' }} →</a>@empty<p class="hint">No private handoff export yet.</p>@endforelse</section>
</aside></div></x-layout>