<x-layout title="Decision & handoff"><x-page-header :title="$inquiry->title" :eyebrow="$inquiry->reference.' · Decision & handoff'" description="Follow the exact commercial agreement through a controlled operations handoff."><x-button variant="secondary" :href="route('inquiries.show',$inquiry)">Inquiry workspace</x-button><x-button :href="route('lifecycle.handoff',$inquiry)">Readiness checklist</x-button></x-page-header>
<x-inquiry-navigation :inquiry="$inquiry" />
<x-lifecycle-panel :inquiry="$inquiry" />
<div class="mt-6 grid items-start gap-6 xl:grid-cols-3">
<section class="panel panel-pad min-w-0"><span class="metric-icon tint-blue"><x-icon name="file-text" /></span><h2 class="section-title mt-5">Client decision</h2><p class="mt-3 text-sm">{{ $status['q']?\App\Support\LifecycleEligibility::outcome($status['q']):'Awaiting approved quotation' }}</p><p class="hint">Acceptance confirms the exact price, scope and terms. It creates a reconfirmation task.</p>
@if($status['q'])@php($q=$status['q'])<a class="mt-5 block rounded-xl border border-blue-100 bg-blue-50/40 p-4" href="{{ route('lifecycle.decision',[$inquiry,$q]) }}"><p class="text-link text-xs">{{ $q->quotation->reference }} · r{{ $q->number }}</p><p class="mt-2 text-xs">{{ \App\Support\LifecycleEligibility::outcome($q) }} · {{ $q->pricing['currency'] }} {{ $q->pricing['total'] }}</p></a>
@php($older=$quotes->where('id','!=',$q->id)->sortByDesc('number'))
@if($older->count())<details class="mt-5 rounded-xl border border-slate-200 p-4"><summary class="cursor-pointer text-xs font-medium">Earlier quotations · {{ $older->count() }}</summary><div class="mt-4 space-y-4">@foreach($older as $oldQuote)<a class="text-link block text-xs leading-6" href="{{ route('lifecycle.decision',[$inquiry,$oldQuote]) }}">Revision {{ $oldQuote->number }} · {{ \App\Support\LifecycleEligibility::outcome($oldQuote) }} · {{ $oldQuote->pricing['currency'] }} {{ $oldQuote->pricing['total'] }}</a>@endforeach</div></details>@endif
@else<p class="mt-5 text-sm text-slate-500">Prepare, review and approve a client quotation first.</p>@endif
<x-button class="mt-5" variant="secondary" :href="route('quotations.index',$inquiry)">New quotation draft</x-button></section>
<section class="panel panel-pad min-w-0"><span class="metric-icon tint-green"><x-icon name="check-circle" /></span><h2 class="section-title mt-5">Vendor confirmation</h2><p class="hint">Actual rate, scope, capacity and date evidence must match the accepted basis.</p>
@forelse($requests as $r)<a class="mt-5 block rounded-xl border border-slate-200 p-4" href="{{ route('lifecycle.vendor',[$inquiry,$r]) }}"><p class="text-link text-xs">{{ $r->selection->snapshot['vendor']['name'] }} · acceptance #{{ $r->client_decision_id }}</p><p class="mt-2 text-xs">{{ ucfirst($r->current()?->status??'pending') }} · quote r{{ $r->decision->revision->number }}</p>@if($status['d']?->id!==$r->client_decision_id)<span class="badge badge-inactive mt-3">Earlier decision basis</span>@endif</a>@empty<p class="mt-5 text-sm text-slate-500">An unconditional reviewed client acceptance opens this step.</p>@endforelse</section>
<section class="panel panel-pad min-w-0"><span class="metric-icon tint-blue"><x-icon name="clipboard-text" /></span><h2 class="section-title mt-5">Operations handoff</h2><p class="mt-3 text-sm">{{ $status['handoff'] }}</p><p class="hint">A private, frozen operations summary. Actual vendor booking requires separate evidence.</p><p class="mt-5 rounded-xl bg-blue-50 p-4 text-sm font-medium">{{ $status['booking'] }}</p>@if($status['h'])<p class="hint">Evidence basis: handoff v{{ $status['h']->number }} · quote r{{ $status['h']->decision->revision->number }}. Current release is checked separately.</p>@endif<x-button class="mt-5" :href="route('lifecycle.handoff',$inquiry)">Open readiness</x-button>@can('manage-company')<a class="text-link mt-5 block text-xs" href="{{ route('settings.handoff') }}">Company prerequisites →</a>@endcan</section></div>
<section class="panel panel-pad mt-6"><h2 class="section-title">Lifecycle history</h2><p class="hint">Recorded outcome time and staff review time remain distinct. Earlier PDFs and corrected decisions stay available.</p>
<div class="mt-6 space-y-4">
@foreach($decisions as $d)<article class="rounded-xl border border-slate-200 p-4"><p class="text-sm font-medium">Client {{ str_replace('_',' ',$d->outcome) }} · quote r{{ $d->revision->number }} · decision {{ $d->number }}</p><p class="hint">Occurred {{ \App\Support\Processing::time($d->decided_at) }} · reviewed {{ \App\Support\Processing::time($d->created_at) }} by {{ $d->reviewer->name }}</p><p class="mt-3 whitespace-pre-line break-words text-xs leading-6">{{ $d->snapshot['notes'] }}</p>@if($d->corrects_id)<p class="hint">Corrects decision #{{ $d->corrects_id }}; original retained.</p>@endif</article>@endforeach
@foreach($confirmations as $v)<article class="rounded-xl border border-slate-200 p-4"><p class="text-sm">Vendor {{ ucfirst($v->status) }} · confirmation v{{ $v->number }}</p><p class="hint">{{ \App\Support\Processing::time($v->confirmed_at) }} · reviewed by {{ $v->reviewer->name }}</p><p class="mt-2 text-xs leading-6">{{ $v->snapshot['data']['notes'] }}</p></article>@endforeach
@foreach($handoffs as $h)<article class="rounded-xl border border-slate-200 p-4"><a class="text-link text-xs" href="{{ route('lifecycle.pdf',[$inquiry,$h]) }}">Private handoff v{{ $h->number }} · {{ $h->approval?'Approved snapshot':'Prepared snapshot' }} →</a><p class="hint">{{ \App\Support\Processing::time($h->created_at) }} · {{ $h->snapshot['reason'] }}</p></article>@endforeach
@foreach($events as $e)<article class="rounded-xl border border-slate-200 p-4"><p class="text-sm">{{ ucfirst(str_replace('_',' ',$e->kind)) }} · approval #{{ $e->handoff_approval_id }}</p><p class="hint">{{ \App\Support\Processing::time($e->occurred_at) }} · {{ $e->recorder?->name }}</p><p class="mt-2 break-words text-xs leading-6">{{ $e->snapshot['data']['vendor_reference']??'' }} · {{ $e->snapshot['data']['notes'] }}</p></article>@endforeach
@if(!$decisions->count()&&!$confirmations->count()&&!$handoffs->count())<p class="text-sm text-slate-500">No commercial outcomes have been reviewed. Start with the exact approved quotation.</p>@endif
</div></section></x-layout>