<form data-unsaved method="POST" action="{{ route('lifecycle.message.save',[$inquiry,$kind,$parent->id]) }}" class="mt-5 space-y-5">@csrf<input type="hidden" name="expected_revision" value="{{ $defaults['expected_revision'] }}">
<div class="grid gap-5 sm:grid-cols-2"><x-field name="to_contact_id" label="Vendor recipient" type="select" required>@foreach($contacts as $contact)<option value="{{ $contact->id }}" @selected(old('to_contact_id',$defaults['to_contact_id'])==$contact->id)>{{ $contact->name }} · {{ $contact->email }}</option>@endforeach</x-field>
<fieldset><legend class="label">Optional vendor CC</legend>@foreach($contacts as $contact)<label class="mt-3 flex items-start gap-2 text-xs leading-6"><input type="checkbox" name="cc_contact_ids[]" value="{{ $contact->id }}" @checked(in_array($contact->id,old('cc_contact_ids',$defaults['cc_contact_ids']))) class="mt-1 h-4 w-4 shrink-0 accent-accent">{{ $contact->name }}</label>@endforeach</fieldset></div>
<x-field name="subject" label="Exact subject" :value="$defaults['subject']" required maxlength="300" />
<x-field name="body" label="Editable vendor message" :value="$defaults['body']" type="textarea" rows="14" required maxlength="12000" />
@include('lifecycle.documents',['selectedDocuments'=>$defaults['document_ids'],'documentLabel'=>'Explicit vendor-facing attachment subset · nothing is attached automatically'])
<label class="flex items-start gap-3 text-xs leading-6"><input type="checkbox" name="disclosure_confirmed" value="1" @checked(old('disclosure_confirmed')) class="mt-1 h-4 w-4 shrink-0 accent-accent">I reviewed all selected files for vendor disclosure, including client identity and addresses. Internal handoff exports and client commercial quotes are excluded.</label>
<x-field name="reason" label="Preparation / change reason" :value="$defaults['reason']" type="textarea" required maxlength="2000" />
<details class="rounded-xl bg-slate-50 p-4"><summary class="cursor-pointer text-xs font-medium">Deliberate repeat after prior provider acceptance</summary><div class="mt-4 space-y-4"><x-field name="resend_of_id" label="Resolved prior dispatch ID" type="number" min="1" /><label class="flex gap-3 text-xs leading-6"><input type="checkbox" name="resend_confirmed" value="1" class="mt-1 h-4 w-4 shrink-0 accent-accent">I intend a separate repeated vendor message linked to that resolved dispatch. Pending or uncertain sends must be reconciled first.</label></div></details>
<x-button>Save message for exact review</x-button></form>