<x-layout title="Reconfirm rate and capacity."><x-page-header title="Reconfirm rate and capacity." eyebrow="Vendor confirmation" description="Assess actual vendor evidence against the accepted quotation and selected shipment cost."><x-button variant="secondary" :href="route('lifecycle.index',$inquiry)">Decision & handoff</x-button><x-button variant="secondary" :href="route('inquiries.show',$inquiry)">Inquiry</x-button></x-page-header>
<x-inquiry-navigation :inquiry="$inquiry" />@if($inquiry->is_demo)<div class="alert alert-warning mb-6">Fictional business preview · retained evidence describes a simulated shipment.</div>@endif
@if($reasons)<div class="alert alert-warning mb-6"><div><strong>This accepted basis is no longer current.</strong>@foreach($reasons as $reason)<p class="mt-2 text-xs leading-6">{{ $reason }}</p>@endforeach</div></div>@endif
<div class="grid items-start gap-6 xl:grid-cols-2"><div class="min-w-0 space-y-6"><section class="panel panel-pad"><h2 class="section-title">{{ $request->selection->snapshot['vendor']['name'] }}</h2><p class="hint">Client acceptance #{{ $request->client_decision_id }} · quote r{{ $request->decision->revision->number }} · shipment v{{ $request->version->number }}</p><div class="mt-5 grid gap-5 sm:grid-cols-2"><div><p class="eyebrow">Selected vendor rate</p><p class="mt-2 text-2xl font-semibold tracking-tight">{{ $request->selection->revision->currency }} {{ \App\Support\OfferCosts::money($request->selection->revision->complete_total,$request->selection->revision->currency) }}</p></div><div><p class="eyebrow">Current vendor review</p><p class="mt-2 text-lg font-medium">{{ ucfirst($current?->status??'Pending') }}</p></div></div>
<a class="text-link mt-5 block text-xs" href="{{ route('offers.selection',[$inquiry,$request->selection]) }}">Exact cost basis, charges and evidence →</a><a class="text-link mt-4 block text-xs" href="{{ route('lifecycle.decision',[$inquiry,$request->decision->revision]) }}">Accepted client terms →</a>
@php($s=$request->selection->snapshot['shipment']['shipment'])<dl class="mt-6 space-y-4">@foreach(['mode'=>'Mode','scope'=>'Scope','origin_location'=>'Origin','destination_location'=>'Destination','cargo_ready_date'=>'Cargo ready','arrival_date'=>'Requested arrival'] as $key=>$label)<div class="flex flex-wrap justify-between gap-3 border-b border-slate-100 pb-3 text-xs"><dt class="text-slate-500">{{ $label }}</dt><dd>{{ $s[$key]??'Not stated' }}</dd></div>@endforeach</dl></section>
@if($message)<section class="panel panel-pad"><h2 class="section-title">Original vendor response</h2><a class="text-link mt-4 block text-xs" href="{{ route('mail.message',$message) }}">Match and classification review →</a><pre class="mt-4 whitespace-pre-wrap break-words rounded-xl bg-slate-50 p-4 font-sans text-sm leading-7">{{ $message->text() }}</pre></section>@endif
<details class="panel panel-pad"><summary class="text-sm font-medium">Earlier vendor confirmations</summary><h2 class="section-title mt-5">Confirmation history</h2>@forelse($history as $v)<article class="mt-5 border-t border-slate-100 pt-5"><span class="badge {{ $v->status==='confirmed'?'badge-active':'badge-warning' }}">{{ ucfirst($v->status) }} · v{{ $v->number }}</span><p class="hint">Actual confirmation {{ \App\Support\Processing::time($v->confirmed_at) }} · {{ $v->reviewer->name }}</p><p class="mt-3 whitespace-pre-line break-words text-sm leading-7">{{ $v->snapshot['data']['notes'] }}</p>@foreach(array_merge($v->snapshot['differences'],$v->snapshot['review_gaps']) as $reason)<p class="hint text-amber-800">{{ $reason }}</p>@endforeach</article>@empty<p class="hint">No reviewed rate/capacity evidence. An acknowledgement does not confirm availability.</p>@endforelse</details></div>
<div class="min-w-0 space-y-6"><section class="panel panel-pad"><h2 class="section-title">Review actual vendor evidence</h2><form data-unsaved data-guided-form data-guide-save="Save confirmation review" class="mt-5 space-y-5" method="POST" action="{{ route('lifecycle.vendor.save',[$inquiry,$request]) }}">@csrf<input type="hidden" name="action_key" value="{{ old('action_key',\Illuminate\Support\Str::uuid()) }}"><input type="hidden" name="expected_revision" value="{{ $request->current_number }}"><input type="hidden" name="mail_message_id" value="{{ $message?->id }}">
<x-form-guide :steps="['reply'=>'Vendor reply','rate'=>'Price & dates','confirm'=>'Check & record']" /><div data-form-step="reply" class="grid gap-5 sm:grid-cols-2"><x-field name="status" label="What did the vendor confirm?" type="select">@foreach(['pending','confirmed','conditional','changed','unavailable'] as $key)<option @selected(old('status','pending')===$key)>{{ $key }}</option>@endforeach</x-field><x-field name="channel" label="Evidence channel" type="select">@foreach(['email','phone','whatsapp','meeting','other'] as $key)<option @selected(old('channel',$message?'email':'phone')===$key)>{{ $key }}</option>@endforeach</x-field>
<x-field name="contact_id" label="Authorized vendor contact" type="select"><option value="">Identity needs review</option>@foreach($contacts as $contact)<option value="{{ $contact->id }}" @selected(old('contact_id')==$contact->id)>{{ $contact->name }} · {{ $contact->email }}</option>@endforeach</x-field>
<x-field name="confirmed_at" label="Actual confirmation time" type="datetime-local" step="1" :value="now($company->timezone)->format('Y-m-d\TH:i:s')" required :hint="$company->timezone" />
</div><div data-form-step="rate" class="grid gap-5 sm:grid-cols-2"><x-field name="rate_total" label="Actual vendor complete rate" inputmode="decimal" hint="Record evidence; this field does not change the selected offer." />
<x-field name="currency" label="Vendor currency" maxlength="3" :value="$request->selection->revision->currency" />
<x-field name="available_date" label="Available cargo / pickup date" type="date" />
<x-field name="arrival_date" label="Confirmed arrival · when stated" type="date" />
<x-field name="expires_at" label="Vendor confirmation expiry · when supplied" type="datetime-local" :hint="$company->timezone.' · optional, never invented'" /></div>
<div data-form-step="confirm" class="space-y-5">@foreach(['identity_confirmed'=>'I verified the vendor contact and their authority.','rate_agreed'=>'Vendor expressly agrees to the exact selected rate and charges.','scope_agreed'=>'Vendor expressly agrees to the accepted service scope and conditions.','capacity_confirmed'=>'Vendor confirmed actual equipment / capacity availability.','dates_agreed'=>'Vendor agrees to the confirmed shipment dates.'] as $key=>$text)<label class="flex items-start gap-3 text-xs leading-6"><input type="checkbox" name="{{ $key }}" value="1" @checked(old($key)) class="mt-1 h-4 w-4 shrink-0 accent-accent">{{ $text }}</label>@endforeach
<x-field name="conditions" label="Outstanding conditions · blank only if none" type="textarea" maxlength="4000" /><x-field name="notes" label="Actual evidence / difference and review reason" type="textarea" required maxlength="8000" rows="5" />@include('lifecycle.documents')
<p class="hint">Changed prices/dates block release. Review the vendor offer and shipment, then issue a new client quotation and obtain renewed acceptance.</p><x-button class="w-full">Record vendor confirmation review</x-button></div></form></section>
<section class="panel panel-pad"><h2 class="section-title">Reconfirmation message</h2><p class="hint">This asks for rate and capacity confirmation. Saving or accepting never sends automatically.</p>@foreach($messages as $op)<a class="text-link mt-4 block text-xs" href="{{ route('lifecycle.message',[$inquiry,$op]) }}">Reconfirmation message v{{ $op->number }} · {{ $op->approval?'Approved':'Needs approval' }} →</a>@endforeach
<details class="mt-5"><summary class="cursor-pointer text-sm font-medium">Prepare / revise vendor message</summary>@include('lifecycle.message-form',['parent'=>$request,'kind'=>'reconfirmation'])</details></section></div></div></x-layout>
