<x-layout title="Client quotation workbench">
@include('quotations.header',['heading'=>'Prepare customer quote'])
@if(!$p)<section class="panel"><x-empty title="Select a vendor cost basis first" description="Review the required services, costs, currency, tax and validity in the vendor comparison. A final eligible selection unlocks client quotation approval." icon="file-text" /><div class="px-6 pb-6"><x-button :href="route('offers.index',$inquiry)">Review vendor offers</x-button></div></section>
@else
@php($basis=$selection->snapshot)
<div class="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_340px]">
<form data-guided-form data-guide-intent="draft" data-unsaved method="POST" action="{{ route('quotations.save',$inquiry) }}" class="min-w-0 space-y-6">@csrf<input type="hidden" name="expected_revision" value="{{ old('expected_revision',$quote?->current_number??0) }}">
<x-form-guide :steps="['cost'=>'Vendor cost','price'=>'Price & tax','terms'=>'Customer terms','email'=>'Email & save']" /><section data-form-step="cost" class="panel panel-pad"><p class="eyebrow">Selected vendor offer</p><h2 class="section-title mt-3">What will the selected vendor charge?</h2>
<x-field name="offer_selection_id" label="Selected vendor offer" type="select" required class="mt-4">@foreach($selections as $item)<option value="{{ $item->id }}" @selected((int)old('offer_selection_id',$selection->id)===$item->id)>Selection #{{ $item->id }} · {{ ucfirst($item->kind) }} · {{ $item->snapshot['vendor']['name'] }}{{ $item->superseded_at?' · superseded':'' }}</option>@endforeach</x-field>
<p class="hint">Changing the selection explicitly creates a new quotation revision. Save a draft after switching to inspect its source lines before review. Existing prices are never refreshed silently.</p><a class="text-link mt-4 inline-block text-xs" href="{{ route('offers.selection',[$inquiry,$selection]) }}">Inspect exact cost basis →</a>
<div class="mt-5 space-y-4">@foreach($basis['calculation']['lines'] as $line)@if(!$line['optional'] && $line['state']==='priced')
<article class="rounded-xl border border-slate-200 p-4"><p class="text-xs font-medium">{{ $line['description'] }}</p><p class="hint">{{ $line['currency'] }} {{ $line['subtotal']??'Unknown' }} · {{ \App\Support\OfferCosts::BASES[$line['basis']] }} · quantity {{ isset($line['billed_quantity'])?\Brick\Math\BigDecimal::of($line['billed_quantity'])->strippedOfTrailingZeros():'Unresolved' }} · vendor tax {{ $line['tax_treatment'] }}</p>
<x-field :name="'descriptions['.$line['key'].']'" label="Customer service description" :value="$p['descriptions'][$line['key']]??''" maxlength="500" class="mt-3" hint="Only this selling description appears in the customer quotation." />
@if($line['tax_treatment']==='inclusive')<x-field :name="'vendor_tax_rates['.$line['key'].']'" label="Confirmed embedded vendor tax %" :value="$p['vendor_tax_rates'][$line['key']]??$line['tax_rate']??''" inputmode="decimal" class="mt-3" hint="Explicit stated rate, including a confirmed zero. Evidence is required below." />@endif
</article>@endif @endforeach</div>
</section>
<section data-form-step="price" class="panel panel-pad"><p class="eyebrow">Your selling price</p><h2 class="section-title mt-3">Markup and stated tax</h2><div class="mt-5 grid gap-5 sm:grid-cols-2">
<x-field name="markup_percent" label="Percentage to add to vendor cost" :value="$p['markup_percent']" inputmode="decimal" hint="0–1000%. Excludes vendor tax and optional charges." />
<x-field name="vendor_tax_handling" label="Vendor tax treatment" type="select">@foreach(['unknown'=>'Awaiting review','recoverable'=>'Staff confirms recoverable / no vendor tax','pass_through'=>'Nonrecoverable · pass through without markup'] as $value=>$label)<option value="{{ $value }}" @selected(old('vendor_tax_handling',$p['vendor_tax_handling'])===$value)>{{ $label }}</option>@endforeach</x-field>
<x-field name="vendor_tax_evidence" label="Vendor tax evidence / staff determination" type="textarea" :value="$p['vendor_tax_evidence']" maxlength="2000" />
<x-field name="tax_charge_description" label="Customer description for any tax pass-through" :value="$p['tax_charge_description']" maxlength="500" hint="Required only when a nonzero tax-related charge passes through." />
<x-field name="customer_tax_treatment" label="Customer tax treatment" type="select">@foreach(['unknown'=>'Awaiting review','none'=>'No customer tax · confirmed by staff','exclusive'=>'Stated percentage added separately'] as $value=>$label)<option value="{{ $value }}" @selected(old('customer_tax_treatment',$p['customer_tax_treatment'])===$value)>{{ $label }}</option>@endforeach</x-field>
<x-field name="customer_tax_rate" label="Stated customer tax %" :value="$p['customer_tax_rate']" inputmode="decimal" hint="0–100%. Tax is calculated on the selling subtotal plus any unmarked charge." />
<x-field name="customer_tax_evidence" label="Customer tax basis / evidence" type="textarea" :value="$p['customer_tax_evidence']" maxlength="2000" />
</div><label class="mt-5 flex items-start gap-3 text-xs leading-6"><input id="markup-confirmed" name="markup_confirmed" type="checkbox" value="1" @checked(old('markup_confirmed')) class="mt-1 h-4 w-4 shrink-0 accent-accent">I explicitly confirm this percentage markup and the resulting customer price.</label>
<p class="hint">Markup applies to cost. Gross margin is estimated profit divided by the selling subtotal. This is potential profit, not realized revenue.</p>
</section>
<section data-form-step="terms" class="panel panel-pad"><p class="eyebrow">Customer quotation details</p><h2 class="section-title mt-3">Who receives the quote, and what does it include?</h2><div class="mt-5 grid gap-5 sm:grid-cols-2">
<x-field name="issue_date" label="Issue date" type="date" :value="$p['issue_date']" required />
<x-field name="valid_until" label="Client valid until" type="datetime-local" :value="$p['valid_until']" :hint="'Local time · '.$company->timezone.'. Must not exceed vendor validity. A date-only entry expires at 23:59:59 local time.'" />
<x-field name="to_contact_id" label="To · authorized client contact" type="select"><option value="">Select client contact</option>@foreach($contacts as $contact)<option value="{{ $contact->id }}" @selected((int)old('to_contact_id',$p['to_contact_id'])===$contact->id)>{{ $contact->name }} · {{ $contact->email }}</option>@endforeach</x-field>
<fieldset><legend class="label">CC · same client contacts</legend>@forelse($contacts as $contact)<label class="mt-2 flex items-start gap-2 text-xs leading-6"><input type="checkbox" name="cc_contact_ids[]" value="{{ $contact->id }}" @checked(in_array($contact->id,old('cc_contact_ids',$p['cc_contact_ids']??[]))) class="mt-1 h-4 w-4 shrink-0 accent-accent"><span class="break-all">{{ $contact->name }} · {{ $contact->email }}</span></label>@empty<p class="hint">Create an active client contact to authorize recipients.</p>@endforelse</fieldset>
</div><div class="mt-5 space-y-5"><x-field name="inclusions" label="Customer inclusions" type="textarea" :value="$p['inclusions']" maxlength="4000" /><x-field name="exclusions" label="Customer exclusions" type="textarea" :value="$p['exclusions']" maxlength="4000" /><x-field name="conditions" label="Staff-confirmed commercial conditions" type="textarea" :value="$p['conditions']" maxlength="12000" hint="State payment, capacity and estimated timing conditions. Do not promise unconfirmed operational dates." /></div>
<label class="mt-5 flex items-start gap-3 text-xs leading-6"><input id="terms-confirmed" name="terms_confirmed" type="checkbox" value="1" @checked(old('terms_confirmed')) class="mt-1 h-4 w-4 shrink-0 accent-accent">I reviewed and confirmed the customer scope, validity, tax treatment, inclusions, exclusions and conditions against the source.</label>
<details class="mt-6"><summary class="cursor-pointer text-sm font-medium">Optional customer services · excluded from total</summary><p class="hint">Enter an explicit customer price. Selecting an option requires a revised quote covering scope and tax; it is never added automatically.</p><div class="mt-4 space-y-4">@for($i=0;$i<max(3,count($p['optional_lines']??[]));$i++)<div class="grid gap-3 rounded-xl bg-slate-50 p-4 sm:grid-cols-[minmax(0,1fr)_130px]"><x-field :name="'optional_lines['.$i.'][description]'" :label="'Optional service '.($i+1)" :value="$p['optional_lines'][$i]['description']??''" maxlength="500" /><x-field :name="'optional_lines['.$i.'][amount]'" label="Selling price" :value="$p['optional_lines'][$i]['amount']??''" inputmode="decimal" /></div>@endfor</div></details>
</section>
<section data-form-step="email" class="panel panel-pad"><h2 class="section-title">Check the email and save</h2><div class="mt-5 space-y-5"><x-field name="subject" label="Email subject" :value="$p['subject']" maxlength="300" /><x-field name="body" label="Editable email body" type="textarea" :value="$p['body']" rows="8" maxlength="12000" hint="Reference, exact deadline, total and reply instructions are appended from this revision. No AI is required." /><x-field name="internal_notes" label="Internal notes · never included in PDF or email" type="textarea" :value="$p['internal_notes']" maxlength="4000" /><x-field name="change_reason" label="Reason for this revision" :value="$revision?'':'Initial client pricing proposal'" required maxlength="2000" /></div>
@if($dispatches->count())<details class="mt-5"><summary class="cursor-pointer text-xs font-medium">Deliberate resend authorization</summary><div class="mt-4"><x-field name="resend_of_id" label="Link earlier resolved quotation dispatch" type="select"><option value="">No resend</option>@foreach($dispatches as $d)<option value="{{ $d->id }}" @selected((int)old('resend_of_id',$revision?->resend_of_id)===$d->id)>#{{ $d->id }} · {{ $d->label() }}</option>@endforeach</x-field><label class="mt-4 flex gap-3 text-xs leading-6"><input type="checkbox" name="resend_confirmed" value="1" class="mt-1 h-4 w-4 shrink-0 accent-accent">I deliberately authorize a new quotation revision for resend and explain why above. Pending or uncertain outcomes must be reconciled first.</label></div></details>@endif
<div class="mt-6 flex flex-wrap gap-3"><x-button name="intent" value="draft" variant="secondary">Save draft</x-button><x-button name="intent" value="review">Save for review</x-button></div><p class="hint">Save creates a new immutable revision and PDF. Review, approval and sending are separate steps.</p></section></form>
<aside class="min-w-0 space-y-6 xl:sticky xl:top-6">
<section class="panel panel-pad"><p class="eyebrow">Last saved customer price</p><p class="mt-3 break-words text-4xl font-semibold tracking-tight">{{ $revision?$revision->pricing['currency']: $basis['comparison']['currency'] }} {{ $revision?->pricing['total']??'—' }}</p><p class="hint">{{ $revision?'Revision '.$revision->number.' · '.$revision->label():'Save to calculate and preview exact server prices.' }}</p>@if($revision)<div class="mt-5 flex flex-wrap gap-3"><x-button :href="route('quotations.review',[$inquiry,$revision])">Review and approve</x-button><x-button variant="secondary" :href="route('quotations.pdf',[$inquiry,$revision])" target="_blank">PDF</x-button></div>@endif</section>
@if($revision)<details class="panel panel-pad"><summary class="text-sm font-medium">Internal cost & estimated profit</summary><p class="eyebrow mt-5">Private · estimated economics</p><dl class="mt-4 space-y-3 text-xs">@foreach(['cost_subtotal'=>'Eligible cost subtotal','vendor_tax'=>'Vendor tax · excluded from markup','markup_percent'=>'Markup %','markup_amount'=>'Markup amount','selling_subtotal'=>'Selling subtotal','vendor_tax_pass_through'=>'Unmarked tax-related charge','customer_tax'=>'Stated customer tax','estimated_profit'=>'Estimated gross profit','gross_margin_percent'=>'Estimated gross margin %'] as $key=>$label)<div class="flex justify-between gap-3"><dt class="text-slate-500">{{ $label }}</dt><dd class="shrink-0 font-medium">{{ $revision->pricing[$key]??'Unresolved' }}</dd></div>@endforeach</dl><p class="hint">{{ $revision->pricing['rounding'] }}</p></details>
<section class="panel panel-pad"><h2 class="section-title">Readiness</h2>@forelse($reasons as $reason)<p class="mt-3 text-xs leading-6 text-[#855600]">{{ $reason }}</p>@empty<p class="mt-3 text-xs leading-6 text-[#28734b]">Commercial checks passed. Review the exact PDF and actual sender before approval.</p>@endforelse</section>@endif
@if($quote)<details class="panel panel-pad"><summary class="text-sm font-medium">Earlier quotation versions</summary><h2 class="section-title mt-5">Revision history</h2><div class="attention-list" role="region" tabindex="0" aria-label="Quotation revision history">@foreach($quote->revisions as $version)<a class="mt-4 block rounded-xl bg-slate-50 p-4 text-xs leading-6" href="{{ route('quotations.review',[$inquiry,$version]) }}"><strong>Revision {{ $version->number }}</strong> · {{ $version->label() }}<br>{{ $version->author_name }} · {{ \App\Support\Processing::time($version->created_at) }}<br>{{ $version->change_reason }}</a>@endforeach</div></details>@endif
</aside></div>@endif</x-layout>
