<x-layout title="Exact quotation review">
@include('quotations.header',['heading'=>'Review every detail.'])
@php($p=$revision->payload) @php($pricing=$revision->pricing)
<div class="mb-6 flex flex-wrap items-center gap-3"><span class="badge tint-blue">{{ $revision->quotation->reference }} · revision {{ $revision->number }}</span><span class="badge badge-inactive">{{ $revision->label() }}</span><x-button variant="secondary" :href="route('quotations.index',$inquiry)">Pricing workbench</x-button><x-button variant="secondary" :href="route('quotations.pdf',[$inquiry,$revision])" target="_blank">Open PDF</x-button><x-button variant="secondary" :href="route('quotations.pdf',[$inquiry,$revision]).'?download=1'">Download PDF</x-button></div>
<div class="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_340px]"><div class="min-w-0 space-y-6">
<section class="panel panel-pad"><p class="eyebrow">Customer quotation · exact saved document</p><div class="mt-4 flex flex-wrap items-end justify-between gap-5"><h2 class="text-4xl font-semibold tracking-tight">{{ $pricing['currency'] }} {{ $pricing['total']??'Unresolved' }}</h2><p class="text-xs leading-6 text-slate-500">Valid until {{ \App\Support\Processing::time($revision->expires_at) }}<br>Optional services excluded</p></div>
<iframe title="Exact saved customer quotation PDF" src="{{ route('quotations.pdf',[$inquiry,$revision]) }}" class="mt-6 h-[680px] w-full rounded-xl border border-slate-200 bg-slate-100"></iframe><p class="hint">If your browser cannot display the PDF, use Open PDF or Download. These links return the same frozen bytes.</p>
<p class="mt-4 break-all text-[10px] leading-5 text-slate-500">PDF version {{ $revision->number }} · {{ number_format($revision->pdf_size/1024,1) }} KB · SHA-256 {{ $revision->pdf_checksum }}</p>
</section>
<section class="panel panel-pad"><h2 class="section-title">Exact customer email</h2><dl class="mt-5 space-y-3 text-xs leading-6"><div><dt class="eyebrow">To</dt><dd class="break-all">{{ $mail['to']['name']??'Unresolved' }} &lt;{{ $mail['to']['email']??'' }}&gt;</dd></div><div><dt class="eyebrow">CC</dt><dd class="break-all">@forelse($mail['cc'] as $recipient){{ $recipient['name'] }} &lt;{{ $recipient['email'] }}&gt;{{ $loop->last?'':', ' }}@empty None @endforelse</dd></div><div><dt class="eyebrow">Subject</dt><dd class="break-words">{{ $mail['subject'] }}</dd></div></dl><pre tabindex="0" aria-label="Exact customer email body" class="mt-5 whitespace-pre-wrap break-words rounded-xl bg-slate-50 p-5 font-sans text-xs leading-7">{{ $mail['body'] }}</pre><p class="hint">Exactly one attachment: {{ $mail['manifest'][0]['name'] }}. Original vendor quotes and internal files are excluded.</p></section>
@if($snapshot || $approval)@php($actual=$snapshot??$approval->snapshot)<section class="panel panel-pad"><h2 class="section-title">Actual sending identity</h2><dl class="mt-5 grid gap-5 sm:grid-cols-2">@foreach(['from'=>'From','sender'=>'Actual sender','reply_to'=>'Reply-To'] as $key=>$label)<div><dt class="eyebrow">{{ $label }}</dt><dd class="mt-2 break-all text-xs leading-6">{{ $actual['envelope'][$key]['name']??'' }} &lt;{{ $actual['envelope'][$key]['email'] }}&gt;</dd></div>@endforeach<div><dt class="eyebrow">Transport</dt><dd class="mt-2 text-xs">{{ ($actual['envelope']['provider']??'outlook')==='gmail'?'Gmail':'Outlook' }} · {{ $actual['envelope']['is_demo']?'Fictional fixture · no real mail':'Connected company mailbox' }}</dd></div></dl></section>@endif
<section class="panel panel-pad"><h2 class="section-title">Revision & evidence timeline</h2>@foreach($revision->quotation->revisions as $item)<a href="{{ route('quotations.review',[$inquiry,$item]) }}" class="mt-4 block rounded-xl border border-slate-200 p-4 text-xs leading-6"><strong>Revision {{ $item->number }}</strong> · {{ $item->label() }}<br>{{ $item->author_name }} · {{ \App\Support\Processing::time($item->created_at) }}<br>{{ $item->change_reason }}@if($item->resend_of_id)<br>Deliberate resend linked to dispatch #{{ $item->resend_of_id }}@endif</a>@endforeach</section>
</div><aside class="min-w-0 space-y-6">
<section class="panel panel-pad"><p class="eyebrow">Private · reviewed pricing</p><dl class="mt-5 space-y-3 text-xs">@foreach(['cost_subtotal'=>'Eligible cost','vendor_tax'=>'Vendor tax','markup_percent'=>'Markup %','markup_amount'=>'Markup amount','selling_subtotal'=>'Selling subtotal','customer_tax'=>'Customer tax','estimated_profit'=>'Estimated gross profit','gross_margin_percent'=>'Estimated gross margin %'] as $key=>$label)<div class="flex justify-between gap-3"><dt class="text-slate-500">{{ $label }}</dt><dd class="shrink-0 font-medium">{{ $pricing[$key]??'Unresolved' }}</dd></div>@endforeach</dl><a class="text-link mt-5 block text-xs" href="{{ route('offers.selection',[$inquiry,$revision->selection]) }}">Exact source selection #{{ $revision->offer_selection_id }} →</a><p class="hint">Vendor tax and optional services receive no percentage markup. Profit is estimated before other company expenses.</p></section>
<section class="panel panel-pad"><h2 class="section-title">{{ $approval?'Exact approval recorded':'Approval readiness' }}</h2>@if($approval)<p class="mt-4 text-xs leading-6">{{ $approval->reviewer_name }} · {{ \App\Support\Processing::time($approval->approved_at) }}</p><p class="mt-3 break-all text-[10px] leading-5 text-slate-500">{{ $approval->digest }}</p>@endif
@forelse($reasons as $reason)<p class="mt-3 text-xs leading-6 text-[#855600]">{{ $reason }}</p>@empty<p class="mt-3 text-xs leading-6 text-[#28734b]">Current commercial, file and sender checks passed.</p>@endforelse
@if(!$approval && $snapshot)<form method="POST" class="mt-5 space-y-5" action="{{ route('quotations.approve',[$inquiry,$revision]) }}">@csrf<input type="hidden" name="digest" value="{{ \App\Support\Processing::hash($snapshot) }}"><label class="flex items-start gap-3 text-xs leading-6"><input id="approve-exact" name="approve_exact" type="checkbox" value="1" required class="mt-1 h-4 w-4 shrink-0 accent-accent">I reviewed this exact pricing, PDF bytes, customer terms, email, recipients, attachment checksum, actual sender and Reply-To. I approve and authorize this exact revision.</label><x-button class="w-full">Approve exact quotation</x-button></form>@endif
@if($approval && !$manual)<x-button class="mt-5 w-full" :href="route('mail.preview',['client_quote',$approval->id])">Send approved quotation</x-button><p class="hint">Opens the shared outbox release screen. Explicit enqueue is still required; approval alone sends nothing.</p>@endif
@if($reasons && !$snapshot)<p class="hint">Draft and PDF review remain available. Resolve the checklist; Admin can configure the mailbox before exact sender approval.</p>@endif
@if($manual)<p class="mt-5 text-xs leading-6">Manual communication declared {{ \App\Support\Processing::time(\Carbon\CarbonImmutable::parse($manual->recorded_at)) }}. No provider delivery is claimed. This approval cannot be enqueued.</p>@endif</section>
@if($approval && !$manual && !$reasons)<details class="panel panel-pad"><summary class="cursor-pointer text-xs font-medium">Record communication outside LRS</summary><p class="hint">Only record an actual manual send. This prevents this approval from being released later through the outbox.</p><form method="POST" action="{{ route('quotations.manual',[$inquiry,$revision]) }}" class="mt-4 space-y-4">@csrf<x-field name="reason" label="Manual communication evidence" required maxlength="2000" /><label class="flex gap-3 text-xs leading-6"><input type="checkbox" name="confirm" value="1" required class="mt-1 h-4 w-4 shrink-0 accent-accent">I confirm this exact quotation was communicated manually.</label><x-button variant="secondary">Record manual send</x-button></form></details>@endif
@if($approval)<x-followup-panel kind="client_quote" :approval="$approval" />@endif
</aside></div></x-layout>
