
<section class="panel panel-pad mb-6">
<div class="flex flex-wrap items-center justify-between gap-4"><div><h2 class="section-title">Company connections</h2><p class="hint">One workspace for every incoming source. New outgoing work uses the selected default; approved work keeps its authorized mailbox.</p></div><span class="badge tint-blue">{{ $connections->count() }} connections</span></div>
<div class="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">
@foreach($connections as $item)<a class="rounded-2xl border p-5 transition {{ $item->id===$connection->id?'border-blue-300 bg-blue-50/50':'border-slate-200 hover:bg-slate-50' }}" href="{{ route('settings.mailbox',['connection'=>$item->id]) }}" @if($item->id===$connection->id) aria-current="page" @endif>
<div class="flex flex-wrap gap-2"><span class="badge {{ $item->provider==='gmail'?'tint-red':'tint-blue' }}">{{ $item->provider==='gmail'?'Gmail':'Outlook' }}</span>@if($outbound->id===$item->id)<span class="badge tint-green">Outbound default</span>@endif @if($item->is_demo)<span class="badge badge-warning">Fictional</span>@endif</div>
<p class="mt-4 break-all text-sm font-medium">{{ $item->target_email?:'Configure mailbox' }}</p><p class="mt-2 text-xs text-slate-500">{{ ucfirst($item->state) }} · Incoming {{ $item->incoming_enabled?'enabled':'paused' }}</p>
</a>@endforeach</div>
<details class="mt-6"><summary class="cursor-pointer text-sm text-accent">Add a company connection</summary><form method="POST" action="{{ route('settings.mailbox.store') }}" class="mt-5 grid items-end gap-5 sm:grid-cols-2 xl:grid-cols-[1fr_1fr_1fr_auto]">@csrf<x-field name="provider" label="Email provider" type="select"><option value="gmail">Gmail · Google account</option><option value="outlook">Outlook · Microsoft 365</option></x-field><x-field name="name" label="Company From name" required maxlength="120" /><x-field name="email" label="Account email" type="email" required maxlength="254" /><x-button>Add connection</x-button></form><p class="hint mt-4">Adding or connecting an account sends nothing. Gmail requires its own Google account; aliases are sending identities within that account.</p></details>
</section>
