
<section class="panel panel-pad"><h2 class="section-title">Authorized Google identity</h2><p class="hint">Use the mailbox's own Google account. Saving material changes disconnects access and invalidates earlier sender authorization. Existing approved quotations need a new reviewed revision if their envelope changes.</p>
<form method="POST" action="{{ route('settings.gmail.update',$connection) }}" class="mt-6 space-y-5" data-unsaved>@csrf @method('PATCH')
<div class="grid gap-5 sm:grid-cols-2"><x-field name="account_email" label="Expected Google account email" type="email" :value="$connection->is_demo?'':$connection->account_email" required maxlength="254" /><x-field name="target_name" label="Company From name" :value="$connection->is_demo?'':$connection->target_name" required maxlength="120" />
<x-field name="from_alias" label="Approved From address" type="email" :value="$connection->is_demo?'':($connection->from_alias?:$connection->account_email)" maxlength="254" hint="The account address or an existing verified send-as alias. LRS does not create aliases." />
<x-field name="transport_limit_mb" label="Message limit · MiB" type="number" :value="$connection->transport_limit?min(33,floor($connection->transport_limit/1024/1024)):25" required min="1" max="33" hint="Exact MIME must also fit Gmail's upload and attachment limits. Recipient limits may be lower." /><x-field name="import_from" label="Import messages from" type="datetime-local" :value="\App\Support\InquiryWorkflow::local($connection->import_from??now())" required hint="Explicit boundary within the last 90 days. Historical import sends nothing." /></div>
<label class="flex items-start gap-3 text-xs leading-6"><input class="mt-1 h-4 w-4 accent-accent" type="checkbox" name="rights_confirmed" value="1" required>I administer this company mailbox and verified its own Google account, permitted From identity and message limit.</label><x-button>Save Google configuration</x-button></form>
@if($connection->aliases)<div class="mt-6 border-t border-slate-100 pt-5"><h3 class="text-sm font-medium">Available sending identities</h3><p class="hint">Read from {{ $connection->is_demo?'local fixture':'Google' }} · {{ \App\Support\Processing::time($connection->aliases_checked_at) }}. The approved From address is checked again before submission.</p><div class="mt-4 space-y-3">@foreach($connection->aliases as $alias)<div class="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-slate-50 p-4"><span class="break-all text-xs">{{ $alias['sendAsEmail'] }}</span><span class="badge {{ ($alias['verificationStatus']??'')==='accepted'?'tint-green':'badge-warning' }}">{{ ($alias['verificationStatus']??'')==='accepted'?'Verified':'Awaiting verification' }}</span></div>@endforeach</div></div>@endif
</section>
