<x-layout title="Email connections">
<x-page-header title="Connected mail. One workspace." eyebrow="Administration · Email connections" description="Bring company email into the inquiry workspace. Outgoing mail always needs exact approval, sender authorization and an explicit send request."><x-button variant="secondary" :href="route('mail.index')">Open email workspace</x-button></x-page-header>
@include("mailbox.connections")
@if($connection->is_demo)<div class="alert alert-warning mb-6"><x-icon name="warning-circle" /><div><strong>Synthetic fixture connection</strong><p class="mt-1">This transport uses local test data. It never contacts an email provider or sends a real message. Website submissions remain separate real intake.</p></div></div>@elseif(!$configured)<div class="alert alert-warning mb-6"><x-icon name="warning-circle" /><div><strong>{{ $connection->provider==="gmail"?"Google":"Microsoft" }} app configuration needed</strong><p class="mt-1">Set the required application ID and server secret, then register the callback below. Manual inquiries, website intake and RFQ approval remain available.</p></div></div>@endif
<div class="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_340px]"><div class="min-w-0 space-y-6">
<section class="panel panel-pad"><div class="flex flex-wrap items-center justify-between gap-3"><h2 class="section-title">{{ $connection->provider==="gmail"?"Gmail":"Outlook" }} connection status</h2><span class="badge {{ $connection->usable()?'tint-green':'badge-warning' }}">{{ ucfirst($connection->state) }}{{ $connection->is_demo?' · fixture':'' }}</span></div><dl class="mt-6 grid gap-6 sm:grid-cols-2">@foreach(['target_email'=>'Company mailbox','account_email'=>'Authorized account','target_name'=>'From display name'] as $key=>$label)<div><dt class="eyebrow">{{ $label }}</dt><dd class="mt-2 break-all text-sm">{{ $connection->$key?:'Not configured' }}</dd></div>@endforeach<div><dt class="eyebrow">Send identity</dt><dd class="mt-2 text-sm">{{ $connection->send_mode==='on_behalf'?'Account on behalf of company mailbox':'Send As company mailbox' }}</dd></div><div><dt class="eyebrow">Last successful sync</dt><dd class="mt-2 text-sm">{{ \App\Support\Processing::time($connection->last_sync_at) }}</dd></div><div><dt class="eyebrow">Import from</dt><dd class="mt-2 text-sm">{{ \App\Support\Processing::time($connection->import_from) }}</dd></div><div><dt class="eyebrow">Approved From address</dt><dd class="mt-2 break-all text-sm">{{ $connection->from_alias?:$connection->target_email }}</dd></div><div><dt class="eyebrow">Routing</dt><dd class="mt-2 text-sm">{{ $outbound->id===$connection->id?"Default outbound for new work":"Incoming / pinned existing work" }} · Incoming {{ $connection->incoming_enabled?"enabled":"paused" }}</dd></div></dl>@if($connection->last_error)<p class="mt-5 rounded-xl bg-amber-50 p-4 text-xs leading-6 text-[#855600]">{{ $connection->last_error }}</p>@endif
<div class="mt-6 flex flex-wrap gap-3">@if($configured && !$connection->is_demo)<form method="POST" action="{{ ($connection->provider==='gmail'?route('settings.gmail.connect',$connection):route('settings.mailbox.connect')) }}">@csrf<input type="hidden" name="connection" value="{{ $connection->id }}"><x-button>{{ $connection->state==='disconnected'?'Connect pinned account':'Reconnect pinned account' }}</x-button></form>@endif
@foreach(($connection->state==='connected'?['sync'=>'Sync selected folders','pause'=>'Pause work']:($connection->state==='paused'?['resume'=>'Resume work']:[]))+($connection->state!=='disconnected'?['disconnect'=>'Disconnect']:[]) as $action=>$label)<form method="POST" action="{{ route('settings.mailbox.action') }}">@csrf<input type="hidden" name="connection" value="{{ $connection->id }}"><input type="hidden" name="action" value="{{ $action }}"><input type="hidden" name="confirm" value="1"><x-button variant="secondary">{{ $label }}</x-button></form>@endforeach@php
$connectionActions = [];
if ($connection->usable() && $outbound->id !== $connection->id) { $connectionActions['default'] = 'Use for new outgoing work'; }
$incomingAction = $connection->incoming_enabled ? 'incoming_disable' : 'incoming_enable';
$connectionActions[$incomingAction] = $connection->incoming_enabled ? 'Pause incoming polling' : 'Enable incoming polling';
if ($connection->provider === 'gmail' && $connection->usable()) { $connectionActions['aliases'] = 'Check verified From identities'; }
@endphp
@foreach($connectionActions as $action=>$label)<form method="POST" action="{{ route('settings.mailbox.action') }}">@csrf<input type="hidden" name="connection" value="{{ $connection->id }}"><input type="hidden" name="action" value="{{ $action }}"><input type="hidden" name="confirm" value="1"><x-button variant="secondary">{{ $label }}</x-button></form>@endforeach</div><p class="mt-4 text-xs leading-6 text-slate-500">Default changes apply to new work. Approved messages and reminder threads remain pinned and need renewed authorization to change their mailbox. Disconnect preserves records and prevents new provider actions. A submission already in flight cannot be recalled. Resuming a paused connection with unchanged configuration retains its approvals. Disconnecting or changing pinned configuration requires renewed authorization.</p></section>
@if($connection->provider==="outlook")<section class="panel panel-pad"><h2 class="section-title">Pin the company identity</h2><p class="mt-3 text-xs leading-6 text-slate-500">Confirm these with your Microsoft 365 administrator. Saving changes disconnects access and invalidates prior sender authorizations. Tokens and the app secret never appear here.</p>
<form method="POST" action="{{ route('settings.mailbox.update') }}" class="mt-6 space-y-6" data-unsaved>@csrf<input type="hidden" name="connection" value="{{ $connection->id }}"> @method('PATCH')
<div class="grid gap-5 sm:grid-cols-2"><x-field name="account_email" label="Expected sign-in email" type="email" :value="$connection->is_demo?'':$connection->account_email" required maxlength="254" /><x-field name="account_id" label="Expected account object ID" :value="$connection->is_demo?'':$connection->account_id" required hint="Entra user object ID · UUID" /><x-field name="target_email" label="Target mailbox email" type="email" :value="$connection->is_demo?'':$connection->target_email" required maxlength="254" /><x-field name="target_id" label="Target mailbox object ID" :value="$connection->is_demo?'':$connection->target_id" required hint="Personal: same as account. Shared: its own object ID." /><x-field name="target_name" label="Company From name" :value="$connection->is_demo?'':$connection->target_name" required maxlength="120" /><x-field name="mailbox_type" label="Mailbox type" type="select"><option value="personal" @selected(old('mailbox_type',$connection->mailbox_type)==='personal')>Personal company mailbox</option><option value="shared" @selected(old('mailbox_type',$connection->mailbox_type)==='shared')>Shared / delegated mailbox</option></x-field><x-field name="send_mode" label="Verified Exchange send right" type="select"><option value="send_as" @selected(old('send_mode',$connection->send_mode)==='send_as')>Send As · company identity</option><option value="on_behalf" @selected(old('send_mode',$connection->send_mode)==='on_behalf')>Send on Behalf · account visible</option></x-field><x-field name="transport_limit_mb" label="Verified tenant message limit · MiB" type="number" :value="$connection->is_demo?'':($connection->transport_limit?$connection->transport_limit/1024/1024:'')" required min="1" max="100" hint="Administrator-confirmed limit. Encoding is included in preflight; recipients may have lower limits." /><x-field name="import_from" label="Import messages from" type="datetime-local" :value="\App\Support\InquiryWorkflow::local($connection->is_demo?now():($connection->import_from??now()))" required hint="Start now or within the last 90 days. No historical message causes an outgoing acknowledgment." /></div>
<label class="flex items-start gap-3 text-xs leading-6"><input type="checkbox" name="account_sent_items" value="1" @checked(old('account_sent_items',$connection->account_sent_items)) class="mt-1 h-4 w-4 accent-accent">Also inspect the authorized account’s Sent Items for shared-mailbox copies. Target Sent Items are always used. Confirm your Exchange copy settings.</label>
<label class="flex items-start gap-3 text-xs leading-6"><input type="checkbox" name="rights_confirmed" value="1" required class="mt-1 h-4 w-4 accent-accent">I verified target mailbox access, Full Access for shared drafts, the chosen Send As / Send on Behalf right, Sent Items behavior and the tenant size limit with our administrator. OAuth consent alone is insufficient.</label><x-button>Save pinned configuration</x-button></form></section>
@else @include("mailbox.gmail-configuration") @endif
<section class="panel panel-pad"><h2 class="section-title">Selected folders & catch-up</h2><p class="mt-3 text-xs leading-6 text-slate-500">{{ $connection->provider==='gmail'?'Selected Gmail labels are incoming; SENT, DRAFT, spam, trash and label-only changes never create cases.':'Inbox is incoming. Sent Items is reconciliation only.' }} Each folder keeps its own durable page and opaque cursor; a provider deletion never deletes a case.</p>
@forelse($folders as $folder)<article class="mt-5 rounded-xl border border-slate-200 p-5"><div class="flex flex-wrap justify-between gap-3"><div><h3 class="text-sm">{{ $folder->name }}</h3><p class="mt-2 text-xs text-slate-500">{{ ucfirst($folder->kind) }} · {{ $folder->enabled?'Enabled':'Paused' }}{{ $folder->identity_hash!==$connection->identity_hash?' · historical identity':'' }}</p></div><span class="badge tint-blue">{{ $folder->page?'Page retained · '.$folder->offset.' processed':($folder->cursor?'Cursor saved':'Initial sync pending') }}</span></div><p class="mt-3 text-xs leading-6">Last sync {{ \App\Support\Processing::time($folder->last_sync_at) }}<br>Boundary {{ \App\Support\Processing::time($folder->import_from) }}</p>@if($folder->last_error)<p class="mt-3 text-xs leading-6 text-[#855600]">{{ $folder->last_error }}</p>@endif
@if($folder->identity_hash===$connection->identity_hash)<details class="mt-4"><summary class="cursor-pointer text-xs text-accent">Recover or pause this folder</summary><form class="mt-4 space-y-4" method="POST" action="{{ route('settings.mailbox.folder-action',$folder) }}">@csrf<input type="hidden" name="connection" value="{{ $connection->id }}"><x-field :name="'action'" :id="'folder-'.$folder->id.'-action'" label="Action" type="select"><option value="{{ $folder->enabled?'disable':'enable' }}">{{ $folder->enabled?'Pause folder':'Resume retained page/cursor' }}</option><option value="resync">Reset cursor · explicit bounded resync</option></x-field><x-field name="import_from" :id="'folder-'.$folder->id.'-import-from'" label="Resync boundary · required for reset" type="datetime-local" :value="\App\Support\InquiryWorkflow::local($folder->import_from)" /><x-field name="reason" :id="'folder-'.$folder->id.'-reason'" label="Recovery reason" required maxlength="2000" /><label class="flex gap-3 text-xs leading-6"><input type="checkbox" name="confirm" value="1" required class="mt-1 h-4 w-4 accent-accent">I reviewed the import interval and any missed window. Original records remain; no historical sends are created.</label><x-button variant="secondary">Record folder action</x-button></form></details>@endif</article>@empty<p class="mt-5 text-sm text-slate-500">No folder has been selected. {{ $connection->provider==='gmail'?'Connecting selects the authorized account Inbox.':'Connecting checks and selects the target Inbox and Sent Items.' }}</p>@endforelse
@if($connection->usable())<details class="mt-6"><summary class="cursor-pointer text-sm text-accent">Select another target folder</summary><form class="mt-5 space-y-4" method="POST" action="{{ route('settings.mailbox.folder') }}">@csrf<input type="hidden" name="connection" value="{{ $connection->id }}"><x-field name="provider_id" label="Exact provider folder / Gmail label ID" required maxlength="512" hint="The configured target mailbox only. Access is checked before selection." /><x-field name="kind" label="Folder purpose" type="select"><option value="incoming">Incoming inquiries / replies</option>@if($connection->provider==="outlook")<option value="sent">Outgoing reconciliation evidence</option>@endif</x-field><label class="flex gap-3 text-xs leading-6"><input type="checkbox" name="confirm" value="1" required class="mt-1 h-4 w-4 accent-accent">Use this selected folder for the stated purpose.</label><x-button variant="secondary">Check & select folder</x-button></form></details>@endif</section>
</div><aside class="min-w-0 space-y-6">@if($connection->provider==="outlook")<section class="panel panel-pad"><span class="metric-icon tint-blue"><x-icon name="file-text" /></span><h2 class="section-title mt-5">Microsoft setup</h2><p class="mt-3 text-xs leading-6">Register a single-tenant Web application. Use a confidential server secret and this exact redirect URI.</p><p class="mt-4 break-all rounded-xl bg-slate-50 p-4 text-xs">{{ config('mailbox.redirect_uri') }}</p><p class="mt-4 text-xs leading-6">Delegated permissions:<br><span class="font-medium">offline_access · User.Read · Mail.ReadWrite · Mail.Send</span><br>Shared adds <span class="font-medium">User.ReadBasic.All · Mail.ReadWrite.Shared · Mail.Send.Shared</span>.</p><p class="mt-4 text-xs leading-6 text-slate-500">Admin consent may be required by your tenant. Access checks verify the pinned account/target and folders; Exchange send rights require administrator confirmation and controlled live verification.</p><a class="text-link mt-4 inline-block text-xs" href="https://learn.microsoft.com/en-us/graph/outlook-send-mail-from-other-user" target="_blank" rel="noopener noreferrer">Microsoft shared-mailbox guidance ↗</a></section>
@else @include("mailbox.gmail-setup") @endif
<section class="panel panel-pad"><h2 class="section-title">Real data intake</h2><p class="mt-3 text-xs leading-6">New website submissions and connected company mail feed the same Needs review workspace. Source labels preserve where each request came from. Existing client matches are suggestions; staff choose identity explicitly.</p><a class="text-link mt-4 inline-block text-xs" href="{{ route('public-inquiries.create') }}">Open website inquiry form →</a><p class="mt-3 text-xs leading-6 text-slate-500">This local URL is not publicly hosted. Provider app registration and company mailbox access must be supplied before real email ingestion.</p></section>
@if(config('mailbox.demo_enabled') && app()->environment('local','testing'))<section class="panel panel-pad border-amber-200"><h2 class="section-title">Local fixture verification</h2><p class="mt-3 text-xs leading-6">Explicit synthetic data for acceptance. This replaces the selected connection identity and invalidates prior release authorization.</p><form method="POST" action="{{ route('settings.mailbox.action') }}" class="mt-5 space-y-4">@csrf<input type="hidden" name="connection" value="{{ $connection->id }}"><input type="hidden" name="action" value="{{ $connection->provider==='gmail'?'gmail_demo':'demo' }}"><label class="flex gap-3 text-xs leading-6"><input type="checkbox" name="confirm" value="1" required class="mt-1 h-4 w-4 accent-accent">Activate an isolated fixture transport. No real mail.</label><x-button variant="secondary">Connect fixture transport</x-button></form>@if($connection->is_demo)<form method="POST" action="{{ route('settings.mailbox.action') }}" class="mt-5">@csrf<input type="hidden" name="connection" value="{{ $connection->id }}"><input type="hidden" name="action" value="{{ $connection->provider==='gmail'?'gmail_fixtures':'fixtures' }}"><input type="hidden" name="confirm" value="1"><x-button variant="secondary">Load synthetic incoming mail</x-button></form>@endif</section>@endif
</aside></div>

@if(config('mailbox.demo_enabled') && app()->environment('local','testing') && $connection->is_demo && $connection->usable())
<section class="panel panel-pad mt-6"><h2 class="section-title">Synthetic follow-up response</h2><p class="hint">Load a fictional question in the exact accepted reminder thread. Import and staff review must stop later stages; no real client is contacted.</p><form method="POST" action="{{ route('settings.mailbox.action') }}" class="mt-5 space-y-5">@csrf<input type="hidden" name="connection" value="{{ $connection->id }}"><input type="hidden" name="action" value="{{ $connection->provider==='gmail'?'gmail_response':'followup_response' }}"><input type="hidden" name="confirm" value="1"><x-field name="plan_id" label="Synthetic plan with an accepted reminder" type="select"><option value="">Select a plan</option>@foreach(\App\Models\FollowupPlan::with('inquiry')->whereHas('inquiry',fn($q)=>$q->where('is_demo',true))->whereHas('stages.envelope',fn($q)=>$q->where('mailbox_connection_id',$connection->id)->where('identity_hash',$connection->identity_hash))->whereHas('stages.envelope.dispatches',fn($q)=>$q->whereIn('status',['accepted','observed']))->get() as $plan)<option value="{{ $plan->id }}">{{ $plan->inquiry->reference }} · {{ $plan->kind }} · plan {{ $plan->id }}</option>@endforeach</x-field><x-button variant="secondary">Import synthetic question</x-button></form></section>
@endif
</x-layout>