<x-layout title="Quotation extraction scope">
@include('offers.header',['heading'=>'Review the extraction scope.','description'=>'Only selected vendor text passages are sent. AI proposes fields; staff review costs and choose the offer.'])
<a class="text-link mb-5 inline-block text-xs" href="{{ route('offers.edit',[$inquiry,$offer]) }}">← Return to commercial review</a>
<div class="grid items-start gap-6 lg:grid-cols-[minmax(0,1.4fr)_minmax(0,1fr)]">
<section class="panel panel-pad"><h2 class="section-title">Selected vendor evidence</h2><form method="GET" class="mt-5 space-y-5">@foreach($catalogue as $source)<label class="block rounded-xl border border-slate-200 p-4 text-xs leading-6"><span class="flex items-start gap-3"><input type="checkbox" name="source_ids[]" value="{{ $source['id'] }}" @checked(in_array($source['id'],array_column($sources,'id'))) class="mt-1 accent-accent">{{ $source['locator'] }}</span><span class="mt-3 block max-h-56 overflow-auto whitespace-pre-wrap break-words">{{ $source['text'] }}</span></label>@endforeach
@if(!$catalogue)<p class="hint">No extracted vendor passages yet. Use local extraction for linked quotation files, or enter commercial information manually.</p>@else<x-button variant="secondary">Refresh selected scope</x-button>@endif</form></section>
<aside class="panel panel-pad"><h2 class="section-title">Optional paid request</h2><dl class="mt-5 space-y-4 text-xs leading-6"><div><dt class="text-slate-500">Purpose / model</dt><dd>Vendor quotation · {{ $settings->model?:'Not selected' }}</dd></div><div><dt class="text-slate-500">Conservative input bound</dt><dd>{{ $bound }} tokens · {{ count($sources) }} passages</dd></div><div><dt class="text-slate-500">Maximum estimated cost</dt><dd>{{ $estimate===null?'Unavailable until rates are configured':'USD '.$estimate }}</dd></div></dl>
@if($reasons)<p class="mt-5 rounded-xl bg-slate-50 p-4 text-xs leading-6">{{ implode(' ',$reasons) }} Manual commercial entry remains available.</p>
@elseif($sources)<form class="mt-5 space-y-5" method="POST" action="{{ route('offers.ai.store',[$inquiry,$offer]) }}">@csrf<input type="hidden" name="expected_revision" value="{{ $revision->number }}"><input type="hidden" name="scope" value="{{ $scope }}">@foreach($sources as $s)<input type="hidden" name="source_ids[]" value="{{ $s['id'] }}">@endforeach<label class="flex items-start gap-3 text-xs leading-6"><input type="checkbox" name="authorize_paid" value="1" required class="mt-1 accent-accent">Authorize one bounded quotation extraction request using these exact passages and the configured budget.</label><label class="flex items-start gap-3 text-xs leading-6"><input type="checkbox" name="retry" value="1" class="mt-1 accent-accent">Explicitly retry a previous failed request, if any.</label><x-field name="retry_reason" label="Retry reason, when applicable" type="textarea" maxlength="2000" /><x-button>Request field proposals</x-button></form>@endif
<p class="hint">No raw PDF, customer invoice, goods value or target budget is included. No email is sent.</p></aside></div>
</x-layout>
