<x-layout title="Capture vendor quotation">
@include('offers.header',['heading'=>'Capture a quotation','description'=>'Keep the original evidence and bind this alternative to the exact vendor request.'])
@if(!$requests->count())<x-empty title="Prepare a vendor request first" description="A quotation needs an approved RFQ revision and confirmed shipment for traceable comparison." :href="route('inquiries.sourcing',$inquiry)" action="Open vendor sourcing"><x-button :href="route('inquiries.sourcing',$inquiry)">Open vendor sourcing</x-button></x-empty>
@else
<div class="grid items-start gap-6 xl:grid-cols-[minmax(0,1.25fr)_minmax(0,1fr)]">
<form class="panel panel-pad space-y-6" data-unsaved data-guided-form data-guide-save="Save vendor evidence" method="POST" action="{{ route('offers.store',$inquiry) }}">@csrf
<x-form-guide :steps="['vendor'=>'Vendor request','source'=>'Original reply','confirm'=>'Check & record']" /><div data-form-step="vendor" class="space-y-5"><x-field name="rfq_revision_id" label="Exact vendor request" type="select" required><option value="">Choose request revision</option>@foreach($requests as $r)<option value="{{ $r->id }}" @selected(old('rfq_revision_id')==$r->id)>{{ $r->rfq->vendor->company_name }} · {{ $r->rfq->reference }} v{{ $r->number }} · shipment v{{ $r->rfq->round->version->number }}{{ $r->number!==$r->rfq->current_number?' · old revision':'' }}</option>@endforeach</x-field>
<x-field name="alternative" label="Offer / alternative label" required maxlength="200" hint="One sailing or equipment option per offer. Never combine alternatives." />
<x-field name="supersedes_offer_id" label="Replaces an earlier quotation, only for a vendor revision" type="select"><option value="">Separate quotation / alternative</option>@foreach($priorOffers as $prior)<option value="{{ $prior->id }}" @selected(old('supersedes_offer_id')==$prior->id)>{{ $prior->vendor->company_name }} · {{ $prior->alternative }} · offer #{{ $prior->id }}</option>@endforeach</x-field></div><div data-form-step="source" class="space-y-5"><x-field name="source_kind" label="Original source" type="select">@foreach(['manual'=>'Commercial information entered by staff','email'=>'Matched vendor email','document'=>'Private vendor quotation document'] as $key=>$label)<option value="{{ $key }}" @selected(old('source_kind')===$key)>{{ $label }}</option>@endforeach</x-field>
<x-field name="message_id" label="Matched source email, when applicable" type="select"><option value="">No email selected</option>@foreach($messages as $m)<option value="{{ $m->id }}" @selected(old('message_id')==$m->id)>#{{ $m->id }} · {{ $m->source['subject']??'Vendor reply' }} · {{ \App\Models\MailMessage::CLASSES[$m->classification]??'Needs review' }}{{ $m->oldRevision()?' · old RFQ':'' }}</option>@endforeach</x-field>
<x-field name="manual_text" label="Original commercial note / quotation text" type="textarea" rows="7" maxlength="20000" hint="Preserve the exact quoted rates, conditions and how this information was obtained." />
<fieldset><legend class="label">Private source documents</legend><div class="space-y-3">@forelse($documents as $d)<label class="flex items-start gap-3 text-xs leading-6"><input type="checkbox" name="document_ids[]" value="{{ $d->id }}" @checked(in_array($d->id,old('document_ids',[]))) @disabled(!in_array($d->classification,['freight_quote','correspondence','other'])) class="mt-1 accent-accent"><span>{{ $d->original_name }} · {{ \App\Models\InquiryDocument::CLASSES[$d->classification] }} · {{ $d->scan_status }}</span></label>@empty<p class="hint">No private files. Upload a vendor quotation from the inquiry before choosing document capture.</p>@endforelse</div></fieldset>
</div><div data-form-step="confirm" class="space-y-5"><x-field name="association_reason" label="Vendor / source association evidence" type="textarea" required maxlength="2000" hint="Identify the vendor sender, quotation reference or manual source. Explain intentional use of a question/other email." />
<label class="flex items-start gap-3 text-xs leading-6"><input type="checkbox" name="association_confirmed" value="1" required class="mt-1 accent-accent">I verified that this is this vendor's commercial evidence for this exact RFQ, rather than a customer invoice, target budget or competitor reference.</label>
<x-button>Save vendor evidence</x-button></div></form>
<aside class="panel panel-pad"><h2 class="section-title">Evidence before amounts</h2><p class="mt-4 text-sm leading-7 text-slate-500">Capturing a reply does not approve its price. Questions, declines and automated messages stay outside the offer list until an agent deliberately captures relevant evidence.</p><p class="mt-4 text-sm leading-7 text-slate-500">Old RFQ replies remain linked to their original shipment. They stay visible but cannot become the current cost basis.</p><a class="text-link mt-6 inline-block text-xs" href="{{ route('inquiries.mail',$inquiry) }}">Inspect email timeline →</a><a class="text-link mt-4 block text-xs" href="{{ route('inquiries.show',$inquiry) }}">Upload a private quotation →</a></aside></div>
@endif
</x-layout>
