<x-layout title="Quotation review">
@include('offers.header',['heading'=>$offer->vendor->company_name,'description'=>$offer->alternative.' · Exact RFQ '.$offer->request->rfq->reference.' v'.$offer->request->number.' · Confirmed shipment v'.$offer->version->number])
<div class="mb-6 flex flex-wrap gap-3"><x-button :href="route('offers.index',$inquiry)" variant="secondary">Compare vendor offers</x-button><a class="btn btn-secondary" href="#commercial-source">Source evidence ↓</a><x-button :href="route('inquiries.extraction',$inquiry)" variant="secondary">Extract private documents</x-button></div>
@if($revision)<section class="panel panel-pad mb-6"><div class="flex flex-wrap items-center justify-between gap-3"><div><p class="eyebrow">Offer version {{ $revision->number }}</p><h2 class="mt-2 text-lg">{{ \App\Models\VendorOfferRevision::STATES[$revision->status] }}</h2><p class="hint">{{ count(array_filter($revision->calculation['lines'],fn($line)=>!$line['optional']&&$line['amount']!==null))?$revision->currency.' '.$revision->calculation['known_total'].' · '.($revision->complete_total!==null?'Reviewed baseline cost':'Known subtotal · incomplete'):'Cost unknown · no priced baseline charges yet' }}</p></div><p class="max-w-xl text-xs leading-6 text-slate-500">{{ $revision->reviewed_at?'Reviewed by '.$revision->reviewer->name.' · '.\App\Support\Processing::time($revision->reviewed_at):'Save and explicitly review each section and charge. AI does not approve costs.' }}</p></div>
@if($revision->gaps)<details open class="mt-4 rounded-xl bg-[#fff5e2] p-4"><summary class="cursor-pointer text-xs font-medium">Missing information · {{ count($revision->gaps) }}</summary><ul class="mt-3 list-disc space-y-1 pl-4 text-xs leading-6">@foreach($revision->gaps as $gap)<li>{{ $gap }}</li>@endforeach</ul></details>@endif
<details class="mt-5"><summary class="cursor-pointer text-xs font-medium">Saved calculation breakdown</summary><div class="mt-4 overflow-x-auto" tabindex="0" role="region" aria-label="Saved charge calculation"><table class="w-full min-w-[600px] text-left text-xs"><thead><tr><th class="pb-3">Charge</th><th>Quantity / billed</th><th>Rate / minimums</th><th>Native amount</th><th>Baseline status</th></tr></thead><tbody>@foreach($revision->calculation['lines'] as $l)<tr class="border-t border-slate-100"><td class="py-3 pr-3">{{ $l['description'] }}</td><td>{{ isset($l['quantity'])?\Brick\Math\BigDecimal::of($l['quantity'])->strippedOfTrailingZeros():'Unknown' }} / {{ isset($l['billed_quantity'])?\Brick\Math\BigDecimal::of($l['billed_quantity'])->strippedOfTrailingZeros():'—' }}</td><td>{{ $l['rate']??'Unknown' }} / {{ $l['minimum_charge']??'—' }} / {{ $l['minimum_quantity']??'—' }}</td><td>{{ $l['currency'] }} {{ $l['amount']??'Unknown' }}</td><td>{{ $l['optional']?'Optional':\App\Support\OfferCosts::STATES[$l['state']] }}</td></tr>@endforeach</tbody></table></div><p class="hint">{{ $revision->calculation['rounding'] }} Optional {{ $revision->currency }} {{ $revision->calculation['optional_total'] }}.</p></details>
</section>@endif
<div class="grid items-start gap-6 xl:grid-cols-[minmax(0,1.5fr)_minmax(0,1fr)]">
<div class="min-w-0 space-y-6">
@if($historical)<section class="panel panel-pad"><h2 class="section-title">Historical commercial record</h2><p class="mt-3 text-xs leading-6">This revision is read-only. Its original source, review decisions and calculation remain preserved.</p><pre class="mt-5 overflow-x-auto whitespace-pre-wrap break-words text-xs leading-6">{{ json_encode($revision?->payload??[],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE) }}</pre><a class="text-link mt-5 inline-block text-xs" href="{{ route('offers.edit',[$inquiry,$offer]) }}">Open current offer →</a></section>
@else
<form class="panel panel-pad space-y-7" method="POST" action="{{ route('offers.save',[$inquiry,$offer]) }}" data-offer-form data-fx-form data-unsaved data-guided-form data-guide-intent="draft">@csrf @method('PATCH')
<input type="hidden" name="expected_revision" value="{{ old('expected_revision',$offer->current_number) }}">
<x-form-guide :steps="['shipment'=>'Shipment','charges'=>'Charges','terms'=>'Terms','review'=>'Review & save']" /><section data-form-step="shipment"><h2 class="section-title">Does this offer match the shipment?</h2><div class="mt-5 grid gap-5 sm:grid-cols-2">
<x-field name="reference" label="Vendor quotation reference" :value="$p['reference']??''" required maxlength="200" />
<x-field name="currency" label="Offer total currency" type="select" data-fx-currency>@foreach(array_keys(config('offers.currency_precision')) as $c)<option @selected(old('currency',$p['currency'])===$c)>{{ $c }}</option>@endforeach</x-field>
<x-field name="received_on" label="Received date" type="date" :value="$p['received_on']" required /><x-field name="issued_on" label="Vendor issue date, if stated" type="date" :value="$p['issued_on']??''" />
<x-field name="mode" label="Quoted shipment mode" type="select">@foreach(['LCL','FCL'] as $m)<option @selected(old('mode',$p['mode'])===$m)>{{ $m }}</option>@endforeach</x-field>
<x-field name="scope" label="Quoted port / door scope" type="select">@foreach(\App\Support\Shipment::SCOPES as $key=>$label)<option value="{{ $key }}" @selected(old('scope',$p['scope'])===$key)>{{ $label }}</option>@endforeach</x-field>
@foreach(['origin_country'=>'Origin country','origin_location'=>'Origin port / location','destination_country'=>'Destination country','destination_location'=>'Destination port / location'] as $key=>$label)<x-field :name="$key" :label="$label" :value="$p[$key]??''" maxlength="500" />@endforeach
</div><label class="mt-5 flex items-start gap-3 text-xs leading-6"><input type="checkbox" name="review[scope]" value="1" @checked(old('review.scope',false)) class="mt-1 accent-accent">I checked the quoted route, mode and service boundary against confirmed shipment v{{ $offer->version->number }}.</label></section>
<section data-form-step="shipment" class="border-t border-slate-100 pt-6"><h2 class="section-title">Check the cargo quantities</h2><p class="hint">Confirmed cargo: {{ \App\Support\Shipment::totals($offer->version->snapshot['shipment'])['weight']??'Unknown' }} kg; calculated {{ \App\Support\Shipment::totals($offer->version->snapshot['shipment'])['volume']??'Unknown' }} CBM. Quantities come from this immutable shipment, with vendor-stated minimums applied separately.</p><div class="mt-5 space-y-5"><x-field name="quantity_statement" label="Vendor cargo / equipment assumptions" type="textarea" :value="$p['quantity_statement']??''" maxlength="2000" /><x-field name="volume_basis" label="Reviewed volume basis for CBM / W/M" type="select">@foreach(['calculated'=>'Calculated confirmed package dimensions','declared'=>'Client-declared confirmed volume'] as $key=>$label)<option value="{{ $key }}" @selected(old('volume_basis',$p['volume_basis']??'calculated')===$key)>{{ $label }}</option>@endforeach</x-field><label class="flex items-start gap-3 text-xs leading-6"><input type="checkbox" name="review[quantities]" value="1" @checked(old('review.quantities',false)) class="mt-1 accent-accent">I checked the vendor assumptions against confirmed quantities and equipment, including any volume discrepancy.</label></div></section>
<section data-form-step="charges" class="border-t border-slate-100 pt-6"><h2 class="section-title">What does the vendor charge?</h2><p class="hint">Required {{ implode(', ',\App\Support\OfferCosts::required($offer->version->snapshot['shipment'])) }}. Included, missing and optional charges stay distinct. No universal fees are invented.</p>
<div class="mt-5 space-y-5" data-charge-list>@foreach(old('lines',$p['lines']) as $i=>$line)@include('offers.line')@endforeach</div>
<button class="btn btn-secondary mt-5" type="button" data-add-charge>Add charge line</button>
</section>
<section data-form-step="charges" class="border-t border-slate-100 pt-6"><h2 class="section-title">Check the quoted total</h2><div class="mt-5 grid gap-5 sm:grid-cols-2"><x-field name="quoted_subtotal" label="Vendor's quoted subtotal, if stated" :value="$p['quoted_subtotal']??''" inputmode="decimal" /><x-field name="quoted_total" label="Vendor's original quoted total" :value="$p['quoted_total']??''" inputmode="decimal" /></div><div class="mt-5"><x-field name="total_not_stated_reason" label="Evidence that the vendor did not state a total" :value="$p['total_not_stated_reason']??''" hint="Only needed when no total was stated. Material discrepancies must be resolved in the actual charge lines." /></div>
<details class="mt-5"><summary class="cursor-pointer text-xs font-medium">Mixed-currency charges · reviewed FX</summary><div class="mt-4">@include('offers.fx',['fx'=>$p['fx']??[],'fxCurrencies'=>array_keys(config('offers.currency_precision')),'targetCurrency'=>old('currency',$p['currency'])])</div></details></section>
<section data-form-step="terms" class="border-t border-slate-100 pt-6"><h2 class="section-title">When is this price valid, and what is included?</h2><p class="hint">{{ config('offers.validity_rule') }}</p><div class="mt-5 grid gap-5 sm:grid-cols-2">
<x-field name="validity_statement" label="Original validity statement" type="select">@foreach(['dated'=>'Vendor provided a dated deadline','unknown'=>'Unknown','open_ended'=>'Open-ended statement','resolved'=>'Vendor-confirmed dated resolution'] as $key=>$label)<option value="{{ $key }}" @selected(old('validity_statement',$p['validity_statement'])===$key)>{{ $label }}</option>@endforeach</x-field>
<x-field name="valid_until" label="Vendor-confirmed valid until" type="datetime-local" :value="!empty($p['valid_until'])?\App\Support\InquiryWorkflow::local(\Carbon\CarbonImmutable::parse($p['valid_until'])):''" :hint="'Local time · '.$company->timezone" />
<x-field name="validity_resolution" label="Resolution evidence, if unknown / open-ended" type="textarea" :value="$p['validity_resolution']??''" maxlength="2000" />
<x-field name="payment_terms" label="Payment terms" type="textarea" :value="$p['payment_terms']??''" maxlength="2000" />
<x-field name="transit" label="Estimated transit / lead time" :value="$p['transit']??''" maxlength="2000" hint="Estimate only; no guarantee or booking." />
<x-field name="timing_assessment" label="Requested-date / conditions assessment" type="select">@foreach(['pending'=>'Unresolved','meets_requested'=>'Reviewed as meeting requested dates / conditions','not_met'=>'Does not meet the confirmed request'] as $key=>$label)<option value="{{ $key }}" @selected(old('timing_assessment',$p['timing_assessment'])===$key)>{{ $label }}</option>@endforeach</x-field>
<x-field name="timing_note" label="Timing / material conditions resolution evidence" type="textarea" :value="$p['timing_note']??''" maxlength="2000" />
<x-field name="conditions" label="Conditions / capacity qualifications" type="textarea" :value="$p['conditions']??''" maxlength="4000" />
<x-field name="inclusions" label="Stated inclusions" type="textarea" :value="$p['inclusions']??''" maxlength="2000" /><x-field name="exclusions" label="Stated exclusions" type="textarea" :value="$p['exclusions']??''" maxlength="2000" />
</div><div class="mt-5 space-y-3">@foreach(['validity'=>'I checked validity against the original vendor statement and retained any dated resolution.','terms'=>'I checked payment, inclusions/exclusions, stated tax, requested dates and material conditions.'] as $key=>$label)<label class="flex items-start gap-3 text-xs leading-6"><input type="checkbox" name="review[{{ $key }}]" value="1" @checked(old('review.'.$key,false)) class="mt-1 accent-accent">{{ $label }}</label>@endforeach</div></section>
<section data-form-step="review" class="border-t border-slate-100 pt-6"><h2 class="section-title mb-5">Record what you checked</h2><x-field name="change_reason" label="Correction / review note" type="textarea" required maxlength="2000" hint="Describe what you checked, corrected or left unresolved." /><div class="mt-5 flex flex-wrap gap-3"><button class="btn btn-secondary" name="intent" value="draft">Save new draft</button><button class="btn btn-primary" name="intent" value="review">Record commercial review</button></div><p class="hint">Each save preserves a new version. Unchecked fields remain gaps; review never finalizes a vendor selection.</p></section></form>
@endif
@if($revision&&!$historical)<section class="panel panel-pad"><h2 class="section-title">Optional quotation extraction</h2><p class="hint">{{ implode(' ',$aiReasons) }} Manual review above is fully usable.</p><x-button :href="route('offers.ai.scope',[$inquiry,$offer])" variant="secondary" class="mt-5">Preview source & paid scope</x-button>
@foreach($runs as $run)<article class="mt-6 border-t border-slate-100 pt-5"><h3 class="text-sm">Run #{{ $run->id }} · {{ $run->label() }}</h3>@if($run->is_demo)<p class="hint">Fictional proposal fixture · no AI provider request or usage.</p>@endif<p class="hint">{{ $run->error_message }}{{ $run->stale()?' Stale · cannot replace this offer.':'' }}</p>
@if($run->result && !$run->stale() && $run->review_outcome!=='applied')
<form class="mt-5 space-y-5" method="POST" action="{{ route('offers.ai.apply',[$inquiry,$offer,$run]) }}">@csrf<input type="hidden" name="expected_revision" value="{{ old('expected_revision',$offer->current_number) }}">
@foreach(\App\Support\OfferProposal::inspect($run,$run->result) as $j=>$proposal)
<fieldset class="rounded-xl border border-slate-200 p-4"><legend class="px-2 text-xs font-medium">{{ $proposal['field'] }}</legend><p class="text-sm">{{ $proposal['value']??'Unknown' }}</p><blockquote class="mt-3 border-l-2 border-accent pl-3 text-xs leading-6">“{{ $proposal['snippet'] }}”<span class="block text-slate-500">{{ $proposal['locator'] }}</span></blockquote><p class="hint">{{ $proposal['supported']?'Exact source snippet found':'Unsupported · remain unresolved or correct with evidence' }}{{ $proposal['uncertainty']?' · '.$proposal['uncertainty']:'' }}</p><div class="mt-4 space-y-4"><x-field :name="'decisions['.$j.'][decision]'" label="Your explicit decision" type="select"><option value="unresolved">Leave unresolved</option><option value="accept" @disabled(!$proposal['supported']||$proposal['uncertainty']!=='')>Accept supported value</option><option value="correct">Correct with evidence</option><option value="reject">Reject proposal</option></x-field><x-field :name="'decisions['.$j.'][value]'" label="Corrected value, when applicable" /><x-field :name="'decisions['.$j.'][reason]'" label="Correction evidence / decision reason" /></div></fieldset>
@endforeach
<x-button variant="secondary">Record decisions as a new draft</x-button></form>
@endif</article>@endforeach</section>@endif
</div>
<aside id="commercial-source" class="order-first min-w-0 space-y-6 xl:order-last xl:sticky xl:top-6">
<section class="panel panel-pad"><p class="eyebrow">Original evidence</p><h2 class="mt-2 section-title">Read alongside the review</h2><p class="hint">{{ $offer->source['association_reason'] }}</p>@if(!empty($offer->source['old_reply']))<p class="mt-4 rounded-xl bg-[#fff5e2] p-4 text-xs leading-6">Reply to an old request · preserve this lineage. It is outside current ranking.</p>@endif
@if(!empty($offer->source['message_id']))<a class="text-link mt-4 block text-xs" href="{{ route('mail.message',$offer->source['message_id']) }}">Open matched source email →</a>@endif
@if(!empty($offer->source['text']))<pre class="mt-5 max-h-[480px] overflow-auto whitespace-pre-wrap break-words rounded-xl bg-slate-50 p-4 text-xs leading-6">{{ $offer->source['text'] }}</pre>@endif
@foreach($offer->source['documents']??[] as $d)<a class="text-link mt-4 block break-all text-xs" href="{{ route('inquiries.documents.show',[$inquiry,$d['id']]) }}">{{ $d['name'] }} · private original →</a><p class="hint">Original checksum {{ substr($d['checksum'],0,16) }}… · inspect unscanned files carefully.</p>@endforeach
@foreach($sources as $source)@if(($source['lineage']['kind']??null)==='document')<details class="mt-5"><summary class="cursor-pointer text-xs">{{ $source['locator'] }}</summary><pre class="mt-3 max-h-80 overflow-auto whitespace-pre-wrap break-words text-xs leading-6">{{ $source['text'] }}</pre></details>@endif @endforeach
</section>
<details class="panel panel-pad"><summary class="text-sm font-medium">Earlier offer versions</summary><h2 class="section-title mt-5">Immutable versions</h2><div class="mt-4 space-y-3">@forelse($offer->revisions as $old)<a class="text-link block text-xs leading-6" href="{{ route('offers.edit',[$inquiry,$offer]).'?version='.$old->number }}">v{{ $old->number }} · {{ \App\Models\VendorOfferRevision::STATES[$old->status] }} · {{ $old->change_reason }}</a>@empty<p class="hint">The first save creates version 1.</p>@endforelse</div></details>
</aside></div>
</x-layout>
