<x-layout title="Vendor comparison">
@include('offers.header',['heading'=>'Compare with clarity.','description'=>'A fair view of reviewed vendor costs for one confirmed shipment. Unknown charges stay visible.'])
<div class="mb-6 flex flex-wrap gap-3"><x-button :href="route('offers.capture',$inquiry)">Capture quotation</x-button><x-button :href="route('inquiries.sourcing',$inquiry)" variant="secondary">Vendor requests</x-button></div>
@if($selection)<section class="panel panel-pad mb-6"><div class="flex flex-wrap items-center justify-between gap-4"><div><p class="eyebrow">{{ $selection->kind==='final'?'Final selection':'Provisional preference' }}</p><h2 class="mt-2 text-lg">{{ $selection->snapshot['vendor']['name'] }} · {{ $selection->snapshot['alternative'] }}</h2><p class="hint">{{ \App\Support\OfferEligibility::selectionReasons($selection)?'Needs renewed eligibility review':'Current reviewed cost basis' }} · {{ \App\Support\Processing::time($selection->selected_at) }}</p></div><x-button :href="route('offers.selection',[$inquiry,$selection])" variant="secondary">Inspect saved cost basis</x-button></div></section>@endif
<section class="panel panel-pad mb-6">
<div class="flex flex-wrap justify-between gap-4"><div><h2 class="section-title">Comparison basis</h2><p class="hint">Confirmed shipment v{{ $inquiry->shipment_revision }} · {{ $inquiry->shipment['mode'] }} · {{ \App\Support\Shipment::SCOPES[$inquiry->shipment['scope']] }} · required {{ implode(', ',\App\Support\OfferCosts::required($inquiry->shipment)) }}</p></div><span class="text-xs text-slate-500">{{ $comparison?'Saved comparison #'.$comparison->id:'Not yet saved' }}</span></div>
<form method="POST" action="{{ route('offers.comparison',$inquiry) }}" class="mt-6 space-y-5" data-fx-form>@csrf<input type="hidden" name="expected_comparison" value="{{ old('expected_comparison',$comparison?->id??0) }}">
<div class="grid gap-5 sm:grid-cols-2"><x-field name="currency" label="Common comparison currency" type="select" data-fx-currency>@foreach(array_keys(config('offers.currency_precision')) as $c)<option @selected(old('currency',$comparison?->currency??$company->currency)===$c)>{{ $c }}</option>@endforeach</x-field><x-field name="reason" label="Comparison / FX review note" required maxlength="2000" :value="$comparison?->reason??'Use the confirmed shipment and reviewed vendor costs.'" /></div>
@php($currencies=array_values(array_unique(array_map(fn($row)=>$row['revision']->currency,$rows))))
@include('offers.fx',['fx'=>$comparison?->fx??[],'fxCurrencies'=>$currencies,'targetCurrency'=>old('currency',$comparison?->currency??$company->currency)])
<x-button variant="secondary">Save comparison basis</x-button></form>
</section>
@if($captured->count())<section class="panel panel-pad mb-6"><h2 class="section-title">Captured sources awaiting commercial entry</h2><div class="mt-4 space-y-3">@foreach($captured as $draft)<a class="text-link block text-xs leading-6" href="{{ route('offers.edit',[$inquiry,$draft]) }}">{{ $draft->vendor->company_name }} · {{ $draft->alternative }} · Draft, no reviewed cost →</a>@endforeach</div></section>@endif
@if(!$rows)<x-empty title="No vendor quotations yet" description="Capture a matched email, private quotation or manual commercial note to begin review." :href="route('offers.capture',$inquiry)" action="Capture first quotation"><x-button :href="route('offers.capture',$inquiry)">Capture first quotation</x-button></x-empty>
@else
<div class="offer-comparison-grid">
@foreach($rows as $row)@php($r=$row['revision'])@php($o=$row['offer'])@php($hasKnown=count(array_filter($r->calculation['lines'],fn($line)=>!$line['optional']&&$line['amount']!==null))>0)
<article class="panel overflow-hidden"><div class="border-b border-slate-100 p-6"><p class="eyebrow">{{ $o->alternative }}</p><h2 class="mt-2 text-xl font-semibold tracking-tight">{{ $o->vendor->company_name }}</h2><div class="mt-3 flex flex-wrap gap-2"><x-offer-badge :tone="$row['reasons']?'amber':'green'">{{ \App\Models\VendorOfferRevision::STATES[$r->status] }}</x-offer-badge>@if($row['lowest'])<x-offer-badge tone="blue">Lowest comparable cost</x-offer-badge>@endif</div><p class="mt-5 text-[30px] font-semibold tracking-tight tabular-nums">{{ $hasKnown?$r->currency.' '.$r->calculation['known_total']:'Cost unknown' }}</p><p class="hint">{{ !$hasKnown?'No priced baseline charges yet':($r->complete_total!==null?'Reviewed baseline cost':'Known subtotal · incomplete') }}</p>@if($row['total']!==null && $comparison->currency!==$r->currency)<p class="mt-2 text-sm">{{ $comparison->currency }} {{ $row['total'] }} · indicative comparison</p>@endif</div>
<div class="space-y-5 p-6">
@if($row['reasons'])<div class="rounded-xl bg-[#fff5e2] p-4"><p class="mb-2 text-xs font-medium">Outside comparable ranking</p><ul class="list-disc space-y-1 pl-4 text-xs leading-6">@foreach($row['reasons'] as $reason)<li>{{ $reason }}</li>@endforeach</ul>@if($r->gaps)<p class="mt-3 text-xs font-medium">Information to resolve</p><ul class="mt-2 list-disc space-y-1 pl-4 text-xs leading-6">@foreach(array_slice($r->gaps,0,3) as $gap)<li>{{ $gap }}</li>@endforeach</ul>@if(count($r->gaps)>3)<details class="mt-3"><summary class="cursor-pointer text-xs">{{ count($r->gaps)-3 }} more review gaps</summary><ul class="mt-2 list-disc space-y-1 pl-4 text-xs leading-6">@foreach(array_slice($r->gaps,3) as $gap)<li>{{ $gap }}</li>@endforeach</ul></details>@endif @endif</div>@else<p class="text-xs font-medium text-[#28734b]">Complete, current and equivalent to this baseline.</p>@endif
<dl class="space-y-3 text-xs leading-6"><div><dt class="text-slate-500">Validity</dt><dd>{{ !empty($r->payload['valid_until'])?\App\Support\Processing::time(\Carbon\CarbonImmutable::parse($r->payload['valid_until'])):'Unresolved · dated resolution required' }}</dd></div><div><dt class="text-slate-500">Estimated transit / timing</dt><dd>{{ $r->payload['transit']??'Not stated' }} · {{ ['pending'=>'Requested window unresolved','meets_requested'=>'Requested window reviewed','not_met'=>'Does not meet the requested window'][$r->payload['timing_assessment']??'pending'] }}</dd></div><div><dt class="text-slate-500">Payment / qualifications</dt><dd>{{ $r->payload['payment_terms']??'Unknown' }}<br>{{ $r->payload['conditions']??'No conditions recorded' }}</dd></div><div><dt class="text-slate-500">Optional services</dt><dd>{{ $r->currency }} {{ $r->calculation['optional_total'] }} · excluded from baseline</dd></div></dl>
<details><summary class="cursor-pointer text-xs font-medium">Charge breakdown & exclusions</summary><div class="mt-3 space-y-3">@foreach($r->calculation['lines'] as $line)<div class="border-t border-slate-100 pt-3 text-xs leading-6"><p>{{ $line['description'] }}{{ $line['optional']?' · optional':'' }}</p><p class="text-slate-500">{{ \App\Support\OfferCosts::STATES[$line['state']] }} · {{ \App\Support\OfferCosts::BASES[$line['basis']] }} · {{ $line['amount']===null?'Amount unknown':$line['currency'].' '.$line['amount'] }}</p>@if($line['billed_quantity']!==null)<p class="text-slate-500">Billed quantity {{ \Brick\Math\BigDecimal::of($line['billed_quantity'])->strippedOfTrailingZeros() }} · min charge {{ $line['minimum_charge']??'none' }} · min quantity {{ $line['minimum_quantity']??'none' }}</p>@endif</div>@endforeach<p class="text-xs leading-6">{{ $r->payload['exclusions']??'' }}</p></div></details>
<x-button :href="route('offers.edit',[$inquiry,$o])" variant="secondary">Review offer v{{ $r->number }}</x-button>
@if($comparison)<form method="POST" action="{{ route('offers.select',$inquiry) }}" class="space-y-4 border-t border-slate-100 pt-5" data-confirm-form="Save this exact offer version and comparison as your chosen cost basis?">@csrf<input type="hidden" name="offer_revision_id" value="{{ $r->id }}"><input type="hidden" name="comparison_id" value="{{ $comparison->id }}"><input type="hidden" name="expected_selection" value="{{ old('expected_selection',$selection?->id??0) }}"><x-field :name="'reason'" :id="'selection-reason-'.$r->id" label="Agent selection reason" type="textarea" required minlength="8" maxlength="2000" hint="Record service, timing or conditions, especially when choosing a higher cost." /><div class="flex flex-wrap gap-3">@if(!$row['reasons'])<button class="btn btn-primary" name="kind" value="final">Finalize this offer</button>@endif<button class="btn btn-secondary" name="kind" value="provisional">Mark provisional</button></div></form>@endif
</div></article>
@endforeach
</div>
<p class="mt-5 text-xs leading-6 text-slate-500">{{ count(array_filter($rows,fn($row)=>!$row['reasons'])) }} comparable offer(s). A single complete offer may be selected. Review does not confirm capacity or a booking.</p>
@endif
@if($history->count())<section class="panel panel-pad mt-6"><h2 class="section-title">Selection history</h2><div class="mt-4 divide-y divide-slate-100">@foreach($history as $h)<a class="flex flex-wrap justify-between gap-2 py-4 text-xs text-link" href="{{ route('offers.selection',[$inquiry,$h]) }}"><span>#{{ $h->id }} · {{ ucfirst($h->kind) }} · {{ $h->snapshot['vendor']['name'] }}</span><span>{{ $h->superseded_at?'Superseded · ':'' }}{{ \App\Support\Processing::time($h->selected_at) }}</span></a>@endforeach</div></section>@endif
</x-layout>
