<x-layout title="Saved vendor cost basis">
@include('offers.header',['heading'=>$selection->kind==='final'?'Saved cost basis.':'Provisional preference.','description'=>$s['vendor']['name'].' · '.$s['alternative'].' · Selection #'.$selection->id])
<div class="mb-6 flex flex-wrap gap-3"><x-button :href="route('offers.index',$inquiry)" variant="secondary">Return to comparison</x-button><x-button :href="route('quotations.index',$inquiry)">Prepare client quotation</x-button><x-button :href="route('offers.edit',[$inquiry,$selection->revision->offer]).'?version='.$s['offer_revision']" variant="secondary">Exact reviewed offer v{{ $s['offer_revision'] }}</x-button></div>
<section class="panel panel-pad mb-6">@if($reasons)<p class="eyebrow text-[#855600]">Currently ineligible for pricing</p><ul class="mt-3 list-disc space-y-1 pl-4 text-xs leading-6">@foreach($reasons as $reason)<li>{{ $reason }}</li>@endforeach</ul>@else<p class="eyebrow text-[#28734b]">Current eligible vendor cost basis</p><p class="hint">Eligibility is checked again at every future pricing/release gate. This records vendor cost and does not confirm a booking.</p>@endif</section>
<div class="grid items-start gap-6 lg:grid-cols-[minmax(0,1.4fr)_minmax(0,1fr)]"><div class="space-y-6 min-w-0">
<section class="panel panel-pad"><p class="eyebrow">Frozen vendor cost</p><h2 class="mt-3 text-4xl font-semibold tracking-tight">{{ $s['calculation']['currency'] }} {{ $s['calculation']['complete_total']??$s['calculation']['known_total'] }}</h2><p class="hint">{{ $s['calculation']['complete_total']===null?'Known subtotal · incomplete':'Reviewed required baseline' }} · optional {{ $s['calculation']['currency'] }} {{ $s['calculation']['optional_total'] }} excluded</p>@if($s['comparison']['total']!==null)<p class="mt-4 text-sm">{{ $s['comparison']['currency'] }} {{ $s['comparison']['total'] }} · frozen indicative comparison</p>@endif
<dl class="mt-6 grid gap-5 sm:grid-cols-2 text-xs leading-6"><div><dt class="text-slate-500">Agent's decision</dt><dd>{{ $s['reason'] }}</dd></div><div><dt class="text-slate-500">Selected by</dt><dd>{{ $s['selected_by']['name'] }} · {{ \App\Support\Processing::time($selection->selected_at) }}</dd></div><div><dt class="text-slate-500">Confirmed shipment</dt><dd>Version {{ $selection->revision->offer->version->number }} · record #{{ $s['shipment_version_id'] }} · {{ $s['commercial']['mode'] }} · {{ \App\Support\Shipment::SCOPES[$s['commercial']['scope']] }}</dd></div><div><dt class="text-slate-500">Exact lineage</dt><dd>RFQ revision #{{ $s['rfq_revision_id'] }} · reviewed offer #{{ $s['offer_revision_id'] }} · comparison #{{ $s['comparison']['id'] }}</dd></div></dl>
</section>
<section class="panel panel-pad"><h2 class="section-title">Reviewed charges</h2><div class="mt-5 divide-y divide-slate-100">@foreach($s['calculation']['lines'] as $line)<div class="py-4 text-xs leading-6"><div class="flex flex-wrap justify-between gap-3"><p class="font-medium">{{ $line['description'] }}{{ $line['optional']?' · optional':'' }}</p><p>{{ $line['currency'] }} {{ $line['amount']??'Unknown' }}</p></div><p class="text-slate-500">{{ \App\Support\OfferCosts::STATES[$line['state']] }} · {{ \App\Support\OfferCosts::BASES[$line['basis']] }} · billed {{ isset($line['billed_quantity'])?\Brick\Math\BigDecimal::of($line['billed_quantity'])->strippedOfTrailingZeros():'—' }} · source {{ $line['source_ref'] }}</p><p class="text-slate-500">Minimum charge {{ $line['minimum_charge']??'none' }} · minimum quantity {{ $line['minimum_quantity']??'none' }} · tax {{ $line['tax_treatment'] }}</p>@if($line['issues'])<p>{{ implode(' ',$line['issues']) }}</p>@endif</div>@endforeach</div><p class="hint">{{ $s['calculation']['rounding'] }}</p></section>
</div><aside class="space-y-6 min-w-0">
<section class="panel panel-pad"><h2 class="section-title">Validity & material conditions</h2><dl class="mt-5 space-y-4 text-xs leading-6">@foreach(['valid_until'=>'Valid until','transit'=>'Estimated transit','timing_note'=>'Timing assessment evidence','payment_terms'=>'Payment terms','quantity_statement'=>'Cargo assumptions','conditions'=>'Conditions / capacity','inclusions'=>'Inclusions','exclusions'=>'Exclusions'] as $key=>$label)<div><dt class="text-slate-500">{{ $label }}</dt><dd class="whitespace-pre-line break-words">{{ $key==='valid_until'&&!empty($s['commercial'][$key])?\App\Support\Processing::time(\Carbon\CarbonImmutable::parse($s['commercial'][$key])):($s['commercial'][$key]??'Not stated') }}</dd></div>@endforeach</dl></section>
<section class="panel panel-pad"><h2 class="section-title">Frozen FX & evidence</h2>@foreach(['Offer charge conversions'=>$s['calculation']['fx'],'Comparison conversions'=>$s['comparison']['fx']] as $label=>$fx)<h3 class="mt-4 text-xs font-medium">{{ $label }}</h3>@forelse($fx as $f)<p class="mt-2 text-xs leading-6">{{ $f['from'] }} → {{ $f['to'] }} · {{ $f['direction'] }} {{ $f['rate'] }}<br>{{ $f['date'] }} · {{ $f['source'] }}</p>@empty<p class="hint">Same currency · no conversion input.</p>@endforelse @endforeach
<p class="hint">{{ $s['source']['association_reason'] }}</p>@if(!empty($s['source']['message_id']))<a class="text-link mt-4 block text-xs" href="{{ route('mail.message',$s['source']['message_id']) }}">Original email →</a>@endif
@foreach($s['source']['documents']??[] as $d)<a class="text-link mt-4 block break-all text-xs" href="{{ route('inquiries.documents.show',[$inquiry,$d['id']]) }}">{{ $d['name'] }} →</a>@endforeach
<p class="mt-5 break-all text-[10px] leading-5 text-slate-500">Cost-basis SHA-256 {{ $selection->digest }}</p><p class="hint">Historical evidence remains unchanged after offer, shipment, FX or validity changes.</p></section>
</aside></div>
</x-layout>
